### PR TITLE
Fix a couple of issues in LDAP

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/2280
Closes https://github.com/eXist-db/exist/issues/2281

### CODE REVIEW

**Comment by simar0at** [comment]
Sorry, this does not seem to work for me. It seems to produce a deadlock situation.
I applied https://patch-diff.githubusercontent.com/raw/eXist-db/exist/pull/2327.diff on top of f62496a5e and
4dddce068 and rebuilt.
Admin client does not crash.
User manager: No accounts, no groups.
On shutdown:
```
SYSTEM INFO
Database instance: exist
-------------------------------------------------------------------
Threads currently waiting for a lock:
=====================================
```

**Comment by adamretter** [comment]
@simar0at When you believe that it has potentially deadlocked, could you provide the output from `jstack` please?

**Comment by simar0at** [comment]
Oops, my fault. Didn't wait long enough. No deadlock here.
It's an infinite loop:
Thanks to jstack we have
```
"qtp577442875-36" #36 prio=5 os_prio=0 tid=0x000000001f603000 nid=0xa30 in Object.wait() [0x000000002414c000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.exist.storage.lock.ReentrantReadWriteLock.acquire(ReentrantReadWriteLock.java:159)
	- locked <0x000000008125f1e8> (a org.exist.storage.lock.ReentrantReadWriteLock)
	at org.exist.collections.MutableCollection.getDocument(MutableCollection.java:670)
	at org.exist.config.Configurator.parse(Configurator.java:1168)
	at org.exist.security.AbstractPrincipal.<init>(AbstractPrincipal.java:65)
	at org.exist.security.AbstractGroup.<init>(AbstractGroup.java:57)
	at org.exist.security.internal.GroupImpl.<init>(GroupImpl.java:50)
	at org.exist.security.internal.SecurityManagerImpl.addGroup(SecurityManagerImpl.java:584)
	at org.exist.security.realm.ldap.LDAPRealm.createGroupInDatabase(LDAPRealm.java:410)
	at org.exist.security.realm.ldap.LDAPRealm.getGroup(LDAPRealm.java:648)
	- locked <0x000000008125e7a8> (a org.exist.security.realm.ldap.LDAPRealm)
	...
	at org.exist.security.realm.ldap.LDAPRealm.getGroup(LDAPRealm.java:616)
	- locked <0x000000008125e7a8> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.hasGroup(LDAPRealm.java:664)
	at org.exist.security.internal.SecurityManagerImpl.addGroup(SecurityManagerImpl.java:580)
	at org.exist.security.realm.ldap.LDAPRealm.createGroupInDatabase(LDAPRealm.java:410)
	at org.exist.security.realm.ldap.LDAPRealm.getGroup(LDAPRealm.java:648)
	- locked <0x000000008125e7a8> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.getGroup(LDAPRealm.java:616)
	- locked <0x000000008125e7a8> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.hasGroup(LDAPRealm.java:664)
	at org.exist.security.internal.SecurityManagerImpl.addGroup(SecurityManagerImpl.java:580)
	at org.exist.security.realm.ldap.LDAPRealm.createGroupInDatabase(LDAPRealm.java:410)
	at org.exist.security.realm.ldap.LDAPRealm.getGroup(LDAPRealm.java:648)
	- locked <0x000000008125e7a8> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.getGroup(LDAPRealm.java:616)
	- locked <0x000000008125e7a8> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.hasGroup(LDAPRealm.java:664)
	at org.exist.security.internal.SecurityManagerImpl.addGroup(SecurityManagerImpl.java:580)
	at org.exist.security.realm.ldap.LDAPRealm.createGroupInDatabase(LDAPRealm.java:410)

   Locked ownable synchronizers:
	- None
```

**Comment by adamretter** [comment]
@simar0at I added another patch. How's it look now?

**Comment by simar0at** [comment]
No, still no joy but progress. Groups are now downloaded to cache (hundreds at my workplace, maybe that's not intended). Now with my modified patch (build issue, override final method) I get an elaborate infinite loop for accounts:
```
"qtp98801744-41" #41 prio=5 os_prio=0 tid=0x0000000020486800 nid=0x1278 in Object.wait() [0x0000000024e86000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.sun.jndi.ldap.Connection.readReply(Connection.java:493)
	- locked <0x00000000dbf59758> (a com.sun.jndi.ldap.LdapRequest)
	at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:365)
	- locked <0x00000000dbf48268> (a com.sun.jndi.ldap.LdapClient)
	at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214)
	- locked <0x00000000dbf48268> (a com.sun.jndi.ldap.LdapClient)
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2791)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.exist.security.realm.ldap.LdapContextFactory.getLdapContext(LdapContextFactory.java:151)
	at org.exist.security.realm.ldap.LDAPRealm.getContextWithCredentials(LDAPRealm.java:441)
	at org.exist.security.realm.ldap.LDAPRealm.getContext(LDAPRealm.java:427)
	at org.exist.security.realm.ldap.LDAPRealm.getContext(LDAPRealm.java:418)
	at org.exist.security.realm.ldap.LDAPRealm.getAccount(LDAPRealm.java:461)
	- locked <0x0000000081089648> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.hasAccount(LDAPRealm.java:536)
	at org.exist.security.internal.SecurityManagerImpl.hasAccount(SecurityManagerImpl.java:375)
	at org.exist.config.ConfigurationDocumentTrigger$PrincipalType.hasPrincipal(ConfigurationDocumentTrigger.java:504)
	at org.exist.config.ConfigurationDocumentTrigger.processPrincipal(ConfigurationDocumentTrigger.java:315)
	at org.exist.config.ConfigurationDocumentTrigger.endElement(ConfigurationDocumentTrigger.java:272)
	at org.exist.collections.triggers.DocumentTriggers.endElement(DocumentTriggers.java:167)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.collections.MutableCollection.lambda$validateXMLResource$3(MutableCollection.java:1311)
	at org.exist.collections.MutableCollection$$Lambda$2790/1963351031.accept(Unknown Source)
	at org.exist.collections.MutableCollection.validateXMLResourceInternal(MutableCollection.java:1430)
	at org.exist.collections.MutableCollection.validateXMLResource(MutableCollection.java:1298)
	at org.exist.collections.MutableCollection.validateXMLResource(MutableCollection.java:1291)
	at org.exist.config.Configurator.save(Configurator.java:1302)
	at org.exist.config.Configurator.parse(Configurator.java:1195)
	at org.exist.security.AbstractPrincipal.<init>(AbstractPrincipal.java:65)
	at org.exist.security.AbstractAccount.<init>(AbstractAccount.java:67)
	at org.exist.security.internal.AccountImpl.<init>(AccountImpl.java:157)
	at org.exist.security.internal.SecurityManagerImpl.addAccount(SecurityManagerImpl.java:635)
	at org.exist.security.internal.SecurityManagerImpl.addAccount(SecurityManagerImpl.java:609)
	at org.exist.security.realm.ldap.LDAPRealm.lambda$createAccountInDatabase$1(LDAPRealm.java:362)
	at org.exist.security.realm.ldap.LDAPRealm$$Lambda$2788/688582413.apply(Unknown Source)
	at org.exist.security.realm.ldap.LDAPRealm.executeAsSystemUser(LDAPRealm.java:403)
	at org.exist.security.realm.ldap.LDAPRealm.createAccountInDatabase(LDAPRealm.java:330)
	at org.exist.security.realm.ldap.LDAPRealm.getAccount(LDAPRealm.java:517)
	- locked <0x0000000081089648> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.getAccount(LDAPRealm.java:462)
	- locked <0x0000000081089648> (a org.exist.security.realm.ldap.LDAPRealm)
	...
	at org.exist.security.realm.ldap.LDAPRealm.hasAccount(LDAPRealm.java:536)
	at org.exist.security.internal.SecurityManagerImpl.hasAccount(SecurityManagerImpl.java:375)
	at org.exist.config.ConfigurationDocumentTrigger$PrincipalType.hasPrincipal(ConfigurationDocumentTrigger.java:504)
	at org.exist.config.ConfigurationDocumentTrigger.processPrincipal(ConfigurationDocumentTrigger.java:315)
	at org.exist.config.ConfigurationDocumentTrigger.endElement(ConfigurationDocumentTrigger.java:272)
	at org.exist.collections.triggers.DocumentTriggers.endElement(DocumentTriggers.java:167)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.collections.MutableCollection.lambda$validateXMLResource$3(MutableCollection.java:1311)
	at org.exist.collections.MutableCollection$$Lambda$2790/1963351031.accept(Unknown Source)
	at org.exist.collections.MutableCollection.validateXMLResourceInternal(MutableCollection.java:1430)
	at org.exist.collections.MutableCollection.validateXMLResource(MutableCollection.java:1298)
	at org.exist.collections.MutableCollection.validateXMLResource(MutableCollection.java:1291)
	at org.exist.config.Configurator.save(Configurator.java:1302)
	at org.exist.config.Configurator.parse(Configurator.java:1195)
	at org.exist.security.AbstractPrincipal.<init>(AbstractPrincipal.java:65)
	at org.exist.security.AbstractAccount.<init>(AbstractAccount.java:67)
	at org.exist.security.internal.AccountImpl.<init>(AccountImpl.java:157)
	at org.exist.security.internal.SecurityManagerImpl.addAccount(SecurityManagerImpl.java:635)
	at org.exist.security.internal.SecurityManagerImpl.addAccount(SecurityManagerImpl.java:609)
	at org.exist.security.realm.ldap.LDAPRealm.lambda$createAccountInDatabase$1(LDAPRealm.java:362)
	at org.exist.security.realm.ldap.LDAPRealm$$Lambda$2788/688582413.apply(Unknown Source)
	at org.exist.security.realm.ldap.LDAPRealm.executeAsSystemUser(LDAPRealm.java:403)
	at org.exist.security.realm.ldap.LDAPRealm.createAccountInDatabase(LDAPRealm.java:330)
	at org.exist.security.realm.ldap.LDAPRealm.getAccount(LDAPRealm.java:517)
	- locked <0x0000000081089648> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.getAccount(LDAPRealm.java:462)
	- locked <0x0000000081089648> (a org.exist.security.realm.ldap.LDAPRealm)
	at org.exist.security.realm.ldap.LDAPRealm.hasAccount(LDAPRealm.java:536)
	at org.exist.security.internal.SecurityManagerImpl.hasAccount(SecurityManagerImpl.java:375)
	at org.exist.config.ConfigurationDocumentTrigger$PrincipalType.hasPrincipal(ConfigurationDocumentTrigger.java:504)
	at org.exist.config.ConfigurationDocumentTrigger.processPrincipal(ConfigurationDocumentTrigger.java:315)
	at org.exist.config.ConfigurationDocumentTrigger.endElement(ConfigurationDocumentTrigger.java:272)
	at org.exist.collections.triggers.DocumentTriggers.endElement(DocumentTriggers.java:167)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)

   Locked ownable synchronizers:
	- None
```
patch was
```
 .../org/exist/security/realm/ldap/LDAPRealm.java   | 17 ++++++++++-
 src/org/exist/security/AbstractRealm.java          | 33 +++++++++++++++++-----
 .../security/internal/SecurityManagerImpl.java     |  8 ++++--
 .../security/management/AccountsManagement.java    | 15 ++++++----
 .../security/management/GroupsManagement.java      | 15 ++++++----
 6 files changed, 67 insertions(+), 24 deletions(-)

diff --git a/extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java b/extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
index 586d3c3f8..9b82a7aee 100644
--- a/extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
+++ b/extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
@@ -531,6 +531,11 @@ public class LDAPRealm extends AbstractRealm {
         }
     }
 
+    @Override
+    public boolean hasAccount(final String name) {
+        return getAccount(name) != null;
+    }
+
     /**
      * The binary data is in form:
      * byte[0] - revision level
@@ -654,6 +659,11 @@ public class LDAPRealm extends AbstractRealm {
         }
     }
 
+    @Override
+    public boolean hasGroup(final String name) {
+        return getGroup((Subject)null, getSecurityManager().getDatabase().getActiveBroker(), name) != null;
+    }
+
     private String addDomainPostfix(final String principalName) {
         String name = principalName;
         if (!name.contains("@")) {
@@ -788,7 +798,7 @@ public class LDAPRealm extends AbstractRealm {
         return null;
     }
 
-    private SearchResult findGroupByGroupName(final DirContext ctx, final String groupName) throws NamingException {
+    private @Nullable SearchResult findGroupByGroupName(final DirContext ctx, final String groupName) throws NamingException {
 
         if (!checkGroupRestrictionList(groupName)) {
             return null;
@@ -1237,6 +1247,11 @@ public class LDAPRealm extends AbstractRealm {
 
             //find the dn of the group
             SearchResult searchResult = findGroupByGroupName(ctx, removeDomainPostfix(name));
+            if (searchResult == null) {
+                // no such group
+                return groupMembers;
+            }
+
             final LDAPSearchContext search = ensureContextFactory().getSearch();
             final String dnGroup = (String) searchResult.getAttributes().get(search.getSearchGroup().getSearchAttribute(LDAPSearchAttributeKey.DN)).get();
 
diff --git a/src/org/exist/security/AbstractRealm.java b/src/org/exist/security/AbstractRealm.java
index 24b36a210..f865deb01 100644
--- a/src/org/exist/security/AbstractRealm.java
+++ b/src/org/exist/security/AbstractRealm.java
@@ -273,13 +273,21 @@ public abstract class AbstractRealm implements Realm, Configurable {
     }
 
     @Override
-    public final boolean hasAccount(final String accountName) {
-        return usersByName.read(principalDb -> principalDb.containsKey(accountName));
+    public boolean hasAccount(final String accountName) {
+        return hasAccountLocal(accountName);
     }
 
     @Override
-    public final boolean hasAccount(Account account) {
-        return hasAccount(account.getName());
+    public boolean hasAccount(final Account account) { return hasAccountLocal(account); }
+
+    @Override
+    public boolean hasAccountLocal(final Account account) {
+        return hasAccountLocal(account.getName());
+    }
+
+    @Override
+    public boolean hasAccountLocal(final String accountName) {
+        return usersByName.read(principalDb -> principalDb.containsKey(accountName));
     }
 
     @Override
@@ -288,14 +296,25 @@ public abstract class AbstractRealm implements Realm, Configurable {
     }
 
     //Groups management methods
+
+    @Override
+    public boolean hasGroup(final Group group) {
+        return hasGroupLocal(group);
+    }
+
+    @Override
+    public boolean hasGroup(final String name) {
+        return hasGroupLocal(name);
+    }
+
     @Override
-    public final boolean hasGroup(final String groupName) {
+    public boolean hasGroupLocal(final String groupName) {
         return groupsByName.read(principalDb -> principalDb.containsKey(groupName));
     }
 
     @Override
-    public final boolean hasGroup(Group role) {
-        return hasGroup(role.getName());
+    public final boolean hasGroupLocal(final Group role) {
+        return hasGroupLocal(role.getName());
     }
 
     @Override
diff --git a/src/org/exist/security/internal/SecurityManagerImpl.java b/src/org/exist/security/internal/SecurityManagerImpl.java
index 034ea4449..a6eaecf4f 100644
--- a/src/org/exist/security/internal/SecurityManagerImpl.java
+++ b/src/org/exist/security/internal/SecurityManagerImpl.java
@@ -577,8 +577,8 @@ public class SecurityManagerImpl implements SecurityManager, BrokerPoolService {
         }
         
         final AbstractRealm registeredRealm = (AbstractRealm)findRealmForRealmId(group.getRealmId());
-        if (registeredRealm.hasGroup(group.getName())) {
-            throw new ConfigurationException("The group '" + group.getName() + "' at realm '" + group.getRealmId() + "' already exist.");
+        if (registeredRealm.hasGroupLocal(group.getName())) {
+            throw new ConfigurationException("The group '" + group.getName() + "' at realm '" + group.getRealmId() + "' already exists.");
         }
         
         final GroupImpl newGroup = new GroupImpl(broker, registeredRealm, id, group.getName(), group.getManagers());
@@ -628,6 +628,10 @@ public class SecurityManagerImpl implements SecurityManager, BrokerPoolService {
         }
 
         final AbstractRealm registeredRealm = (AbstractRealm) findRealmForRealmId(account.getRealmId());
+        if (registeredRealm.hasAccountLocal(account.getName())) {
+            throw new ConfigurationException("The account '" + account.getName() + "' at realm '" + account.getRealmId() + "' already exists.");
+        }
+
         final AccountImpl newAccount = new AccountImpl(broker, registeredRealm, id, account);
 
         final Lock lock = accountLocks.getWriteLock(newAccount);
diff --git a/src/org/exist/security/management/AccountsManagement.java b/src/org/exist/security/management/AccountsManagement.java
index a940a4a00..b971af915 100644
--- a/src/org/exist/security/management/AccountsManagement.java
+++ b/src/org/exist/security/management/AccountsManagement.java
@@ -32,14 +32,17 @@ import org.exist.security.Account;
  */
 public interface AccountsManagement {
 	
-	public Account addAccount(Account account) throws PermissionDeniedException, EXistException, ConfigurationException;
+	Account addAccount(Account account) throws PermissionDeniedException, EXistException, ConfigurationException;
 	
-	public Account getAccount(String name);
+	Account getAccount(String name);
 
-	public boolean hasAccount(Account account);
-	public boolean hasAccount(String name);
+	boolean hasAccount(Account account);
+	boolean hasAccount(String name);
 
-	public boolean updateAccount(Account account) throws PermissionDeniedException, EXistException, ConfigurationException;
+	boolean hasAccountLocal(Account account);
+	boolean hasAccountLocal(String name);
+
+	boolean updateAccount(Account account) throws PermissionDeniedException, EXistException, ConfigurationException;
 	
-	public boolean deleteAccount(Account account) throws PermissionDeniedException, EXistException, ConfigurationException;
+	boolean deleteAccount(Account account) throws PermissionDeniedException, EXistException, ConfigurationException;
 }
\ No newline at end of file
diff --git a/src/org/exist/security/management/GroupsManagement.java b/src/org/exist/security/management/GroupsManagement.java
index 25ce7143e..a4409828a 100644
--- a/src/org/exist/security/management/GroupsManagement.java
+++ b/src/org/exist/security/management/GroupsManagement.java
@@ -33,15 +33,18 @@ import org.exist.storage.DBBroker;
  */
 public interface GroupsManagement {
 
-	public Group addGroup(DBBroker broker, Group group) throws PermissionDeniedException, EXistException, ConfigurationException;
+	Group addGroup(DBBroker broker, Group group) throws PermissionDeniedException, EXistException, ConfigurationException;
 	
-	public Group getGroup(String name);
+	Group getGroup(String name);
 
-	public boolean hasGroup(Group group);
-	public boolean hasGroup(String name);
+	boolean hasGroup(Group group);
+	boolean hasGroup(String name);
 
-	public boolean updateGroup(Group group) throws PermissionDeniedException, EXistException, ConfigurationException;
+	boolean hasGroupLocal(Group group);
+	boolean hasGroupLocal(String name);
+
+	boolean updateGroup(Group group) throws PermissionDeniedException, EXistException, ConfigurationException;
 	
-	public boolean deleteGroup(Group group) throws PermissionDeniedException, EXistException, ConfigurationException;
+	boolean deleteGroup(Group group) throws PermissionDeniedException, EXistException, ConfigurationException;
 
 }
\ No newline at end of file

```

**Comment by adamretter** [comment]
@simar0at Hmm this is quite a complex one. I would need to be able to reproduce this on demand. Is it possible to get secure remote access to either your LDAP or a Linux machine (which has network access to your LDAP)? Then I could do some debugging and testing...

**Comment by dizzzz** [comment]
any update?

**Comment by adamretter** [comment]
@simar0at Any updates on this please? If we don't hear from you, I think we should likely merge this PR as it improves the current situation IMHO.

**Comment by simar0at** [comment]
@adamretter you should do what you suggested above. Test it with an actual server. Nothing was changed so LDAP will probably still bombard the server with hundreds of unnecessary request in what seems to be something like an endless loop. To verify this I suggest you get yourself a free [UCS Server virtual machine](https://www.univention.de/download/download-ucs/). You have a little bit of setup to do but it's the fastest free production (AD) like LDAP solution I know.

**Pull request merged**
