### PR TITLE
Add test showing problem with dynamic context in range:index-keys-for-field

### PR DESCRIPTION
**Pull request by olvidalo**
demonstrates issue in #1226

### CODE REVIEW

**Comment by shabanovd** [comment]
hmm,  tests pass

**Comment by dizzzz** [comment]
Probably the invocation of the script need to be configured. I remember a file for this....

**Comment by olvidalo** [comment]
I just added the pending annotation because @joewiz did it in #1177 and I thought this must be common practise. Apparently it isn't :) Pending tests don't get executed at all but show up in the report as such. So this could be merged even before fixing the bug without breaking CI. Might be useful as this contains some passing tests for range:index-keys-for-field which hadn't been tested before.

But I can remove the %pending of course. Let me know..

**Comment by dizzzz** [comment]
I missed the %pending part :-)

**Pull request merged**
