### PR TITLE
do not set java location by "env.JAVA_HOME" property at yajsw config

### PR DESCRIPTION
**Pull request by shabanovd**
set local java location at yajsw config is wrong because it share with installer config and build fail if JAVA_HOME is not set

### CODE REVIEW

**Comment by dizzzz** [comment]
I overlooked this PR. @ljo what is your idea?

**Comment by ljo** [comment]
I do not get the motivation to change this. @shabanovd could you please elaborate on What this means: "set local java location at yajsw config is wrong because it share with installer config and build fail if JAVA_HOME is not set" The last part about JAVA_HOME I interpret as the intended behaviour.

**Comment by shabanovd** [comment]
@ljo your change force to have `JAVA_HOME` (build fail if it was not set) and also at build time it create `wrapper.conf` with java location of the computer (OS) where it was build.

**Comment by dizzzz** [comment]
@shabanovd that is not too bad is it? as long as in the installer/DMG no value is set? or do I overlook something?

**Comment by shabanovd** [comment]
@dizzzz guess, you did.
 - build fail;
 - that only place where `JAVA_HOME` required;
 - installer have java location of OS where it was build.

**Comment by ljo** [comment]
No. If you install and rebuild a wrapper you are really not talking about 1 percent. We need to keep both cases. Automated testing and installation will be completely hopeless without it. And if you are rebuilding why not simply provide your preferred values as requested? This is still the ant script we are talking about. If you are only installing from the installer your provided JAVA_HOME will be used.

**Comment by shabanovd** [comment]
- why I should rebuild after install?
 - if I do not set JAVA_HOME where installer will take it?
 - how installer will know where you put java location if config file have no `JAVA_HOME`?
 - where automated tests for yajsw?
 - installation always require manual setup or automated by manually prepared configurations files that copied during installation.

**Comment by dizzzz** [comment]
I am not (yet) convinced this is the correct way, as it removes the route te specify JAVA_HOME ?
(though there is a chance that the java executable use it)

**Comment by adamretter** [comment]
@dizzzz @shabanovd Is there not a compromise here. i.e.

1) detect if JAVA_HOME is set.
2) if not see if we find `java` on the path
3) if none of the above, fail and complain appropriately to the user.

**Pull request closed without merging**
