### PR TITLE
Fixes for FLWOR expressions

### LINKED ISSUE #384: Failure to recognize grouping variable
Problem: eXist fails to recognize the grouping variable in the following query, and returns this error:

    "Definition for grouping var character not found"

Query:

```xquery
declare variable $plays := (
  document {
   <play>
    <title>Hamlet</title>
    <characters>
      <character>Hamlet</character>       
      <character>Claudius</character>
      <character>Polonius</character>
      <character>Rosencrantz</character>
      <character>Guildenstern</character>
      <character>Francisco</character>
      <character>Reynaldo</character>     
    </characters>
   </play>
   },
   document {<play>
    <title>Rosenkrantz and Guildenstern are Dead</title>
    <characters>
      <character>Alfred</character>
      <character>Rosencrantz</character>
      <character>Guildenstern</character>
      <character>Hamlet</character>   
      <character>Claudius</character>     
    </characters>  
   </play>
   }
);

for $play in $plays/play
let $title := $play/title
for $character in $play/characters/character
group by $character
return
    <character name="{$character}">
     {
        $title ! <play>{ . }</play>
     }
    </character>
```

Expected result:

```xml
<character name="Hamlet">
  <play>
    <title>Hamlet</title>
  </play>
  <play>
    <title>Rosenkrantz and Guildenstern are Dead</title>
  </play>
</character>
<character name="Claudius">
  <play>
    <title>Hamlet</title>
  </play>
  <play>
    <title>Rosenkrantz and Guildenstern are Dead</title>
  </play>
</character>
<character name="Polonius">
  <play>
    <title>Hamlet</title>
  </play>
</character>
<character name="Rosencrantz">
  <play>
    <title>Hamlet</title>
  </play>
  <play>
    <title>Rosenkrantz and Guildenstern are Dead</title>
  </play>
</character>
<character name="Guildenstern">
  <play>
    <title>Hamlet</title>
  </play>
  <play>
    <title>Rosenkrantz and Guildenstern are Dead</title>
  </play>
</character>
<character name="Francisco">
  <play>
    <title>Hamlet</title>
  </play>
</character>
<character name="Reynaldo">
  <play>
    <title>Hamlet</title>
  </play>
</character>
<character name="Alfred">
  <play>
    <title>Rosenkrantz and Guildenstern are Dead</title>
  </play>
</character>
```

### PR DESCRIPTION
**Pull request by wolfgangmm**
This is a major update to FLWOR processing in eXist to align it with the 3.0/3.1 specification. The "for", "let", "where", "order by" and "group by" clauses are now implemented as separate classes (instead of being attached to a main "for" or "let"), and may thus appear in any place the spec allows. A FLWOR expression may have multiple "order by", "group by" or "where" clauses. The previous implementation was too restrictive, allowing those clauses only in specific positions.

The "group by" clause, which was added back in 2007 and has been updated a few times since then, was completely rewritten and does now also support collations. The "allowing empty" spec within a "for" is now respected.

Closes #384 and #739.

### CODE REVIEW

**Comment by joewiz** [comment]
This is huge! Many, many thanks, Wolfgang! Having just read the Group By section of the pre-release copy of Priscilla Walmsley's 2nd edition of _XQuery_ that she distributed at Balisage—which helped me finally understand `group by`—I plan to make use of this new functionality extensively.

**Comment by ljo** [comment]
Yes, looks good. Merging.

**Comment by jonathanrobie** [comment]
Excellent!  This is really important functionality.

**Comment by duncdrum** [comment]
any chance that these fixes will be backported to 2.2, since they apply to xQuery 3.0 and 3.1?

**Comment by dizzzz** [comment]
@duncdrum No, as I see it we'll not port it to 2.2 ; the team is focussing on 3.0 ....

**Pull request merged**
