### PR TITLE
[6.x.x] [fix] XQSuite assertXPath annotation: Support default element namespace

### PR DESCRIPTION
**Pull request by joewiz**
Backport of https://github.com/eXist-db/exist/pull/4799.

### CODE REVIEW

**Comment by joewiz** [comment]
A PR containing the required documentation is available at https://github.com/eXist-db/documentation/pull/902.

**Comment by line-o** [comment]
Judging from the title of this PR this should have been merged into `develop/6.x.x` no? @joewiz @adamretter

**Comment by joewiz** [comment]
Drat! Good catch. I based it on the correct branch locally, but I failed to select the target branch in GitHub... I will re-submit.

**Comment by adamretter** [comment]
Ah ha! Joe can you send a second PR for 6.x.x please?

**Pull request merged**
