### PR TITLE
Correct jmx option parsing

### PR DESCRIPTION
**Pull request by hungerburg**
Enable jmx and try to parse port ONLY when option matches at beginning of argument.

### CODE REVIEW

**Comment by adamretter** [comment]
@hungerburg awesome thanks :-)

Could you send PR's for the `develop-4.x.x` and `develop-5.0.0` as well please?

**Comment by adamretter** [comment]
@hungerburg did you mean to close those?

**Comment by hungerburg** [comment]
@adamretter I tested the patch here, works fine; Is it still available -- I did a git flow command that I do not understand

**Comment by joewiz** [comment]
@adamretter @dannes Is anyone still using Git Flow for eXist? I recall it being part of a README when we first switched to GitHub, struggled with it, stopped using it, and forgot about it until now. I see it is still mandated at https://github.com/eXist-db/exist/blob/develop/CONTRIBUTING.md. I don’t use it or see others using it. Am I mistaken, or shall we remove git flow from the contributing guidelines?

**Comment by adamretter** [comment]
@joewiz I can update the `CONTRIBUTING.md`. It is not necessary to use the git flow command, but basically the workflow is the same if you use it or not.

**Comment by dizzzz** [comment]
Myself I don't use the tool, but I do adhere to the fundamentals....

**Comment by duncdrum** [comment]
i d say put the git-flow question on the community call agenda so more folks can chime in. I think the cons outweigh the pros but it seems easier to discuss this there then in the comments of this PR

**Pull request merged**
