### PR TITLE
Adding a Lucene index attribute boosting feature

### PR DESCRIPTION
**Pull request by ljo**
Refactored and adapted to develop branch (2.3+)
No log flooding.

### CODE REVIEW

**Comment by dizzzz** [comment]
some documentation is required in the docs-app right?

**Comment by joewiz** [comment]
Wow, looks super!  Thanks for this, and in advance the additional docs!

**Comment by ljo** [comment]
Yes, docs on its way, and there will also be a tempting wiki article firstly.

**Comment by adamretter** [comment]
@ljo are there docs for this now that 3.0.RC1 is going out?

**Comment by ljo** [comment]
Yes, I have prepared a wiki article including examples, which can be easily adapted to fit docs app.

**Pull request merged**
