### PR TITLE
Improve %latest% in start.config

### PR DESCRIPTION
**Pull request by adamretter**
When running `client`/`jetty` from `org.exist.start.Main` eXist did not recognised the new log4j2 jar files as it's definition of `%latest%` in `org/exist/start/start.config` was too narrow.

### CODE REVIEW

**Comment by ljo** [comment]
@windauer I have seen a lot of these "in progress" labels being inserted at the same time the request comes in, so my conclusion is this automatically inserted and not that you are doing it? Can I pull this or are you actually looking?

**Comment by dizzzz** [comment]
if the 'in progress' has additional semantics, it is not explained nor discussed on exist-develop or exist-open ...

**Comment by ljo** [comment]
@dizzzz so you mean I should not pull it since the sematics we agreed on,  just to make it clear to others, is "I am doing the review thus it is in progress" or?

**Comment by dizzzz** [comment]
@ljo no, I think you can pull it in, the code looks good....

**Comment by ljo** [comment]
I still think this automatic labeling is not a good change. So if someone can explain and convince me why something automatically can be in progress I would be happier.

**Comment by windauer** [comment]
ehm, I'm a little bit confused.. now it say I removed the "in progress" label a minute ago, but I didn't do anything here. Joern and me tried to find a better view for Github issue or to connect it with Trello. Perhaps something wen't wrong there.. I will have a look.. sorry for the noise if it was me :)

**Comment by ljo** [comment]
@windauer Ok. Yes, this is new behaviour from latest week which should be changed then. ;)

**Comment by windauer** [comment]
I removed 3 of 4 webhooks from the eXist git repo. Should be fine again now

**Pull request merged**
