### PR TITLE
remove non lts oracle java versions

### LINKED ISSUE #2227: Disable Oracle Java10 build on travis
As it is now deprecated; should we focus on Java8/Java11 only?

image

### PR DESCRIPTION
**Pull request by duncdrum**
oracle java11 not yet supported by travis it seems 
close #2227

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz @duncdrum I really didn't want this change to happen :-(

**Comment by duncdrum** [comment]
@adamretter but the oracle 9/10 stuff no longer runs on travis, the only way we can keep testing would be to switch the a) ci provider, or b) rewrite our travis config, so we change and maintain base linux and java install ourselves. Are EOL oracle version worth the extra work?

**Comment by adamretter** [comment]
@duncdrum I don't think anything changed, it seems to me that it all ran on Travis just fine - https://travis-ci.com/eXist-db/exist/builds/87889264

**Comment by duncdrum** [comment]
@adamretter that was 9 days ago, here is 2 days ago https://travis-ci.com/eXist-db/exist/jobs/153207487

**Comment by adamretter** [comment]
@duncdrum Ahhhh okay. Sorry. Thank you.

**Pull request merged**
