### PR TITLE
[cicd] Build with Java16

### PR DESCRIPTION
**Pull request by dizzzz**
Lets check the build results;
Java15 is EOL and unstable for eXist-db; v16 is more logical to use.

### CODE REVIEW

**Review by duncdrum — COMMENTED** [review]
Ci changes are good, these failures we ll have to see

**Comment by duncdrum** [comment]
@dizzzz can you allow J16 to fail using [this syntax](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) for now, also lets build the javadocs so at least we know whats coming up (also allow fail). This would then be good to merge, imv.

**Comment by joewiz** [comment]
From today's Community Call notes:

> @duncdrum: suggest to pull-in java16 pr, as 15 is EOL. accept build issues (as Java15) and work on it for fixes

@duncdrum I assume this means you are ok merging this as is, without the syntax change that you suggested above and despite the CI failures? 

If so, could you please "approve" the PR?

**Comment by duncdrum** [comment]
@joewiz this is still a draft PR, as discussed I m happy to merge, once we allow the build to fail, which will also help our larger CI issues

**Comment by dizzzz** [comment]
todo: allow failing

**Comment by dizzzz** [comment]
@duncdrum I have no idea how to implement your suggestion, this is way beyond by current understanding. Please could you make the required changes in this PR ?

**Comment by duncdrum** [comment]
@dizzzz no worries i ll add the necessary config changes and cherry-pick your commits

**Comment by duncdrum** [comment]
@dizzzz this was superseded in the interim, if there is anything i overlooked please reopen

**Pull request closed without merging**
