### PR TITLE
(4.x.x) Adopt FastUtil primitive maps

### PR DESCRIPTION
**Pull request by adamretter**
Backport of https://github.com/eXist-db/exist/pull/2587

### CODE REVIEW

**Comment by duncdrum** [comment]
looks like this one doesn't like `4.x.x`

**Comment by dizzzz** [comment]
no, stil some tests are failing....

```
test-local:
     [echo] ------------------------------------------
     [echo] Running tests on a local database instance
     [echo] ------------------------------------------
    [junit] Running org.exist.backup.BackupRestoreSecurityPrincipalsTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.846 sec
BUILD FAILED
/home/travis/build/eXist-db/exist/build/scripts/junit.xml:152: Test org.exist.backup.BackupRestoreSecurityPrincipalsTest failed
```

**Comment by adamretter** [comment]
@dizzzz okay, let's see now...

**Comment by dizzzz** [comment]
Again in appveyor we have a test issue in linux; I think it is a very specific issue as travis builds ok

```
 (98 %)Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer2259792442326420356Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer2938639807920235244
4525    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer136452465084702061
4526    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer3906729929923864893
4527    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer2356115753357248063
4528    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer876296779410014894
4529    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer8916850508876926742
4530    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer7328365469925479850
4531    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer6038248500891757790
4532    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer7629923294730408972
4533    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer1730422699939171459
4534    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer4020612556606518054
4535    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer3247419837126877087
4536    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer5102135487459359652
4537    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer7798897057199035695
4538    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer5550219954990708810
4539    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer7516753169054974413
4540    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer3167812029371450052
4541    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer1457892070714135126
4542    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer2548465578208766526
4543    [junit] Tests run: 49, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 239.14 sec
4544
4545BUILD FAILED
4546/home/appveyor/projects/exist/build/scripts/junit.xml:317: Test org.exist.storage.AllStorageTests failed
4547
4548Total time: 28 minutes 24 seconds
4549
```

**Comment by adamretter** [comment]
@dizzzz the failures on Ubuntu AppVeyor are consistent across all 3 branches, so it seems likely that there could be a real issue. AppVeyor uses Ubuntu 18.04, whilst Travis used 16.04. I will see if I can reproduce on an 18.04 VM here...

**Comment by duncdrum** [comment]
*yay* for expanding our testsuite to cover multiple linux releases

**Comment by adamretter** [comment]
@dizzzz @duncdrum I cannot reproduce the issue on a Ubuntu 18.04 VM here :-(

**Comment by dizzzz** [comment]
@duncdrum  "Jay" ... well it worries me extremely that linux distros can be so different.

**Comment by duncdrum** [comment]
@dizzzz well better we see it here than in production, no?

**Pull request merged**
