### PR TITLE
Range index returns invalid results

### PR DESCRIPTION
**Pull request by wolfgangmm**
Several users reported wrong nodes being returned as the result of an XQuery predicate using a range index. While the result looked ok on first sight, serializing it would show seemingly random nodes from the same document. Unfortunately the issue was not easy to reproduce. Several people tried to write tests, including @joewiz, @windauer and myself, but could not trigger the bug in a simple test scenario. 

I finally managed to download a complete database dump from one production server where the bug just became manifest and managed to track it down to deleted lucene documents being returned by queries.

The deleted lucene documents were picked up by a filter used by the range index to optimize queries on a single context node. As a consequence, the range index returned pointers to invalid (deleted) nodes into the XQuery result. It randomly chose one of the found lucene entries, which explains why the bug was unpredictable.

The optimization achieved by the filter appeared to be rather minor in my tests. I thus would vote for dropping this filter altogether as it apparently is the cause of the issues.

### CODE REVIEW

**Comment by joewiz** [comment]
From https://ci.appveyor.com/project/AdamRetter/exist/build/develop-354:

```
3272    [junit] Using temporary storage location: C:\Users\appveyor\AppData\Local\Temp\1\org.exist.test.ExistEmbeddedServer4141105031809044933
3273    [junit] Running xquery.arrays.ArrayTests
3274    [junit] Tests run: 142, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 1.984 sec
3275
3276BUILD FAILED
3277C:\projects\exist\build\scripts\junit.xml:153: Test xquery.arrays.ArrayTests failed
3278
3279Total time: 7 minutes 51 seconds
3280Command exited with code 1
```

**Comment by dizzzz** [comment]
Interesting to see that the non-windows build succeeds

**Comment by duncdrum** [comment]
I think we should revisit #194 in light of this PR to see if it still applies.

**Comment by dizzzz** [comment]
I am really waiting for this fix.....

**Comment by wolfgangmm** [comment]
@dizzzz If I can get the windows build fixed ...

**Comment by dizzzz** [comment]
I understand. is it clear which test fails? or..... if there is only one...

**Comment by wolfgangmm** [comment]
At the moment I still have 1 failure and 1 error. Both are very weird.

**Comment by dizzzz** [comment]
I merged-in the recent changes of 'develop', rerunning tests..

**Comment by dizzzz** [comment]
I did not see the problems anymore after this fix !

**Pull request merged**
