### PR TITLE
[wip] [feat] distinct analyzers for indexing and querying with Lucene

### PR DESCRIPTION
**Pull request by line-o**
### Description:

Original from @sten1ee :
In our usage of eXist, we're utilising a 'State of the art' LuceneAnalyzer for Sanskrit language developed by our colleagues from BDRC It has several modes of operation, but the one that we use - 'lenient mode' - requires one Analyzer to be used during the indexing phase, but then a different (or a differently configured) one to be used during querying.
Currently, eXist does not provide support for this use case, but this PR is aiming to achieve this feat.

- [x] rebased on current develop
- [x] tests for full-text indices 
- [x] tests for fields 
- [x] tests for new Lucene fields
- [ ] documentation

### Reference:

based on #2908, #2991 opened by @sten1ee 

### Type of tests:

testsuite in XML

### CODE REVIEW

**Comment by sten1ee** [comment]
@line-o : how's it going with the additional tests and the documentation of the feature?

**Comment by line-o** [comment]
@sten1ee the tests are part of this PR - documentation is still TODO (see the checkboxes in the description)

**Comment by line-o** [comment]
@sten1ee would you be able to describe your use-case in the referenced documentation ticket. A link to the indexer and a code example would be great, too.

**Comment by sten1ee** [comment]
There's some documentation, (who volunteers to review it?):
https://github.com/eXist-db/documentation/pull/445

**Comment by sten1ee** [comment]
The corresponding [docs PR#449](https://github.com/eXist-db/documentation/pull/445) was approved and merged.
So perhaps it is about time to approve and merge this too, @adamretter ? :)

**Comment by adamretter** [comment]
@sten1ee @line-o I think this one has to be reviewed by @wolfgangmm instead of me, as how the Lucene stuff works in eXist-db is his domain.

**Pull request merged**
