### PR TITLE
Cleaned up the XML:DB Remote API implementation

### PR DESCRIPTION
**Pull request by adamretter**
General code audit and cleanup. Fixed several small bugs along the way that were the result of previous copy-pasta mistakes or bad code style.

### CODE REVIEW

**Comment by dizzzz** [comment]
The PR looks pretty straightforward to me, ok for me to pull in.

2 questions for adam (not necessarily a request for a change!)
- on a few locations you write `final List params = new ArrayList()` as where `List<Object>` was used first; is that actually a better choice? I remember this solved some checkstyle/pdm/findbugs reports
- one one location an input stream is copied to an output stream (buffer of 64kb?); for readability I tend to use `IOUtils.copy()` for this.  This additional dependancy is probably not too bad.

**Comment by adamretter** [comment]
@dizzzz Ah right, yes, good catch! It should be `List<Object>` and not the parameterised `List`. Let me just fix that.

**Comment by adamretter** [comment]
@dizzzz Okay I have done that and rebased. It is ready to go...

**Comment by dizzzz** [comment]
Thnx ; I'd ike to discuss with @wolfgangmm @shabanovd  @ljo to have a look as wel; e.g. for other PRs @wolfgangmm is testing the PR ; same for this one?

**Comment by wolfgangmm** [comment]
Tested this for a day without finding an issue.

**Comment by adamretter** [comment]
Yay :-)

**Comment by dizzzz** [comment]
woohoo!

**Comment by ljo** [comment]
:)

**Pull request merged**
