### PR TITLE
Don't output extraneous whitespace in JSON unless indent=yes is set

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by dizzzz** [comment]
@adamretter I think you forgot to commit a test file..... 

```
/home/travis/build/eXist-db/exist/build/scripts/junit.xml:124: Test org.exist.util.serializer.json.JSONObjectTest failed 
```

**Comment by dizzzz** [comment]
When I think of 'non-indenting' output I also think of not writing newlines..... I do not see any changes regarding newlines, so this is unchanged ?

**Comment by dizzzz** [comment]
@adamretter ???

**Comment by adamretter** [comment]
@dizzzz Sorry about that, just added the test and rebased. Hopefully all is well now. As far as I am aware, there are no changes to EOL as the JSON serializer doesn't add EOL anyway.

**Comment by dizzzz** [comment]
Again a fail?

**Comment by joewiz** [comment]
The failure:

> [junit] Running xquery.arrays.ArrayTests
> [junit] XQuery Test suite: http://exist-db.org/test/arrays
> ...
> [junit] 	FAILED: serialize-old-json-compat. assertEquals failed.. Expected: '{ "status" : true }' Actual: '{"status":true}'

... from https://travis-ci.org/eXist-db/exist/builds/183272052#L3040

**Comment by adamretter** [comment]
@dizzzz @joewiz That should be fixed now :-)

**Comment by dizzzz** [comment]
I am happy ... @ljo too?

**Comment by windauer** [comment]
@dizzzz any reason to wait for @ljo? Tests are running green, code looks good and @adamretter even extended the test case. I would merge this if you don't have any obligations.

**Comment by dizzzz** [comment]
In a chat we had @ljo expressed some concerns. But yes as all is green... Lets pull it in :)

**Pull request merged**
