### PR TITLE
Fix use of deprecated functions to restore dashboard etc.

### PR DESCRIPTION
**Pull request by wolfgangmm**
Replace xmldb:is-admin-user with sm:is-dba to restore packaged apps for develop and 5.0.

### CODE REVIEW

**Comment by adamretter** [comment]
As this is part of the core, coukd you add some XQuery test please, so that we know when this breaks in future?

**Comment by joewiz** [comment]
I have tested this PR and confirmed that it allows apps that otherwise couldn't start (such as dashboard, monex, and packagemanager) to work. 

I added the "needs 4.x.x backport" just as a suggestion. It isn't strictly necessary, but it would be nice to keep the source aligned where possible across branches/versions.

**Comment by wolfgangmm** [comment]
Ok, added a junit test to cover this module.

**Comment by dizzzz** [comment]
@adamretter ?

**Pull request merged**
