### PR TITLE
Move monex' jar files into main repository.

### PR DESCRIPTION
**Pull request by dizzzz**
fix for #1721 ; need to update Monex too ! see https://github.com/eXist-db/monex/pull/50

### CODE REVIEW

**Comment by adamretter** [comment]
Do you also need to add config files to `$EXIST_HOME/tools/jetty/etc/` and update `tools/jetty/etc/standard.enabled-jetty-configs`?

**Comment by dizzzz** [comment]
not sure.... ? I could use some help here probably.

**Comment by dizzzz** [comment]
answering: you are probably right, but as the original JAR files are loaded via the XAR... not sure how/if any changes are needed?

**Comment by adamretter** [comment]
@dizzzz I think this should be okay as is

**Pull request merged**
