### PR TITLE
[5.x.x] Fixes to fn:replace, fn:tokenize, and fn:analyze-string

### PR DESCRIPTION
**Pull request by adamretter**
Backport of https://github.com/eXist-db/exist/pull/4864

### CODE REVIEW

**Review by reinhapa — APPROVED** [review]

**Review by dizzzz — APPROVED** [review]

**Comment by line-o** [comment]
I just want to understand why this is OK where other, similar changes were not.

**Comment by line-o** [comment]
Has this been tested with the bundled applications?

**Comment by adamretter** [comment]
> Changes like this were considered breaking in the past.
> If in any application running on exist (a future version of 5) calls fn:matches((1,2), "\d") will now throw an error.

Good point!

Technically this is not an API change though (which would warrant a major version bump), as the API has stayed the same. It is however a behaviour change as you describe.

Would it be acceptable if I removed the commit that introduces the FORX0003 error from this PR? The other commits should not be a problem for a hotfix version

**Comment by line-o** [comment]
`fn:matches("a", "\d?")` will also throw (FORX0003) but that is a different error than the one that is thrown when a sequence is used as the first argument (XPTY0004) no?

**Comment by reinhapa** [comment]
> `fn:matches("a", "\d?")` will also throw (FORX0003) but that is a different error than the one that is thrown when a sequence is used as the first argument (XPTY0004) no?

@line-o is this blocking the merge?

**Comment by line-o** [comment]
I would welcome this change and make it a precedent for future changes. Allow patch releases that bring the xquery engine to spec compliance. Or we decide that this is a won't fix as it is changing existent behaviour that is fixed _only_ in a major release.

**Comment by line-o** [comment]
Since the back port for v6 of this was already merged to develop-6.x.x we can already consider this ti be a precedent.
But we should make it clear in at least the release notes what did change and how that might affect existing queries and applications that rely on the current behavior.

**Comment by adamretter** [comment]
> we can already consider this ti be a precedent.

I am not comfortable with that.

My approach here was to address the concerns of @line-o and remove the things that he felt were breaking changes. The other PR to 6.x.x got merged before I could address @line-o's request and so it was outside of my control.

**Comment by reinhapa** [comment]
> > we can already consider this ti be a precedent.
> 
> I am not comfortable with that.
> 
> My approach here was to address the concerns of @line-o and remove the things that he felt were breaking changes. The other PR to 6.x.x got merged before I could address @line-o's request and so it was outside of my control.

Seems I was to fast here, @adamretter if you want you could prepare a PR for a partial roll back for those parts you are not comfortable with or would this to complicated now?

**Comment by line-o** [comment]
@adamretter This PR is marked as ready-for-review and two approvals. If you think it should not be merged as is please, it would be good to communicate that clearly. Request changes, convert it to a draft PR or add the `ON HOLD` label.

**Comment by adamretter** [comment]
@dizzzz @reinhapa I believe this is now ready to merge please

**Comment by line-o** [comment]
@adamretter the last commit is 6 months old. Is it really this PR that you think is ready to be merged?

**Comment by line-o** [comment]
There are also failing tests. I would at least want to these those succeed _before_ this PR is merged @dizzzz @reinhapa

**Comment by adamretter** [comment]
> the last commit is 6 months old. Is it really this PR that you think is ready to be merged?

@line-o Yes, it is this PR.

> There are also failing tests. I would at least want to these those succeed before this PR is merged @dizzzz @reinhapa

@line-o If you check, you will see that the failing tests are unrelated to this PR.

**Comment by line-o** [comment]
@adamretter could you please rebase so that the tests can be run.

**Comment by adamretter** [comment]
@line-o Done.

**Comment by adamretter** [comment]
@dizzzz @reinhapa this one has been languishing since Sept 2nd. Could we get it merged please?

**Review by reinhapa — APPROVED** [review]

**Comment by reinhapa** [comment]
@adamretter could you rebase that in order to see if the macOS tests will pass?

**Comment by adamretter** [comment]
@reinhapa Okay, I have rebased. Let's see what happens in CI...

**Comment by adamretter** [comment]
@reinhapa Yes, the rebase seems to have fixed macOS

**Comment by dizzzz** [comment]
@adamretter I need to check the previously stated concerns re: compatibility? I remember that this is the reason why it was not pulled in yet?

**Comment by adamretter** [comment]
@dizzzz I believe that was addressed and done here - https://github.com/eXist-db/exist/pull/4866#issuecomment-2324178928

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
