### PR TITLE
put db settings in build.properties

### PR DESCRIPTION
**Pull request by wshager**
I put the database settings for `conf.xml` (in some locations) in the `build.properties file`. This is probably a good idea, and would've saved me the time to find out how this works.

### CODE REVIEW

**Comment by dizzzz** [comment]
i'd like to propose to call these `config.dataDir` and `config.cacheSize`;

**Comment by wshager** [comment]
@dizzzz sounds good.

**Comment by wshager** [comment]
@dizzzz like dizzz?

**Comment by adamretter** [comment]
@wshager Looks good to me, but if you add `dataDir` you should also add `journalDir` as by default they both point to `webapp/WEB-INF/data`. See `//recovery/@journal-dir` in `conf.xml.tmpl`.

Likewise, with `cacheSize` you will probably also need collection cache size, as the later is allocated from the former. See `//db-connection/@collectionCache`.

**Comment by adamretter** [comment]
@wshager Would you be able to make the requested changes before Sept 25th Sept (which is our next release date)?

**Comment by wshager** [comment]
@adamretter I simply corrected the parameters that were already present, but you're asking me to add new ones. However, I'm not entirely sure on the nomenclature, so perhaps this is better left to someone who is.

**Comment by adamretter** [comment]
Superseded by https://github.com/eXist-db/exist/pull/1535

**Pull request closed without merging**
