### PR TITLE
[bugfix] Fix JMX interface

### PR DESCRIPTION
**Pull request by wolfgangmm**
After change to mxbean (in 5edf64625aa0df4f825be70630cfaf7444166cd4), information on running queries, query history, jobs, locks etc. was no longer provided. This not only affected eXist's JMXServlet but also jconsole and other JMX clients.

### CODE REVIEW

**Comment by dizzzz** [comment]
Is it possible to test this automagically?

**Comment by wolfgangmm** [comment]
Thought about it, but it would be difficult to write an automated test as useful information is only provided if there's a certain load on the server which would need to be triggered concurrently.

**Comment by adamretter** [comment]
I am not quite clear why all these changes were required. Exporting the existing data via Tabular Data worked just fine. Is it rather that you also fixed the issue and then enhanced the output by using Java Beans instead of TabularData?

**Comment by wolfgangmm** [comment]
It looks like directly returning TabularData is not possible using mxbeans. Instead of the data, you only got the type information. Anyway, using Java Beans results in more readable code, so there's a benefit in the end.

**Pull request merged**
