### PR TITLE
Add support for XQuery 3.0 `declare context item`

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1567

### CODE REVIEW

**Comment by adamretter** [comment]
Please ignore the codacy report, most of that is caused from Antlr code generation.

**Comment by joewiz** [comment]
Thanks so much, Adam! 

In my testing the following query, when saved as `/db/test.xq` and executed at <http://localhost:8080/exist/rest/db/test.xq>, works the first time but fails in subsequent runs:

```xquery
xquery version "3.0";

declare context item := 3; 

<x>{. + 4}</x>
```

The initial run returns the expected result, `<x>7</x>`, but returns the following error on subsequent runs:

```xml
<exception>
    <path>/db/test.xq</path>
    <message>err:XPDY0002 Undefined context sequence for 'self::node()' [source:
        /db/test.xq]</message>
</exception>
```

**Comment by adamretter** [comment]
@joewiz, oops some testing code I left it. I think that "*repeatable*" issue should now be fixed...

**Comment by joewiz** [comment]
@adamretter That did the trick. Thank you!

**Comment by joewiz** [comment]
@dizzzz Thanks!

**Pull request merged**
