### PR TITLE
SequenceType do not have ("empty" "(" ")")

### LINKED ISSUE #1155: Typeswitch allows invalid checks
I would expect the following query to fail, because `empty()` is not a type declaration:

``` xquery
xquery version "3.1";

let $item := ()
return
    typeswitch ($item)
    case empty() return
        'empty!?'
    default return
        'default'
```

eXist allows this through and in fact returns `empty!?`. This is using a current build of the develop branch.

### PR DESCRIPTION
**Pull request by shabanovd**
### Description:
SequenceType do not have ("empty" "(" ")")

### Reference:
fix #1177 
close #1155

### CODE REVIEW

**Comment by dizzzz** [comment]
```
BUILD FAILED
/home/travis/build/eXist-db/exist/build/scripts/junit.xml:124: Test org.exist.xquery.AllXqueryTests failed
```

**Comment by shabanovd** [comment]
@dizzzz fixed

**Comment by wolfgangmm** [comment]
A quick search reveals this will require small updates to other apps, in particular the demo.

**Comment by joewiz** [comment]
I could do the demo updates - just replace empty with empty-sequence, right? Any other apps you spotted? I could also search...

**Comment by dizzzz** [comment]
hint: https://github.com/search?q=org%3AeXist-db+empty+extension%3Axq

**Comment by joewiz** [comment]
Thanks, Dannes! Of those 7, this is the only one that needs to be fixed:

https://github.com/eXist-db/tamboti/blob/cdbb8f5c6269cf386b9a80883a2e88c8bd5951ef/modules/edit/edit.xq#L48

This ability to search across the organization is another argument in favor of centralizing core apps like monex, eXide, and now markdown in the eXist repo ;)  

It's also a good argument for building linting - and a "strict" mode that flags deprecated or legacy/compatibility usage.

**Comment by joewiz** [comment]
Ok, Dannes, I made the change to Tamboti. I also did a sweep through these other users/orgs and confirmed there were no other uses of empty() as a sequence type:

* eXist-db: https://github.com/search?utf8=%E2%9C%93&q=org%3AeXist-db+empty+extension%3Axq&type=Code&ref=searchresults
* wolfgangmm: https://github.com/search?utf8=%E2%9C%93&q=user%3Awolfgangmm+empty+extension%3Axq&type=Code&ref=searchresults
* dizzzz: https://github.com/search?utf8=%E2%9C%93&q=user%3Adizzzz+empty+extension%3Axq&type=Code&ref=searchresults
* ljo: https://github.com/search?utf8=%E2%9C%93&q=user%3Aljo+empty+extension%3Axq&type=Code&ref=searchresults
* shabanovd: https://github.com/search?utf8=%E2%9C%93&q=user%3Ashabanovd+empty+extension%3Axq&type=Code&ref=searchresults
* adamretter: https://github.com/search?utf8=%E2%9C%93&q=user%3Aadamretter+empty+extension%3Axq&type=Code&ref=searchresults
* HistoryAtState: https://github.com/search?utf8=%E2%9C%93&q=org%3AHistoryAtState+empty+extension%3Axq&type=Code&ref=searchresults
* joewiz: https://github.com/search?utf8=%E2%9C%93&q=user%3Ajoewiz+empty+extension%3Axq&type=Code&ref=searchresults

I did a broader search - across all of github - for any use of the phrase "as empty" and only found some tamboti forks. The search:
* https://github.com/search?utf8=%E2%9C%93&q=%22as+empty%22+exist+extension%3Axq&type=Code&ref=searchresults
The hits:
* https://github.com/exc-asia-and-europe/tamboti/blob/dd57e4e2aa87efc89c19556ed9d4e6d3e18a2a19/modules/administration/recursive-apply-ace.xq
* https://github.com/exc-asia-and-europe/tamboti-1.1.2-patched/blob/e4a99994ef7b15148f27d7e4fdb4e053dfc0ee6b/modules/administration/recursive-apply-ace.xq

Another search for the phrase "instance of empty" found one hit. The search:
* https://github.com/search?utf8=%E2%9C%93&q=%22instance+of+empty%22+exist+extension%3Axq&type=Code&ref=searchresults
The hit:
* https://github.com/grantmacken/example.com/blob/58e8ad71004e124d5c9bf40f7b22a26c8627b7e4/modules/lib/test-runner.xq

I'll let Grant know about the fact about this bugfix.

**Comment by joewiz** [comment]
While I wouldn't claim my searches were comprehensive, it looks to me like there were very few cases of this usage - and this makes sense, since the spec has been clear that `empty-sequence()` is the way to test if a sequence is empty since 1.0.  My guess is that any uses of this were purely accidental - because they happened to work, rather than because the author intended to use this. 

(Unfortunately, gitlab [doesn't offer global code search](https://gitlab.com/gitlab-org/gitlab-ce/issues/14597), so I couldn't quickly do a sweep of http://gitlab.exist-db.org. It would have to be done project by project.)

**Comment by shabanovd** [comment]
@dizzzz good to merge?

**Comment by adamretter** [comment]
@shabanovd I think this could be classed as a breaking API change? It would certainly break some peoples XQueries as I understand. As such that would mean we have to keep it for eXist-4.0.

**Comment by joewiz** [comment]
I wondered about that too. But from an XQuery perspective, it is a bug fix. No one ever should have used `empty()` as a sequence type check, e.g., `case empty()` in a typeswitch expression or `instance of empty()`. The spec has been clear about this since 1.0. I'm not sure how this squares with the notion of "API changes" though.

**Comment by dizzzz** [comment]
From a functional perspective OK to land into 4.0 ;

Please @ljo could you review as you have antlr experience
@shabanovd the PR needs to be reworked :-( there is a merge conflict

**Comment by dizzzz** [comment]
Thnx

**Pull request closed without merging**
