### PR TITLE
Eliminate SequencedLongHashMap custom code

### PR DESCRIPTION
**Pull request by adamretter**
Removes another custom untested/unproven HashMap implementation in favour of a library version.

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]

**Comment by duncdrum** [comment]
@adamretter  can you remove the unused imports, i m happy to follow @dizzzz  but a partial PR like this, that includes a new warning about infinite loops, really needs a bit of prose to help the review along.

**Review by line-o — CHANGES_REQUESTED** [review]
Please address the Codacy warning

**Comment by line-o** [comment]
I also second that more explanation and or justification for this change would be highly appreciated.

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
The reported q issues are not true issues to this pull request; IMO this PR is good to go.

**Pull request merged**
