### PR TITLE
Fix test resource leaks introduced in https://github.com/eXist-db/exist/pull/5276

### PR DESCRIPTION
**Pull request by adamretter**
Fixes the resource leaks that were introduced in https://github.com/eXist-db/exist/pull/5276

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]

**Review by dizzzz — CHANGES_REQUESTED** [review]
Surefire issues.... MVND related?

[exist-core] [INFO] Running org.exist.storage.RecoverXmlTest
Error: core] [ERROR] [SUREFIRE] std/in stream corrupted

**Comment by adamretter** [comment]
> Surefire issues.... MVND related? --> isolated to windows tests
>
> [exist-core] [INFO] Running org.exist.storage.RecoverXmlTest
> Error: core] [ERROR] [SUREFIRE] std/in stream corrupted

@dizzzz I have appended some commits which I think now address the (unrelated to this PR) Windows CI issues.

**Review by dizzzz — APPROVED** [review]
Nice!

**Review by dizzzz — APPROVED** [review]

**Review by reinhapa — APPROVED** [review]
The only question I got is if only activating flight recorder using `-XX:StartFlightRecording` would have the same bad impact or if that is caused by the additonal parameters...

**Comment by adamretter** [comment]
> The only question I got is if only activating flight recorder using -XX:StartFlightRecording would have the same bad impact or if that is caused by the additonal parameters...

@reinhapa I am afraid I don't know the answer to that. Perhaps you would like to experiment with that in a follow-up PR? I would suggest running whatever experiments you have multiple times in the Windows CI, as it can be fickle ;-)

**Pull request merged**
