### PR TITLE
Feature/improve sortindex

### PR DESCRIPTION
**Pull request by dizzzz**
Improve readability etc

### CODE REVIEW

**Comment by dizzzz** [comment]
anyone?

**Comment by adamretter** [comment]
@dizzzz I don't see anything apart from code reformatting. Is that correct?

**Comment by adamretter** [comment]
@ljo The tests seem to be failing in Travis on this branch, i.e. `org.exist.dom.persistent.NodeTest`.

**Comment by dizzzz** [comment]
Added finals, wrapped exceptions, reformatting 
No rocker science, but it made the code more compact hence more readable

**Pull request merged**
