### PR TITLE
Block startup for Java 12-15 to protect from data corruption

### PR DESCRIPTION
**Pull request by dizzzz**
Add warning and delay to indicate that openJDK12 and newer should not be used with eXist-db, for now.

Example output:
```
*****************************************************
eXist-db should only be started with Java8 or Java11!
OpenJDK versions 12 and newer contain at this moment a
severe bug in the JIT compiler that will cause data loss.
The problem has been reported and will be addressed in
future versions of the OpenJDK.
Detected version is 15.
*****************************************************
```

### CODE REVIEW

**Comment by joewiz** [comment]
Great idea, Dannes! How about this version, with minor edits:

> Warning: eXist-db should only be used with Java 8 or 11! OpenJDK versions 12 and higher currently suffer from a critical bug in the JIT compiler that will cause data loss in eXist-db. The problem has been reported to the OpenJDK community. 
> 
> For more information, see:
>
> * https://bugs.openjdk.java.net/browse/JDK-8253191
> * https://github.com/eXist-db/exist/issues/3375
>
> The detected version of Java on your system is " + jreVersion + ". eXist-db will continue its startup sequence after a short delay, but until this OpenJDK bug is resolved, we urge you to switch to Java 8 or 11.

**Review by joewiz — APPROVED** [review]

**Comment by dizzzz** [comment]
thnx, good to have native speakers onboard :-)

**Comment by dizzzz** [comment]
updated to

image

**Comment by dizzzz** [comment]
I decided not to abort the startup of the database, although there are probably good arguments to do so.

**Comment by adamretter** [comment]
Couple of thoughts:

```
eXist-db should only be started with Java8 or Java11!
```

should read something like:
```
eXist-db should only be used with Java versions 8 through 11!
```

As Java 9, and 10 are also OK.

---

> I decided not to abort the startup of the database, although there are probably good arguments to do so.

You probably should do so, as otherwise corruption is inevitable. The worst scenario would be someone who upgrades to a newer eXist-db/Java and corrupts their otherwise good database files.
...Also if you can return an appropriate exit code if possible that would be great.

**Review by adamretter — COMMENTED** [review]
I think you might need to place this code into some sort of common place, and call it from there.

Unfortunately there are multiple ways that eXist-db can be started, and several of them don't involve going via this start/Main class.

**Comment by dizzzz** [comment]
I know that exist can be started from may ways, this part is the most common one I guess. I'd like to see that ppl use LTS versions only, java9/10 are really EOL for ages right now. A little push does not hurt.

**Comment by dizzzz** [comment]
with a hard stop, I do agree that java9/10 should not be blocked

**Comment by dizzzz** [comment]
@adamretter what locations would you indicate as 'entry' for starting eXist-db ? I think that only the common ones would be sufficient no?

**Comment by dizzzz** [comment]
new attempt, now with not starting eXist-db

image

**Comment by dizzzz** [comment]
for me, now it stops as it was intended as a simple change.

**Comment by dizzzz** [comment]
Anyone ! @wolfgangmm @adamretter @joewiz  @ljo ?

**Comment by dizzzz** [comment]
mac startup: via org.exist.start.Main:
image

**Comment by dizzzz** [comment]
Deamon code via main.runEx():
image

**Comment by dizzzz** [comment]
I updated the PR in such a way that both routes mentioned above + normal scripts will touch the OpenJDK version check.

**Comment by adamretter** [comment]
@dizzzz As requested on the call, I took a look. So there are a couple of places where I think this code also needs to be called:

1. `InteractiveClient#main` - as the db can be started in embedded mode there. The warning/error should probably only be shown when launching in embedded mode, as the JDK issue doesn't effect the remote client.
2. `JettyStart#run(String[] args, Observer)` - this can also launch the db in embedded mode. It is used for tests, the exist-db-xqts-runner and various other apps which embed eXist-db.
3. ExistEmbeddedServer and ExistXmldbEmbeddedServer - (same reasons as (2)).
4. AbstractXMLDBTask
5. ExportMain and ExportGUI - as these can start the database in embedded mode.

It might also be worth doing some testing with the launcher. As I am not sure if it will show the error properly when your warning stops eXist-db from starting. If that is the case you would need to integrate your warning into LauncherWrapper/Launcher main but show it in a dialog message.

**Comment by joewiz** [comment]
Correct me if I'm wrong, @dizzzz, but as discussed on today's Community Call, Dannes will revise this to check java is either (a) between 8 and 11, OR (b) 16+. And will remove exception in favor of just logging the warning. JW and PR think this is reasonable and will be an improvement, even if the warning isn't yet shown in all scenarios.

**Comment by adamretter** [comment]
> And will remove exception in favor of just logging the warning.

IMHO we should keep the exception. I have seen that few users often check the logs lately, and will likely ignore warnings. This bug leads to certain database corruption and so we should try and help users not loose data here.

**Comment by dizzzz** [comment]
I agree with @adamretter but as the PR is hanging for 7 months , I really 'd like to make a small step as I am very very concerned on the instability.

@wolfgangmm  offered to update the PR to make sure more startup scenarios would be covered.

**Review by dizzzz — COMMENTED** [review]
lgtm

**Comment by adamretter** [comment]
I pushed some commits to this branch. I think it should be in good shape now

**Review by wolfgangmm — APPROVED** [review]
Looks good to me :-)

**Pull request merged**
