### PR TITLE
[bugfix] corrects version number on missed POMs

### PR DESCRIPTION
**Pull request by reinhapa**
### Description:
Fixes the version numbers in missed POM files after the last release.

### CODE REVIEW

**Comment by line-o** [comment]
Thanks for updating the two poms ( there is an open issue for that #4694 ).

I would like to point out that rather than having to fix it manually each time we release exist I would like to see a change that updates the maven process that updates those two poms like all the other ones.

**Review by line-o — APPROVED** [review]
This is still a helpful hot fix for us to continue working on the develop branch.
We still need to update the maven release configuration to do this automatically.

**Review by dizzzz — APPROVED** [review]

**Review by line-o — CHANGES_REQUESTED** [review]
These two files are built artefacts and should be removed and ignored from version control.

**Review by line-o — APPROVED** [review]
I just realized, that this is not about the dependency-reduced-poms.
We still need to find out how to include the real POMs into the maven release process.

**Pull request merged**
