### PR TITLE
Cleanup and refactoring of REST Server

### PR DESCRIPTION
**Pull request by adamretter**
- Much cleanup and removal of duplicated code.
- Easier to read code.
- Fixed several black-hole bugs.
- Made parameter handling consistent between http methods.
- Made error handling in the REST interface consistent and correct.

### CODE REVIEW

**Comment by dizzzz** [comment]
Looks good.....

**Comment by adamretter** [comment]
@dizzzz Does that mean you will merge it?

**Comment by ljo** [comment]
Looks good, but I have not had the time to test it yet.

**Comment by dizzzz** [comment]
@adamretter we are a bit slow with pulling in PRs, since changes in 'essential' or 'core' areas need to be verifyied thoroughly (enough). I certainly do NOT want to slow down development, input from fellow devs like "looks good to me" (review) certainly helps to know who has looked into a PR.

I feel though that we need some talks -skype/hangout/...- to align who/how/when/what is pulled in, what is the criterium.

I fear that running the unit-tests is an essential step but not sufficient. But... what is then sufficient?

**Comment by adamretter** [comment]
@dizzzz Okay. I would like to get an idea if the next version is 2.3 or 3.0, certainly I have another 6 potential pull-requests stacked up on top of the ones I have sent. Some of them would be more suitable for a 3.0 as they are the removal of deprecated features. My personal feeling is the next version should be a 3.0, due to several things, but the major non-backwards change is the switch to Java 8.

Just let me know when you want to Skype?

Regards the unit tests, if you can't trust our test-suite then we need more tests!

**Comment by ljo** [comment]
Testing in a live system with additional extensions and xars enabled, using other than default configuration and with legacy or at least current production code I would say is preferred for central components like this on top of unit testing. So closer to integration/delivery/acceptance.

**Comment by adamretter** [comment]
@ljo But your live system is different to anyone else's live system, so it is not a repeatable test. For example none of my live systems use xars! Instead when issues are found that are not covered by the test suite, then tests should be added.

**Comment by ljo** [comment]
@adamretter yes, they should of course be fed back as unit tests. But to get a broad spectrum probe testing it in any one live system could add some insights even if not repeatable. This was for mainly for @dizzzz on what could be done in addition. And I just said it was a preferred addition.

**Comment by adamretter** [comment]
@ljo okie doke.

**Comment by wolfgangmm** [comment]
Just for explanation: I test every pull request (or set thereof) which may affect core performance against two or three apps using a data set of around 20 gb. I mainly concentrate on install/upload performance, selected queries, memory consumption. This costs some time (about 2 to 3 hours), but gives me some confidence, in particular concerning memory leaks. I'm currently running the test for Adam's last PRs and I'm happy if Leif does the same.

Now that at least one of the data sets is actually in the public domain, I'd like to automate this type of load testing.

I would welcome a skype chat, also to coordinate preparations for the next release. There are still a lot of bugs to be addressed. How about tomorrow or Thursday evening?

**Comment by dizzzz** [comment]
Wednesday would be fine, thursday is not possible for me....

**Comment by adamretter** [comment]
@wolfgangmm Anytime is fine for me. I would also like to see those tests automated :-)

**Comment by ljo** [comment]
I just got a meeting moved to tomorrow evening, but let me know the time. From 20.30 I will be available.

**Comment by wolfgangmm** [comment]
Ok, so let's say 20:30 CEST tomorrow. I'll send a hangout link.

**Comment by shabanovd** [comment]
any time is fine for me

**Comment by dizzzz** [comment]
Ok, great.

**Comment by wolfgangmm** [comment]
I was getting a deadlock after applying this PR to my test system. Investigating ...

**Comment by adamretter** [comment]
@wolfgangmm Okay very interesting. Let me know what you find...

**Comment by wolfgangmm** [comment]
The deadlock occurs because withCollection keeps a lock on the collection of the main query while parsing it. Import statements need to lock other resources in order to check their validity, so the collection should not remain locked.

As always, reproducing a deadlock depends on the exact timing, but it happens quite easily on my machine by hitting reload on the dashboard a few times.

```
Threads currently waiting for a lock:
=====================================
Thread: eXistThread-33
           Lock type: COLLECTION
           Lock mode: READ
             Lock id: /db/apps/dashboard/modules
             Held by: [eXistThread-45]
             Held by: [eXistThread-45]
             Held by: [eXistThread-45]
    Waiting for read: []
   Waiting for write: []
```

```
"eXistThread-45" #45 prio=5 os_prio=31 tid=0x00007fa455019000 nid=0x840b waiting for monitor entry [0x0000000125aa1000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.exist.storage.XQueryPool.returnObject(XQueryPool.java:133)
	- waiting to lock <0x000000078085fa00> (a org.exist.storage.XQueryPool)
	at org.exist.storage.XQueryPool.returnCompiledXQuery(XQueryPool.java:129)
	at org.exist.http.RESTServer.lambda$compileQuery$99(RESTServer.java:1403)
	at org.exist.http.RESTServer$$Lambda$51/1696695126.apply(Unknown Source)
	at org.exist.http.RESTServer.processExecutable(RESTServer.java:531)
	at org.exist.http.RESTServer.lambda$null$15(RESTServer.java:428)
	at org.exist.http.RESTServer$$Lambda$38/516271227.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at org.exist.http.RESTServer.lambda$processGetUri$16(RESTServer.java:425)
	at org.exist.http.RESTServer$$Lambda$32/1593647117.apply(Unknown Source)
	at org.exist.http.RESTServer.lambda$withDocument$89(RESTServer.java:1255)
	at org.exist.http.RESTServer$$Lambda$36/1231792430.apply(Unknown Source)
	at org.exist.http.RESTServer.lambda$null$86(RESTServer.java:1242)
	at org.exist.http.RESTServer$$Lambda$34/1980999548.apply(Unknown Source)
	at org.exist.http.RESTServer.lambda$withCollection$90(RESTServer.java:1280)
	at org.exist.http.RESTServer$$Lambda$33/675156664.apply(Unknown Source)
	at org.exist.http.RESTServer.lambda$withDocument$87(RESTServer.java:1238)
	at org.exist.http.RESTServer$$Lambda$31/1717034254.apply(Unknown Source)
	at org.exist.http.RESTServer.processGetUri(RESTServer.java:424)
	at org.exist.http.RESTServer.doGet(RESTServer.java:381)

"eXistThread-33" #33 prio=5 os_prio=31 tid=0x00007fa457a1e800 nid=0x7503 in Object.wait() [0x00000001292b8000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.exist.storage.lock.ReentrantReadWriteLock.acquire(ReentrantReadWriteLock.java:148)
	- locked <0x0000000780f03d70> (a org.exist.storage.lock.ReentrantReadWriteLock)
	at org.exist.collections.Collection.getDocumentWithLock(Collection.java:789)
	at org.exist.storage.NativeBroker.getXMLResource(NativeBroker.java:2181)
	at org.exist.source.DBSource.isValid(DBSource.java:89)
	at org.exist.xquery.ExternalModuleImpl.moduleIsValid(ExternalModuleImpl.java:252)
	at org.exist.xquery.XQueryContext.checkModulesValid(XQueryContext.java:1592)
	at org.exist.xquery.PathExpr.isValid(PathExpr.java:492)
	at org.exist.storage.XQueryPool.borrowObject(XQueryPool.java:195)
	at org.exist.storage.XQueryPool.borrowCompiledXQuery(XQueryPool.java:205)
	- locked <0x000000078085fa00> (a org.exist.storage.XQueryPool)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:681)
```

**Comment by shabanovd** [comment]
Think that
```
if (!query.isValid()) {
    remove(key);
    return null;
}
```
must be done outside synchronized block and borrowCompiledXQuery should be none synchronized

**Comment by adamretter** [comment]
Thanks @wolfgangmm I will take a look at this in the next 2 days or so (playing with transactions at the moment) and also check @shabanovd suggestion.

**Comment by dizzzz** [comment]
hmmmmm this one is still around?

**Comment by adamretter** [comment]
Yes, I need to find the time to finalise it.

On 21 October 2015 at 21:44, Dannes Wessels <notifications@github.com>
wrote:

> hmmmmm this one is still around?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/pull/549#issuecomment-150019038>.
>



-- 
Adam Retter

skype: adam.retter
tweet: adamretter
http://www.adamretter.org.uk

**Comment by dizzzz** [comment]
Also this one is still open.....

**Comment by adamretter** [comment]
@dizzzz Yes, as I wrote above I need to make some small changes to it.

**Comment by duncdrum** [comment]
@adamretter with new interest in the REST api from @eXist-db/tools maybe its a good time to rebase this for the next RC?

**Comment by duncdrum** [comment]
So…?

**Comment by adamretter** [comment]
It is unlikely I will revive this for eXist-db. FusionDB will have a new http server to replace this. Unless anyone wants to continue this work, I suggest we close the PR

**Comment by duncdrum** [comment]
well @line-o and i talked about update to REST, @adamretter could you rebase this, so we see where its at?

**Comment by adamretter** [comment]
@duncdrum sorry, rebasing this requires resolving a lot of merge conflicts. Someone else is welcome to do so though...

**Comment by line-o** [comment]
@adamretter We would need to understand the changes and concepts behind this, in order to be able to do revive development. What are the expected benefits that would justify this?

**Comment by adamretter** [comment]
@line-o there are as laid out in the bullet points at the top of this PR.

**Comment by adamretter** [comment]
I won't be developing this further. If someone else wishes to continue with it, please feel free.

**Pull request closed without merging**
