### PR TITLE
fix Rest client file encoding 

### PR DESCRIPTION
**Pull request by marmoure**
this Fixes: https://github.com/eXist-db/exist/issues/4458
as mentioned in the issue above the rest client was unable to handle filenames with special characters. This fixes that for all HTTP request GET,POST,PUT,DELETE
now storing resource like 
```xquery
xquery version "3.1";

xmldb:create-collection("/db","AéB"),
xmldb:store(xmldb:encode("/db/AéB"), xmldb:encode("AéB.xml"), <foo/>)
```
and performing operations on it from the rest client works fine eg:
GET: http://localhost:8080/exist/rest/db/A%C3%A9B/A%C3%A9B.xml

### CODE REVIEW

**Comment by dizzzz** [comment]
Quite some tests fail :-(

This is a tricky PR, this subject has been 'a challenge' since ages. Eg with this change, is it still possible to get the document consistently using webdav, and using `doc(..)', and in the Java client?

**Review by dizzzz — CHANGES_REQUESTED** [review]
Please check tests

**Comment by adamretter** [comment]
@dizzzz So this one specifically focuses on improving the handling in the REST Server. It does improve the current situation. We do have some work scheduled here at Evolved Binary in the near-future to improve the situation for other interfaces too. However, I think this PR can standalone and be merged as it is an improvement. Does that sound reasonable?

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
great thnx

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
