### PR TITLE
[bugfix] Block creation of collection by guest  #3505

### LINKED ISSUE #3505: [BUG] Guest users can create collections hidden from dba users
**Describe the bug**

Guest users can create collections. The collections are “available” but completely hidden from dba users.

**Expected behavior**

Guest users should not be able to create collections. Created collections should always be visible to dba users.

**To Reproduce**

1. Log into the Java admin client as guest.
2. Create a collection “test” in “/db” (ensuring that this collection doesn’t already exist). You’ll get an error that guest cannot create a collection.
3. Submit a query, `xmldb:collection-available("/db/test")`, and the query will return `true()`.
4. Refresh the database listing, and there’s no “test” collection.
5. Even weirder, now log in as admin, and run the query, `xmldb:store("/db/test", "test.xml", <test/>)`. The query completes without error. Now refresh the directory contents, and notice that there’s still no "test" collection.

**Context (please always complete the following information):**

 - OS: macOS 10.15.6
 - eXist-db version: 5.3.0-SNAPSHOT dd71ec6d727c6963fb23f67bfd55ae371afcde7a 20200610124401
 - Java Version: OpenJDK 1.8.0_265 (Zulu 8.48.0.53-CA-macosx build 1.8.0_265-b11)

**Additional context**

- How is eXist-db installed? Built from source, running via .app
- Any custom changes in e.g. `conf.xml`? No

### PR DESCRIPTION
**Pull request by dizzzz**
fixes #3505 
added tests @joewiz

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz I think the fix looks good and is certainly on the right path. Would you be able to contribute a test for this please?

**Comment by dizzzz** [comment]
Would  a Xquery based test be able to do the test?

**Comment by adamretter** [comment]
@dizzzz I am not certain, all the security tests so far are in Java.

**Comment by joewiz** [comment]
In my testing, the xqsuite tests in this PR show that the PR prevents guest from perfrorming the xmldb:create-collection operation. In develop (before this PR), the tests fail (well, the first try passes since the exception is thrown, but the 2nd and subsequent executions of the same test fail because the collection was actually created in the 1st pass).

**Review by joewiz — APPROVED** [review]

**Comment by joewiz** [comment]
17 successful and 3 failing - looking good! 

Appveyor says:

```
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ exist-index-range ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\projects\exist\extensions\indexes\range\target\test-classes
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] org.exist.xquery.modules.file.XmldbBinariesTest.readAndWriteBinary[remote]
[ERROR]   Run 1: XmldbBinariesTest>AbstractBinariesTest.setup:58->storeBinaryFile:74 � XMLDB Fa...
[ERROR]   Run 2: XmldbBinariesTest>AbstractBinariesTest.cleanup:63->removeCollection:121 � XMLDB
[INFO] 
[ERROR] org.exist.xquery.modules.file.XmldbBinariesTest.readBinary[remote]
[ERROR]   Run 1: XmldbBinariesTest>AbstractBinariesTest.setup:58->storeBinaryFile:74 � XMLDB Fa...
[ERROR]   Run 2: XmldbBinariesTest>AbstractBinariesTest.cleanup:63->removeCollection:121 � XMLDB
```

The other 2 failures were Java 11 (macOS latest) and 15 (ubuntu latest). The macOS failure looks like the dependency check random rate limit issue we discussed on community calls:

```
Error:  Failed to execute goal org.owasp:dependency-check-maven:6.1.6:check (default) on project exist-restxq: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
Error:  	AnalysisException: Failed to request component-reports
Error:  		caused by TransportException: Unexpected response; status: 429
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :exist-restxq
Error: Process completed with exit code 1.
```

As to the ubuntu issue, I can't really tell where the real error appears, so I won't paste anything in.

As to all 3, I can't judge their significance, I'm afraid...

**Comment by dizzzz** [comment]
rerunning Appveyor

**Comment by joewiz** [comment]
@dizzzz AppVeyor is green! We just need an approval from a member of @eXist-db/core.

**Review by line-o — APPROVED** [review]
Very cool! Great work @dizzzz

**Pull request merged**
