### PR TITLE
Feature/major sync

### PR DESCRIPTION
**Pull request by alebastrov**
https://github.com/eXist-db/exist/issues/847
https://github.com/eXist-db/exist/issues/851
https://github.com/eXist-db/exist/issues/852

### CODE REVIEW

**Comment by adamretter** [comment]
@alebastrov I am working on cleaning up your PR (it wasn't based on the HEAD of the develop branch), and splitting some of your commits. I am almost finished, my work in progress is here: https://github.com/adamretter/exist/commits/853

**Comment by adamretter** [comment]
@alebastrov I have rebased this and reworked it, thanks for your contribution, the updated PR is here - https://github.com/eXist-db/exist/pull/886

**Comment by alebastrov** [comment]
Thank you very much, It was very pleasant to work with you guys

**Comment by JoernT** [comment]
@adamretter if you reworked it in another PR doesn't that mean that this one can be closed?

**Comment by adamretter** [comment]
@JoernT Yes, but not just yet please, as my reworked PR still needs some attention.

**Comment by JoernT** [comment]
ok - that's fine - just wondered if this has been forgotten.

**Comment by adamretter** [comment]
I am going to close this, the non-synchronization stuff has been move out into https://github.com/eXist-db/exist/pull/1822 and the synchronization stuff has been taken care of in the much larger piece of work here - https://github.com/eXist-db/exist/pull/1719

**Pull request closed without merging**
