### PR TITLE
Upgrade to latest YAJSW

### PR DESCRIPTION
**Pull request by dizzzz**
upgrade to 12.12, including late fix for issue reported by @adamretter 

Overlaps with PR from Adam, but contains a split of .bat files into separate directory, generic update of .sh files.

### CODE REVIEW

**Comment by dizzzz** [comment]
I have one remark: the systemd support has moved into separate .sh files ; we need to document how to use the new way of working, if any.

**Comment by adamretter** [comment]
The shell files in their 12.12 release for systemd are broken. Hence me not changing them in eXist

**Comment by dizzzz** [comment]
Ok lets wait for the next iteration then

**Comment by joewiz** [comment]
@dizzzz Did you want to keep this branch around until then?

**Pull request closed without merging**
