### PR TITLE
Rest URLs consistency

### PR DESCRIPTION
**Pull request by hungerburg**
Resources containing certain characters (mostly from the RFC 3986 reserved set) cannot be GET by the name, that was used to PUT them: The included unit test case spells them out in full detail. The rest of the branch makes the unit test succeed.

Beware that this is just a starting point: Some further normalization will be necessary to deliver cross user agent interoperability; eg. the encoded path may contain superficial escape sequences. Yet the place for that might rather be the XmldbURI class.

### CODE REVIEW

**Comment by windauer** [comment]
The Unit tests fail with the following error: 

  [javac] /home/travis/build/eXist-db/exist/src/org/exist/http/RESTServer.java:396: error: XmldbURI(String) has protected access in XmldbURI
    [javac]         final XmldbURI pathUri = new XmldbURI(pathStr);
    [javac]                                  ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

**Comment by hungerburg** [comment]
Build failure corrected, hopefully. (Why did it work locally once? Now fails here too…) Waiting for travis and the complete test suite.

**Comment by hungerburg** [comment]
Travis fails, though seems to be unrelated to this pull request…

**Comment by windauer** [comment]
@hungerburg you are right. Although thats even worse /o\

**Comment by hungerburg** [comment]
@windauer Lars, would you care and do away the *invalid* label. Also I considered *bug* quite appropriate. In fact, this is a refactoring of #127.

**Comment by hungerburg** [comment]
Here quite happy now with the patches, considerable effort went into this research. I hope you can make good use of it, if at least as an inspiration. The changes to AdjustPath use java.net.URI with dummy parameters to work around a *imho* severe deficiency of the java standard library in dealing with loose components of URIs, like they are passed around in servlet containers. XmldbURI.createInternal() is now used as an alias for createFromEncodedPath(), which seems not too far off, from reading the signature comment. This I think is the most that can be done, without touching XmldbURI.java, which I rather not do.

**Comment by adamretter** [comment]
@hungerburg Thanks for your contribution it looks well tested, and sorry for the delay.

**Comment by hungerburg** [comment]
@adamretter Adam, Thank you for the trust you put in my code: I see, you took the complete changes, except the addition of /lib/test to the PATH in run.sh, which allowed me to run only certain unit tests from command-line (ant) instead of the whole suite.

If that makes it into the upcoming release, the Notes should point out, that users, that did double encode when fetching no longer have the need for this. Binaries with two-byte utf characters seem to be save, though a backup--restore cycle should be recommended for upgraders.

As time permits, I may now expand RESTServiceTest to also try and create binaries, as the limits between eXist-db internal xml store and the underlying file systems differ a bit regarding characters allowed in a directory or file name. First test shows, that linux extfs is good. NTFS will have problems (nothing new though), hopefully the error messages will be clear.

Compatibility with WEBDAV also is much better now, though some chars remain problematic:
problematic eXist:   `# % / ? [ ]`
problematic cadaver: `? *`
(cadaver does globbing, so cannot handle wildcards, the star works in davfs2, not the question mark)

below a table of an improvised test:

Filename       | REST listing   | WEBDAV listing | Content
---------------|----------------|----------------|--------
T_0-9__.txt    | T_0-9__.txt    | T_0-9__.txt    | T_0-9__
T_%20__.txt    | T_%20__.txt    | T_ __.txt      | T_ __
T_%23__.txt    | T_%23__.txt    | T_#__.txt      | T_#__
T_%25__.txt    | T_%25__.txt    | T_%__.txt      | T_%__
T_%2F__.txt    | T_%2F__.txt    | T_/__.txt      | T_/__
T_%3F__.txt    | T_%3F__.txt    | T_?__.txt      | T_?__
T_%5B__.txt    | T_%5B__.txt    | T_[__.txt      | T_[__
T_%5D__.txt    | T_%5D__.txt    | T_]__.txt      | T_]__
T_a-z__.txt    | T_a-z__.txt    | T_a-z__.txt    | T_a-z__
T_A-Z__.txt    | T_A-Z__.txt    | T_A-Z__.txt    | T_A-Z__
T_%C3%A4__.txt | T_%C3%A4__.txt | T_ä__.txt      | T_ä__
T_~__.txt      | T_~__.txt      | T_~__.txt      | T_~__
T_=__.txt      | T_=__.txt      | T_=__.txt      | T_=__
T____.txt      | T____.txt      | T____.txt      | T____
T_-__.txt      | T_-__.txt      | T_-__.txt      | T_-__
T_,__.txt      | T_,__.txt      | T_,__.txt      | T_,__
T_;__.txt      | T_;__.txt      | T_;__.txt      | T_;__
T_!__.txt      | T_!__.txt      | T_!__.txt      | T_!__
T_.__.txt      | T_.__.txt      | T_.__.txt      | T_.__
T_'__.txt      | T_'__.txt      | T_'__.txt      | T_'__
T_(__.txt      | T_(__.txt      | T_(__.txt      | T_(__
T_)__.txt      | T_)__.txt      | T_)__.txt      | T_)__
T_@__.txt      | T_@__.txt      | T_@__.txt      | T_@__
T_$__.txt      | T_$__.txt      | T_$__.txt      | T_$__
T_*__.txt      | T_*__.txt      | T_*__.txt      | T_*__
T_&__.txt      | T_&__.txt      | T_&__.txt      | T_&__
T_+__.txt      | T_+__.txt      | T_+__.txt      | T_+__

**Comment by adamretter** [comment]
@hungerburg I didn't take the changes to `bin/run.sh` only because you modified the *ENDORSED* path, which is not quite the correct one to modify (although you would have achieved the desired end-result).

I would be happy to see more Tests around URIs and URI encoding. I think ultimately someone will  probably need to start from scratch and write a new `XmldbURI` class... the existing one is just hideous!

**Pull request closed without merging**
