### PR TITLE
Fixed the trigger functionality

### PR DESCRIPTION
**Pull request by ChiSamurai**
- fixes https://github.com/eXist-db/exist/issues/255
- PR for updating the documentation here: https://github.com/eXist-db/documentation/pull/72

### CODE REVIEW

**Comment by shabanovd** [comment]
Is it possible to keep order as it was (new-url, old-url)?

**Comment by ChiSamurai** [comment]
Sure, but Joe and Alister proposed to make this consistent for "before" and "after" trigger. Since the relevant triggers did not work at all and all the trigger functionality broke after using them this change imo will not affect existing usage.

**Comment by adamretter** [comment]
@ChiSamurai I am happy for it to change if it means we get a better API

**Comment by shabanovd** [comment]
@adamretter the problem that compatibility will be broken ... again ... -(

**Comment by shabanovd** [comment]
@ChiSamurai the idea was to keep 1st parameter in-storage resource location and 2nd informative (what will be or what was).

The xquery interface also was in-line with java interface https://github.com/eXist-db/exist/blob/develop/src/org/exist/collections/triggers/CollectionTrigger.java#L55 or https://github.com/eXist-db/exist/blob/develop/src/org/exist/collections/triggers/DocumentTrigger.java#L103

**Comment by ChiSamurai** [comment]
hmm... I just tried to change the output order. I don't really understand the complete code but it seems that there are some dependecies on the  (old-url, new-url) for any of these triggers. Every try to change the order broke the trigger functionality completely.

**Comment by ChiSamurai** [comment]
But if compatibility is affected, it would surely be good to change this... maybe somebody more trained in Java can have a look? I got a xquery unit-test which fires each trigger once which I can provide.

**Comment by shabanovd** [comment]
@ChiSamurai can you commit? and I'll review it

**Comment by ChiSamurai** [comment]
@shabanovd The test contains three files: the collection.xconf, the trigger xquery functions itself and the xquery with collection and a xquery script which does the collection and resource operations.  Can I just write you an email? Or maybe skype or jabber?

**Comment by shabanovd** [comment]
@ChiSamurai sure

**Comment by shabanovd** [comment]
fixed by https://github.com/eXist-db/exist/pull/910

**Pull request closed without merging**
