### PR TITLE
(5.0.0) Update to Tika version 1.20

### PR DESCRIPTION
**Pull request by adamretter**
Backport of https://github.com/eXist-db/exist/pull/2558

### CODE REVIEW

**Comment by dizzzz** [comment]
@adamretter  suggested me to hold back from pulling the change in until the hot fix is out...

**Comment by joewiz** [comment]
@dizzzz @adamretter Sorry, I must've missed that. Perhaps next time please add a "do not merge" note to this effect on the PRs in question.

**Comment by adamretter** [comment]
@joewiz @dizzzz The comment was about 4.x.x, as we wanted to do a hotfix release next. I did actually right a "do not merge" on the relevant PR previously, see - https://github.com/eXist-db/exist/pull/2560 ;-)

**Comment by joewiz** [comment]
@adamretter Ugh, I’m not sure how I missed that.

**Comment by adamretter** [comment]
@joewiz no worries.

**Pull request merged**
