### PR TITLE
Add options for securing the XML Parser

### PR DESCRIPTION
**Pull request by adamretter**
Adds the facility for configuring the XML parser from `conf.xml`. This allows the user to specify various options. It is suggested to use the commented options in `conf.xml` to secure the parser.

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz Yes, I am aware. I was trying to see if there was some different Parser used. It seems not. I am going to attempt to download the Docker image that Travis uses and debug them locally.

**Comment by duncdrum** [comment]
@adamretter the codacity suggestions seem sensible, mind addressing them?

**Comment by adamretter** [comment]
@duncdrum done!

**Comment by adamretter** [comment]
@dizzzz So the CI now says "Hell Yeah!"

**Pull request merged**
