### PR TITLE
[HOTFIX] Avoid unauthorised creation of collections.

### LINKED ISSUE #3505: [BUG] Guest users can create collections hidden from dba users
**Describe the bug**

Guest users can create collections. The collections are “available” but completely hidden from dba users.

**Expected behavior**

Guest users should not be able to create collections. Created collections should always be visible to dba users.

**To Reproduce**

1. Log into the Java admin client as guest.
2. Create a collection “test” in “/db” (ensuring that this collection doesn’t already exist). You’ll get an error that guest cannot create a collection.
3. Submit a query, `xmldb:collection-available("/db/test")`, and the query will return `true()`.
4. Refresh the database listing, and there’s no “test” collection.
5. Even weirder, now log in as admin, and run the query, `xmldb:store("/db/test", "test.xml", <test/>)`. The query completes without error. Now refresh the directory contents, and notice that there’s still no "test" collection.

**Context (please always complete the following information):**

 - OS: macOS 10.15.6
 - eXist-db version: 5.3.0-SNAPSHOT dd71ec6d727c6963fb23f67bfd55ae371afcde7a 20200610124401
 - Java Version: OpenJDK 1.8.0_265 (Zulu 8.48.0.53-CA-macosx build 1.8.0_265-b11)

**Additional context**

- How is eXist-db installed? Built from source, running via .app
- Any custom changes in e.g. `conf.xml`? No

### PR DESCRIPTION
**Pull request by dizzzz**
Fixes #3505 
Make sure transaction is aborted upon exception.

### CODE REVIEW

**Review by line-o — APPROVED** [review]
Thanks a ton @dizzzz

**Comment by line-o** [comment]
Should we create a test for this?

**Review by adamretter — APPROVED** [review]

**Comment by dizzzz** [comment]
Jikes :-( though I think the approach is OK, I was wrong with my manual tests :-(  This PR does not fix :-(

**Comment by dizzzz** [comment]
image

I wonder why this `transaction.commit()` is invoked so often, even when there is no write operation done, e.g. typing `cd` in the java client command box. Might that be a source of issues?

**Comment by line-o** [comment]
And still I am seeing `Transaction was not committed nor aborted!` in my logs every now and then :)

**Pull request merged**
