### PR TITLE
Fix CI issues with PR that require GitHub Secrets

### PR DESCRIPTION
**Pull request by adamretter**
GitHub Secrets can not be access from Pull Requests, see: https://github.com/eXist-db/exist/settings/secrets/actions

### CODE REVIEW

**Comment by reinhapa** [comment]
@adamretter I doubt that just disabling the check when no secrets are available is the solution to go here, there must be a other solution somehow.

**Comment by dizzzz** [comment]
at least there are no errors :-) .... as long we are sure the test is executed at certain moments I'd be happy

**Comment by adamretter** [comment]
>  I doubt that just disabling the check when no secrets are available is the solution to go here, there must be a other solution somehow.

I don't know of one. @reinhapa Do you have something in mind?

**Comment by reinhapa** [comment]
> > I doubt that just disabling the check when no secrets are available is the solution to go here, there must be a other solution somehow.
> 
> I don't know of one. @reinhapa Do you have something in mind?

Maybe `pull_request_target`  instead of `pull_request` could be an alternative taking the following [security implications](https://dev.to/suzukishunsuke/secure-github-actions-by-pullrequesttarget-641) into account

**Comment by adamretter** [comment]
@reinhapa As I understand it `pull_request_target` is quite neat, and should likely be our default for triggering CI (can be done in a separate PR) - however using it for the NVD task won't help us, as even with that you still can't access Secrets from a PR CI run.

**Review by reinhapa — APPROVED** [review]

**Comment by reinhapa** [comment]
@adamretter we still seem to have troubles with the windows builds...

**Comment by adamretter** [comment]
> we still seem to have troubles with the windows builds...

@patrick it looks like a network blip as I see the following in the CI output:

> status code: 502, reason phrase: Bad Gateway (502)

I have restarted the build...

**Comment by dizzzz** [comment]
image

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
