### PR TITLE
(5.0.0) fix context sequence for higher order functions and sorting

### PR DESCRIPTION
**Pull request by windauer**
Port of #2470

### CODE REVIEW

**Comment by adamretter** [comment]
@windauer  You have some merge conflicts and also #2141 is now merged. Could please rebase this on the develop HEAD? We can then look to get this PR merged.

**Comment by windauer** [comment]
rebased.

**Comment by wolfgangmm** [comment]
3 tests are currently failing

**Comment by windauer** [comment]
I did another rebase because of a merge conflict in exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java after another PR was added first.. rebasing nightmare...

**Pull request merged**
