### PR TITLE
Trim list of packages in default installer

### LINKED ISSUE #1302: Trim packages from the default installer
### What is the problem

The default installer contains 12 packages. Besides adding to the download size, each package adds time to the first time startup and clutter to the default dashboard. 

### Proposal

Adopt the following principles for judging which apps should be included in the default installer:

1. Include apps that are cited in the UI (namely, the menu bar references "dashboard," "eXide," and "Monitoring and Profiling") and the "shared-resources" package that these basic apps rely on. 

2. Include the core documentation (namely, "docs" and "fundocs") that arguably every user is likely to consult and the "markdown" package that fundocs relies on.

Other than these entries, demos and other libraries are readily accessible via the dashboard package manager, so should be excluded. 

A forthcoming PR will trim the following list of 12 packages (11.7 MB):

```
2.1M 00shared-resources-0.4.0.xar
646K bf-XForms-1.4.xar
559K dashboard-0.4.7.xar
497K demo-0.3.3.xar
4.3M doc-0.4.7.xar
1.4M eXide-2.3.2.xar
 30K fundocs-0.7.xar
8.4K markdown-0.4.xar
1.3M monex-0.9.6.xar
 19K xqjson-0.2.0.xar
200K xsltforms-594.xar
133K xsltforms-demo-0.1.5.xar
```

to this list of 7 packages (10.2 MB a marginal savings of 1.5 MB)

```
2.1M 00shared-resources-0.4.0.xar
559K dashboard-0.4.7.xar
4.3M doc-0.4.7.xar
1.4M eXide-2.3.2.xar
8.4K markdown-0.4.xar
 30K fundocs-0.7.xar
1.3M monex-0.9.6.xar
```

### Context information

- eXist-db version + Git Revision hash: eXist-db 3.0 develop

### PR DESCRIPTION
**Pull request by joewiz**
### Description:

Trim list of packages in default installer

### Reference:

https://github.com/eXist-db/exist/issues/1302 (Closes #1302)

### Type of tests:

n/a

### CODE REVIEW

**Comment by joewiz** [comment]
If/when this is merged, please squash and commit.

**Comment by shabanovd** [comment]
```
Squash and merge
The 2 commits from this branch will be combined into one commit in the base branch.
**Not enabled for this repository**
```

**Comment by dizzzz** [comment]
hmmm did someone switch it off?

**Comment by joewiz** [comment]
@dizzzz Okay, I've rebased this PR into a single commit. Please merge when convenient. Thank you!

**Comment by adamretter** [comment]
@dizzzz Yes the more complex merge PR options were disabled. That was done because they do not make merge commits in the base branch `develop`, which makes undoing a PR very difficult. In the last teleconf @wolfgangmm stated that he wanted the ability to undo troublesome PRs if they were not stable when we are cutting a release.

**Comment by joewiz** [comment]
@adamretter No worries, I don't mind rebasing my PRs into a single commit. This just puts the burden on the submitter of the PR to do so; and I'd suggest letting the PR requester decide if they want to do this, since it can result in lost comments (particularly comments hung directly on commits).  I think if reviewers have approved a PR, they should be certainly feel free to ask the submitter to rebase, but it shouldn't be a condition of merging the PR - if the PR was approved on its merits. Just articulating one approach to this for the future discussion on the role of the issue tracker and PR expectations.

Please merge when convenient, thank you!

**Comment by adamretter** [comment]
@joewiz actually it doesn't necessarily force the burden onto the submitter. The person doing the merge can rebase and merge it with Git. I have done this a few times to add tests to PRs or fix merge conflicts (e.g. https://github.com/eXist-db/exist/commit/0044ff2b75cf35514f88d9150e6bfaaa82527cd7), it can't be done through the Git UI, but using the git command it is just two commands.

**Comment by joewiz** [comment]
@adamretter Thank you! And good to know. I see some opportunities for transparency and understanding, which could be mentioned not just in a proposal/document but also in the PR template: (1) The reviewer (rather, whoever serves as the "merge manager" for a particular PR) reserves the right to rebase a PR after submitting it without notice. (2) If the reviewer adds tests, or otherwise modifies the content of the PR, the reviewer will wait, say, 24 hours before performing a final rebase/merge to allow the submitter a chance to comment. Again, just some ideas.

**Pull request merged**
