### PR TITLE
Update to Jetty 9.4.6.v20170531

### PR DESCRIPTION
**Pull request by adamretter**
May help with https://github.com/eXist-db/exist/issues/1521

### CODE REVIEW

**Comment by dizzzz** [comment]
This would probably be A Good moment to move the websocket jar from monex into the distribution?

**Comment by adamretter** [comment]
@dizzzz I don't know anything about Monex, so I would rather leave that to someone else in a separate PR if they want to do that.

**Comment by dizzzz** [comment]
Sure.... I'll study on it.

**Comment by dizzzz** [comment]
For 3.5 right?

**Comment by adamretter** [comment]
@dizzzz I think it likely our next release will be 3.5.0. So I am happy for such PRs to be merged

**Comment by dizzzz** [comment]
Aren't there any files from eclipse/netbeans having references?

**Comment by adamretter** [comment]
@dizzzz Right you are! I just fixed that now :-)

**Pull request merged**
