### PR TITLE
Further tests for Cache Module and a small NPE avoidance fix

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/3932

### CODE REVIEW

**Review by line-o — APPROVED** [review]
Looks good `cache:put` should under no circumstance return null which could lead to an NPE.
Also CI passes and more Tests are more good.
Related question: Is the "enableLazyCreation" option documented?

**Comment by line-o** [comment]
The failing build on JDK11 is due to a request timeout. Should we restart the whole process?

**Comment by line-o** [comment]
Static code analysis indicates that this not null check is unnecessary. Under which circumstances previous could end up being null?
https://sonarcloud.io/project/issues?id=eXist-db_exist&open=AXof8Tqp65lVRGWXCjZE&pullRequest=3935&resolved=false&types=CODE_SMELL

**Comment by adamretter** [comment]
@line-o I am afraid that the static code analysis is wrong. Put on a Java Map can return null - https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#put-K-V-

**Comment by line-o** [comment]
A failure in static code analysis is worrying.

**Comment by adamretter** [comment]
@line-o It's not unusual. Static code analysis is often not perfect.

**Comment by line-o** [comment]
When I inspect the code in question in IDEA I get the following

Screenshot 2021-06-22 at 16 02 11

That looks to me as if the map type returned by the cache implementation annotates the value with @nonnull
That might lead to the static code analysis "thinking" that there is no way a null value might be returned.
And you also mention it as being potentially return null, that means you never actually observed it returning null, correct?

**Comment by adamretter** [comment]
> When I inspect the code in question in IDEA I get the following

@line-o I think your screenshot is showing that `asMap` cannot return `null`. The subsequent `put` can still return `null`.

**Comment by line-o** [comment]
OK, I come to the same conclusion.
Can we annotate (or comment) this line in some form. So that, if the same line is touched again SonarCloud does not yell and we or others have the same discussion again?

**Comment by adamretter** [comment]
@line-o SonarCloud has identified many false positives. I am not sure annotating them all makes sense...

**Comment by dizzzz** [comment]
probably annotating is a lot of work indeed

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
I'd trust to pull in... these 429's will just re-appear

**Comment by line-o** [comment]
A quick search found that adding

    //NOSONAR

To any end of a line is the way to handle won't fix and false positives in SonarQube. So it is likely to work on SonarCloud as well.

**Comment by line-o** [comment]
And also from what I now know I suspect it would be rather simple to create a test case that would provoke an NPE (and also prove that this is an issue).

**Review by dizzzz — APPROVED** [review]

**Comment by line-o** [comment]
A simple

```
cache:put("this new key", 1)
```

will cause a NPE or it does not.
Or am I missing something obvious?

**Comment by line-o** [comment]
```xquery
xquery version "3.1";

let $c := cache:create("a", map {})

return cache:put("a", "k", 1)
```
does not throw

**Comment by line-o** [comment]
Is the lazy / non-lazy cache creation option documented?

**Comment by adamretter** [comment]
> And also from what I now know I suspect it would be rather simple to create a test case that would provoke an NPE (and also prove that this is an issue).

Test are already included. If you remove the commit with the fix and re-run the tests you will see that they fail.

**Comment by adamretter** [comment]
> Is the lazy / non-lazy cache creation option documented?

@line-o Yes, already documented, see - https://github.com/eXist-db/documentation/pull/614

**Review by line-o — APPROVED** [review]
I was able to provoke the NPE with

   [cache:put("a", "k2", 1)]?1

**Pull request merged**
