### PR TITLE
(4.x.x) Add a test to assert the integrity of installer/jobs.xml

### PR DESCRIPTION
**Pull request by ohumbel**
This PR adds a long promised test which applies to the `develop-4.x.x` branch only.

See discussion on https://github.com/eXist-db/exist/pull/2896.

### CODE REVIEW

**Comment by ohumbel** [comment]
Sorry, the test miserably fails on windows - try to fix this with the next commit

**Comment by adamretter** [comment]
@ohumbel Hi Oliver, thanks for this. I am just wondering if you see it also as necessary for eXist-db 5.0.0 also?

**Comment by ohumbel** [comment]
> @ohumbel Hi Oliver, thanks for this. I am just wondering if you see it also as necessary for eXist-db 5.0.0 also?

Hi Adam,
no I don't think it applies to 5.0.0, since there is no `installer/jobs.xml` present any more. I believe you use a newer version of IzPack from 5.0.0 on.
Oti

**Comment by adamretter** [comment]
@ohumbel We are using the newer IzPack 5, which we instantiate from Maven.

There is still a `jobs.xml`, you find see it here - https://github.com/eXist-db/exist/blob/develop/exist-installer/src/main/izpack/jobs.xml.

**Comment by ohumbel** [comment]
All tests passed in the last run. 

But appveyor had an upload problem in the end.
I'll push another commit to trigger the checks again - proceed, with fingers crossed

**Comment by ohumbel** [comment]
> @ohumbel We are using the newer IzPack 5, which we instantiate from Maven.
> 
> There is still a `jobs.xml`, you can find it here - https://github.com/eXist-db/exist/blob/develop/exist-installer/src/main/izpack/jobs.xml.

@adamretter Please apologize my oversight.
Then it is of course necessary to create a PR for the `develop` branch as well. I'll go for that as soon as appveyor is giving me green lights here.

**Comment by adamretter** [comment]
@ohumbel are you still planning to port to `develop` in a separate PR?

**Comment by ohumbel** [comment]
@adamretter Yes I have a bit of time the next 2 weeks and will try to convince `appveyor` that my test does not change any behaviour. And a separate PR for `develop` as well.

**Comment by ohumbel** [comment]
This PR has quite a history of commits, but in essence only adds one `*Test.java`.
So in the very unexpected case of all checks passing this time, I'd suggest to `squash` merge it.

**Comment by ohumbel** [comment]
@adamretter Hooray all checks have passed. I'd suggest to `squash` merge this, since there is only one additional `*Test.java` file involved.
Meanwhile I started to port this to `develop`.

**Comment by ohumbel** [comment]
@adamretter Thanks for merging!

**Pull request merged**
