### PR TITLE
Catch exception and enrich exception with location information. 

### LINKED ISSUE #3473: [BUG] missing location info in errors involving type comparisons (XPTY0004)
**Describe the bug**

In eXist, errors involving type comparisons like `1 eq "2"` lack location information.

**Expected behavior**

I expected the errors to report the location of the error in the query, as they do in BaseX and Saxon.

**To Reproduce**

**Query 1**

```xquery
xquery version "3.1"; 

1 eq "2"
```

eXist error:

> err:XPTY0004 can not compare xs:string('1') with xs:integer('2')

BaseX returns the error at the end of the expression containing the error:

> Stopped at /Users/joe/Downloads/file, 3/9:
> 
> [XPTY0004] Types xs:integer and xs:string are not comparable.

Saxon reports the error as appearing at the first character of the expression containing the error:

> In {1 eq "2"}: cannot compare xs:integer to xs:string
> 
> Start location: 3:2

**Query 2**

```xquery
xquery version "3.1"; 

1 = "2"
```

eXist error: 

> err:XPTY0004 Incompatible primitive types

BaseX error:

> Stopped at /Users/joe/Downloads/file, 3/8:
> 
> [XPTY0004] Types xs:integer and xs:string are not comparable.

Saxon error:

> In {1 = "2"}: cannot compare xs:integer to xs:string
> 
> Start location: 3:2

**Context (please always complete the following information):**
 - OS: macOS 10.13.6
 - eXist-db version: 5.3.0-SNAPSHOT
 - Java Version: JDK 11.0.7+10 (Liberica 2020-04-14 LTS)

**Additional context**
- How is eXist-db installed? 5.3.0-SNAPSHOT built from source 
- Any custom changes in e.g. `conf.xml`? None.

### PR DESCRIPTION
**Pull request by dizzzz**
Closes #3473

An exception occurred during query execution: err:XPTY0004 Type error: cannot compare operands: xs:integer and xs:string [at line 1, column 3]

### CODE REVIEW

**Comment by joewiz** [comment]
I restarted Travis and Appveyor.

**Comment by dizzzz** [comment]
No idea why these failed, it is not logical with the change as effectively there is no different logic flow.

**Comment by joewiz** [comment]
I should've checked the logs before restarting the builds - perhaps there was a clue! One clue I stumbled upon in further testing is that with this PR, the locations of errors returned in other scenarios aren't accurate. 

For example, the location of the error below is on line 23 (the final line), and the develop branch reports this as expected, whereas when running a local build of the PR, the error reported is line 3, column 3:

```xquery
xquery version "3.1";

declare variable $local:colors :=
    map {
        "blue": "#2d7ff9",
        "cyan": "#18bfff",
        "gray": "#666",
        "grayDark": "666",
        "green": "#20c933",
        "greenDark": "20c933",
        "orange": "#ff6f2c",
        "pink": "#ff08c2",
        "pinkDark": "ff08c2",
        "purple": "#8b46ff",
        "red": "#f82b60",
        "redDarker": "f82b60",
        "teal": "#20d9d2",
        "yellow": "#fcb400",
        "yellowDark": "fcb400"
    }
;

error()
```

I won't restart CI if there are failures this time.

**Comment by dizzzz** [comment]
I restarted the build before you, but checked the logs;  there are issues in the index tests....

thnx for the additional testcase, I think I know a solution...

**Comment by dizzzz** [comment]
ok improved code. I was soo close

**Comment by dizzzz** [comment]
build looks good to go https://ci.appveyor.com/project/dizzzz/exist/builds/34010035

**Comment by adamretter** [comment]
@dizzzz would you be able to add some tests?

**Comment by dizzzz** [comment]
I have been thinking about that, for all late fixes.  Yes I will

**Comment by dizzzz** [comment]
@adamretter added the tests, also for the previous PRs

**Comment by dizzzz** [comment]
travis is ok

**Comment by dizzzz** [comment]
@adamretter @joewiz  all tests green!

**Pull request merged**
