### PR TITLE
[refactor] Update Mail Module to Jakarta Mail 2.0.0

### PR DESCRIPTION
**Pull request by adamretter**
Backported from FusionDB
Closes https://github.com/eXist-db/exist/issues/3969

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]
Almost a drop-in replacement

**Comment by adamretter** [comment]
@dizzzz Yes, it was less work than I remembered - unless I missed an additional commit I need to backport

**Comment by dizzzz** [comment]
:-(
image

**Review by dizzzz — CHANGES_REQUESTED** [review]
:-( still failing
image

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
jay !

**Pull request merged**
