### PR TITLE
Many simple bug fixes that were identified through static analysis

### PR DESCRIPTION
**Pull request by adamretter**
Fixes 363 bugs identified by static analysis with FindBugs. Still some 1000+ issues to check...

### CODE REVIEW

**Comment by shabanovd** [comment]
I can't say that I like fix without evidence of problem specially with `synchronized`. It easily can lead to deadlock.

**Comment by adamretter** [comment]
@shabanovd You are welcome to run FindBugs yourself and check through the issues or you can rely that I have done this already.

**Comment by shabanovd** [comment]
@adamretter FindBugs is not that smart after all (and I did it from time to time)

**Comment by adamretter** [comment]
@shabanovd Yes I agree that FindBugs can find false-positives... which is why I looked at each of these changes very carefully before I made them!

**Comment by shabanovd** [comment]
@adamretter to be clean, I'm not against all changers or I do not say that you did not spend time on each commit. All I want to say that `synchronized` at wrong place can bring headache.

**Comment by adamretter** [comment]
@shabanovd I agree, I think it is in the right place though now. Do you think otherwise?

**Comment by shabanovd** [comment]
@adamretter that just scared me ...

**Comment by adamretter** [comment]
@shabanovd So we can merge or you want to investigate?

**Comment by shabanovd** [comment]
if some one else review that then ok

**Pull request merged**
