### PR TITLE
4xx: Implement adaptive serialisation for fn:trace and util:log* functions

### LINKED ISSUE #2340: util:log should default to adaptive serialization
This spawned from the discussion in https://github.com/eXist-db/exist/issues/2339

### What is the problem

Logging more complex data structures using `util:log` can lead to misleading conclusions since maps and arrays are serialised to empty strings.

Example:

```xquery
util:log('debug', ('values:', map {'key':1}, ['more', 'data']))
```

Will be logged as 

```
2018-12-07 17:36:53,867 [qtp1658704411-695] DEBUG  (LogFunction.java [writeLog]:199) - (Line: 1 /db/apps/my-app/modules/test.xq) values:

```

### What did you expect

```
2018-12-07 17:36:53,867 [qtp1658704411-695] DEBUG  (LogFunction.java [writeLog]:199) - (Line: 1 /db/apps/my-app/modules/test.xq) values:map {'key':1},['more', 'data']
```

### Describe how to reproduce or add a test

1. eval the example
1. look for the entry in the exist.log

### Context information

Please always add the following information
- eXist-db 5.0.0-RC3 
- Java 8
- MacOs
- 64 bit
- build from GitHub
- no changes

### PR DESCRIPTION
**Pull request by dizzzz**
fixes #2340 

@wolfgangmm Can all serialization be done with the xqueryserializer with the 'adaptive' mode switched on?

### CODE REVIEW

**Comment by dizzzz** [comment]
jstack output of waning unit tests @adamretter 
[hang_2.txt](https://github.com/eXist-db/exist/files/2715065/hang_2.txt)

**Comment by dizzzz** [comment]
@wolfgangmm Can all serialization be done with the xqueryserializer with the 'adaptive' mode switched on?

**Comment by dizzzz** [comment]
Ok synced to develop and 5xx

**Comment by adamretter** [comment]
@dizzzz you merged your own PR?

**Comment by dizzzz** [comment]
@adamretter after to reviews (2x OK), I thought it was OK....

**Comment by line-o** [comment]
@dizzzz Thanks for the nice work and late Christmas gift. 🎉

**Pull request merged**
