### PR TITLE
[refactor] Do not config collections twice

### PR DESCRIPTION
**Pull request by adamretter**
http://exist-development.markmail.org/thread/g6vgcsmbp3dcnxst

### CODE REVIEW

**Comment by adamretter** [comment]
@ljo this wasn't ready to land yet! @shabanovd had some concerns I think. I am not sure we need to revert, but I might need to send a follow-up.

**Comment by ljo** [comment]
@adamretter OK. I thought your message said split the PR #730 so this is not delayed. But it was the other way around then.

**Comment by adamretter** [comment]
@ljo Yes, sorry for the ambiguous language.

**Comment by shabanovd** [comment]
@adamretter question was what to do with configurations in future. Is it ok to shift to ConcurrentHashMap? (I think yes)

**Comment by adamretter** [comment]
Hmmm... I thought you were worried that the second collection configuration
I removed was thread-safe, whereas the first (which remains) is not?

On 14 July 2015 at 17:02, Dmitriy Shabanov <notifications@github.com> wrote:

> @adamretter <https://github.com/adamretter> question was what to do with
> configurations in future. Is it ok to shift to ConcurrentHashMap? (I think
> yes)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/pull/734#issuecomment-121291270>.
>



-- 
Adam Retter

skype: adam.retter
tweet: adamretter
http://www.adamretter.org.uk

**Pull request merged**
