### PR TITLE
Fixed fn name functions to work with the Context Item

### PR DESCRIPTION
**Pull request by adamretter**
@tuurma this should fix your issue and then some ;-)
Closes https://github.com/eXist-db/exist/issues/1476

### CODE REVIEW

**Comment by dizzzz** [comment]
@adamretter it looks good to me, but I need to have an explanation (to prevent i will make similar bugs in the future...)

**Comment by adamretter** [comment]
@dizzzz the zero arity version of those functions, did not retrieve the context item correctly. Take a look at the tests that I added :-)

**Comment by joewiz** [comment]
@adamretter Thank you!  I had occasionally run into this and didn't realize that some of these functions had zero-arity versions.  To add to the explanation in the test cases, here's what I would bump into:

While `/name()` would work, e.g.,:

```xquery
xquery version "3.1";

declare namespace tei="http://www.tei-c.org/ns/1.0";

element tei:persName { "Dannes" }/name()
```

`node-name()` would return an error:

```xquery
element tei:persName { "Dannes" }/node-name()
```

would return:

> Unexpectedly received 0 parameter(s) in call to function 'node-name()'. Defined function signatures are: node-name($arg as node()?) xs:QName?

The workaround was to specify a context item, e.g., `/node-name(.)`. 

(I wonder if we need to do a review of eXist's function signatures against the spec? Or perhaps integrating the QT3 test suite, if only partially to focus on function signatures...)

**Comment by joewiz** [comment]
Also, for context, here's the link to the current spec for this function: https://www.w3.org/TR/xpath-functions-31/#func-local-name.

**Pull request merged**
