### PR TITLE
Upgrade to Apache Commons Pool 2

### PR DESCRIPTION
**Pull request by adamretter**
Requires https://github.com/eXist-db/exist/pull/4021

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]
LGTM ; I once had a loak at it to do the same, but I think I remember that eg betterForm was blocking this upgrade.

- [x] DWES: need to check replication code

**Comment by dizzzz** [comment]
all tests seem to time-out; restarting yet another time...

**Review by dizzzz — CHANGES_REQUESTED** [review]
The build is not stable :-( there are NPEs, timeouts...

**Comment by adamretter** [comment]
@dizzzz Yes, this one is still a draft.
We need to merge https://github.com/eXist-db/exist/pull/4021 first.

**Review by dizzzz — APPROVED** [review]

**Review by dizzzz — CHANGES_REQUESTED** [review]
exi module issue... strange? 
image

**Comment by adamretter** [comment]
@dizzzz Yup. Seem unrelated to this PR but I will see if I can fix it too...

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
