### PR TITLE
Fixes for names in XQuery 3

### PR DESCRIPTION
**Pull request by adamretter**
* Support for URIBracedLiteral
* Correct use of EQName instead of QName in XQuery 3.0.

### CODE REVIEW

**Comment by dizzzz** [comment]
wow, what a work! I fear I can't judge the details here, it looks pretty good. @wolfgangmm ? @ljo ? @shabanovd

**Comment by wolfgangmm** [comment]
I'm checking for compatibility issues with existing apps ... Will merge if ok.

**Comment by adamretter** [comment]
I don't expect any compatibility issues, as whilst references to `qName` have been replaced with `eqName`. The spec itself ensures backwards compatibility by making `eqName` a disjunction of `qName` and `URIQualifiedName`.

**Comment by wolfgangmm** [comment]
Handling qnames in the parser has always been a bit tricky, so I checked if any of the known issues (e.g. errors if one uses a keyword like "for" as element name) would pop up. It seems all ok, though.

**Pull request merged**
