### PR TITLE
Test should override default config

### PR DESCRIPTION
**Pull request by adamretter**
Fixes CI.

### CODE REVIEW

**Comment by duncdrum** [comment]
win still failing, it looks like you rebased, any ideas?

**Comment by adamretter** [comment]
@duncdrum Maybe just a blip? Windows tests are passing now

**Comment by dizzzz** [comment]
Are the tmp directories cleaned up?

**Comment by adamretter** [comment]
@dizzzz should be, that is what the `@Rule` does ;-)

**Pull request merged**
