### PR TITLE
Update the AppBundler plugin to better detect the Java version

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by adamretter** [comment]
@joewiz Done! Thank you :-)

**Comment by joewiz** [comment]
Hi Adam, Sean merges the PR fixing the outstanding issue with appbundler: https://github.com/TheInfiniteKind/appbundler/pull/46. Would you have time to prepare a new release of the maven plugin and update this PR? I’ll also submit an updated version of my 4.x PR.

**Comment by adamretter** [comment]
@joewiz I have now release `1.0.4` we will need a PR to `exist-distribution/pom.xml`

**Comment by joewiz** [comment]
@adamretter Thanks! I'll test and prepare a full round of PRs for develop-4.x, develop, and develop-5.0.0. It may take a few days as I'm traveling.

**Comment by joewiz** [comment]
Superseded by #2790.

**Pull request closed without merging**
