### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by dizzzz**
Refactoring code with IDEA hints ; improving quality in general

### CODE REVIEW

**Comment by dizzzz** [comment]
thnx for reviewing!
sure, but there are 100's of potential improvements out there :-)  I need to stop somewhere, right? 
these changes have been done more or less mechanically, low hanging fruit; I'll continue..... every now and then

**Comment by adamretter** [comment]
@dizzzz I will do a through review in the next day or so...

**Comment by dizzzz** [comment]
ok updated with input, test suite is running again

**Comment by shabanovd** [comment]
lgtm

**Comment by dizzzz** [comment]
done for now :-) @adamretter

**Comment by adamretter** [comment]
Sorry I missed my window. Now I'm snowed in until next week;-)

**Comment by ljo** [comment]
Looking through it.

**Comment by dizzzz** [comment]
Please :-) 14 days for such a simple PR ; should I pull in myself :-) ?

**Comment by ljo** [comment]
Sorry for the late response. Got caught by something else in the middle.

**Comment by adamretter** [comment]
@dizzzz Sorry I was in France on Holiday and then away for work. Today would have been my first opportunity, but I see @ljo has kindly taken care of it

**Pull request merged**
