### PR TITLE
fix context sequence for higher order functions and sorting

### PR DESCRIPTION
**Pull request by windauer**
Port of #2470

### CODE REVIEW

**Comment by windauer** [comment]
is it possible to re-run the AppVeyor tests without adding a (useless) commit to the PR @duncdrum, @adamretter ?

**Comment by duncdrum** [comment]
Yes click rerun. Should be visible to all core team members

**Comment by duncdrum** [comment]
@windauer can you rebase this PR please?

**Comment by dizzzz** [comment]
sometimes.... git does not understand simple file move operations, sigh

**Comment by adamretter** [comment]
@windauer You have some merge conflicts and also #2140 is now merged. Could please rebase this on the develop HEAD? We can then look to get this PR merged.

**Comment by adamretter** [comment]
Still needs to be rebased!

**Comment by windauer** [comment]
rebased

**Comment by windauer** [comment]
Hm strange, on my machine all XQuery tests work perfectly fine (especially the XQuery3Tests).. Could anyone please point me to the detailed junit reports to see if I find something in there? I requested another Travis run as well.

**Comment by duncdrum** [comment]
@windauer https://github.com/orgs/eXist-db/teams/core/discussions/2

**Comment by adamretter** [comment]
@windauer on AppVeyor that my are available from the Artifacts tab of the build.

**Comment by windauer** [comment]
@adamretter "The build job does not contain any artifacts." :( 
@duncdrum looks great but I did not figure out how to download the results for the failed run, will send you a pm. 

Next the executing the XQuery tests by hand (which were all green) I did run a ./build.sh test on my local machine. I'm got 1 failure and 4 errors but I would assume that these fail due to my system configuration and not because of this PR. The tests are 

Failure: 
-	testWithDefaultMimeTypeFeature

Errors: 
- unparsed-text-available-from-url-encoding
- unparsed-text-from-url
- unparsed-text-from-url-encoding
- unparsed-text-lines-from-url-count

The new travis run I requested is now queued for > 20 hours and I'm wondering if it will ever start ;)

**Comment by windauer** [comment]
update: I was able to reproduce the failing tests now localally .. had to do with a rebase issue. The failing tests are in org/xquery/test/arrowp for-each-pair-with-context-item and in org/xquery/test/function_sort its sort_context and sort_context_ao. Will need to do some further investigation..

**Comment by windauer** [comment]
I did another rebase because of a merge conflict in exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java after another PR was added first.. rebasing nightmare...

**Pull request merged**
