### PR TITLE
Make sure the correct context sequence is used with util:eval-with-context

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/3039

### CODE REVIEW

**Comment by dizzzz** [comment]
Please could we have Joe's test included as well?

```xquery
xquery version "3.1";

module namespace ewc="http://exist-db.org/xquery/eval-with-context";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
    %test:assertEquals(1)
function ewc:root-node() {
    util:eval-with-context('count(/)', (), false(), document { <x/> })
};
```

**Review by dizzzz — CHANGES_REQUESTED** [review]
Add joe's test case

**Comment by dizzzz** [comment]
A lot of travis tests fail, in the range index tests for example.

**Comment by adamretter** [comment]
@dizzzz Indeed. Those range index tests are not valid

**Comment by line-o** [comment]
What is wrong with the range index tests @adamretter ?
`xqts.org.exist-db.xquery.range.test.contains-string` for instance

**Comment by joewiz** [comment]
@adamretter Both Travis and AppVeyor failed. Should these be restarted, or is there a known problem with the PR?

**Comment by adamretter** [comment]
@joewiz From the Travis log it looks like there are a lot of failing tests related to Range Indexes now.

**Comment by joewiz** [comment]
Tests may be fixed by #3605; rebase and test after it's merged.

**Comment by joewiz** [comment]
@adamretter Do you think it would be possible to relax the 4th parameter of `util:eval-with-context` to be `$context as item()?` instead of `node()?`? This would allow the counterpart of the following query:

```xquery
xquery version "3.1";

declare context item := [1, 2, 3];

array:size(.)
```

... which returns `3`, to be accomplished dynamically using `util:eval-with-context()`:

```xquery
xquery version "3.1";

util:eval-with-context(array:size(.), (), false(), [1, 2, 3])
```

... which currently raises the error:

> err:XPDY0002 Nothing to select [at line 3, column 35]

Line 3 column 35 resolves to the `.` inside of `array:size(.)`.

This change would bring parity between this function and the [context item declaration](https://www.w3.org/TR/xquery-31/#id-context-item-declarations). It would open up the possibility of setting the context dynamically in xqsuite tests. For example, at the moment it's not possible to adapt my suggested test for @dizzzz's PR https://github.com/eXist-db/exist/pull/3644#issuecomment-736877075 to xqsuite due to the `node()` restriction. Relaxing it and allowing `item()` would allow Dannes to add this test to his PR.

**Comment by adamretter** [comment]
> Do you think it would be possible to relax the 4th parameter of util:eval-with-context to be $context as item()? instead of node()?

@joewiz The 4th parameter is `$eval-context-item` not `$context`. Also, the `$eval-context-item` parameter is already an `item()?`. Did you mean the 4th parameter?

> `util:eval-with-context('array:size(.)', (), false(), [1, 2, 3])`

That query currently evaluates to `1`. Likely because the context item has to be a Sequence, and so we end up with `([1,2,3])`.

**Comment by joewiz** [comment]
@adamretter I'm terribly sorry for the muddled question. Let me start over, because I agree that what I wrote above was quite unclear. Here is my observation:

Building a fresh checkout of the PR's branch, the following sample queries all return the error `err:XPDY0002 Nothing to select`—with the location of the error pointing to the `.` in the expression supplied in the 1st parameter. This error message originates from https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/xquery/ContextItemExpression.java#L50-L52, which suggests that `util:eval-with-context()` is not setting a context item (or a context sequence), despite the 4th parameter in all cases clearly being a valid item that conforms to the function signature's type declaration, `item()?`. 

- `util:eval-with-context(., (), false(), <x/>)`
- `util:eval-with-context(., (), false(), document { <x/> })`
- `util:eval-with-context(count(.), (), false(), (1, 2, 3))`
- `util:eval-with-context('array:size(.)', (), false(), [1, 2, 3])`
- `util:eval-with-context(.?foo, (), false(), map { "foo": "bar" })`
- `util:eval-with-context(., (), false(), ())`

According to my understanding, instead of raising this error, these expressions should produce the identical result as if the context item declaration was used to set the context item. For example, adapting the 1st example above:

```xquery
xquery version "3.1";

declare context item := <x/>; 

.
```

This query returns the expected result, `<x/>`. But `util:eval-with-context(., (), false(), <x/>)` raises the `Nothing to select` error.

**Comment by joewiz** [comment]
Oh my, I just realized my error. I was supplying an expression in the 1st parameter instead of a string! 

Sorry for the noise @adamretter!

**Comment by adamretter** [comment]
@joewiz Okay... so all is okay now?

**Review by joewiz — APPROVED** [review]
@adamretter Yes!

**Comment by joewiz** [comment]
@adamretter I see this PR is marked "Draft" - are there still other changes you plan? I see that CI tests all pass.

**Comment by adamretter** [comment]
@joewiz It was only draft whilst I was waiting for other PRs to be merged first. So yes, I think it is now good to go.

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
