### PR TITLE
Revert "Bump junit-vintage-engine from 5.8.1 to 5.8.2"

### PR DESCRIPTION
**Pull request by line-o**
This reverts commit 8a84a9d2b1716bcee0ef2ab09da2ac32396eb975.

### CODE REVIEW

**Comment by line-o** [comment]
The above commit just triggered Intellij IDEA to no longer recognise junit-vintage-engine as a dependency.
There seems to be some deeper issue.

**Comment by line-o** [comment]
If this PR is applied Intellij IDEA CE stops complaining here in exist-parent pom.xml

Screenshot 2021-12-02 at 12 48 41

**Comment by line-o** [comment]
@dizzzz The title is correct as the bump is reverted ;)

**Comment by dizzzz** [comment]
Hehehehe sorry

**Comment by line-o** [comment]
This was only due to an issue in Intellij

**Pull request closed without merging**
