### PR TITLE
Implement the HTML ASCII Case Insensitive Collation as defined in XPath F&O 3.1

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1585

@joewiz I am certainly no collation expert, however I think this likely solves it.

### CODE REVIEW

**Comment by joewiz** [comment]
@adamretter This PR passes all of relevant QT3 tests except these two from `fn-contains`:

```xml
   <test-case name="liam-contains-001" covers="html-ascii-case-insensitive">
      <description>Check for presence of HTML ascii case-insensitive collation</description>
      <created by="Liam Quin" on="2009-09-08"/>      
      <modified by="Michael Dyck" on="2014-09-11" change="parenthesize IfExpr's condition"/>
      <modified by="Josh Spiegel" on="2014-09-16" change="Added XP31+ dependency."/>
      <modified by="Michael Kay" on="2014-09-16" change="Added XQ31+ dependency."/>
      <dependency type="spec" value="XP31+ XQ31+"/>
      <test>if (fn:contains('iNPut', 'pu', 'http://www.w3.org/2005/xpath-functions/collation/html-ascii-case-insensitive')) then 'pass' else 'huh'</test>
      <result>
         <assert-string-value>pass</assert-string-value>
      </result>
   </test-case>
   <test-case name="liam-contains-002" covers="html-ascii-case-insensitive">
      <description>Check for presence of HTML ascii case-insensitive collation</description>
      <created by="Liam Quin" on="2009-09-08"/>      
      <modified by="Michael Dyck" on="2014-09-11" change="parenthesize IfExpr's condition"/>
      <modified by="Josh Spiegel" on="2014-09-16" change="Added XP31+ dependency."/>
      <modified by="Michael Kay" on="2014-09-16" change="Added XQ31+ dependency."/>
      <dependency type="spec" value="XP31+ XQ31+"/>
      <test>if (fn:contains('iNPut', 'PU', 'http://www.w3.org/2005/xpath-functions/collation/html-ascii-case-insensitive')) then 'pass' else 'huh'</test>
      <result>
         <assert-string-value>pass</assert-string-value>
      </result>
   </test-case>
```

eXist returns `huh` instead of `pass` for these two tests.

**Comment by adamretter** [comment]
@joewiz https://stackoverflow.com/questions/47022995/html-ascii-case-insensitive-icu-collator

**Comment by dizzzz** [comment]
what is the status of this PR ?

**Comment by joewiz** [comment]
@adamretter I'm not sure if this helps or not, but I checked how BaseX approaches this, and it appears they don't use UCA for this collator: 

- https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/util/collation/Collation.java#L23-L25
- https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/util/collation/NoCaseCollation.java

Their documentation backs this up - see http://docs.basex.org/wiki/XQuery_3.1#Collations:

> XQuery 3.1 provides a new default collation, which allows for a case-insensitive comparison of ASCII characters (A-Z = a-z)... 
>
> If the ICU Library is downloaded and added to the classpath, the full Unicode Collation Algorithm features get available in BaseX...

I read this as saying that case-insensitive ASCII comparison is available even if the ICU library isn't available.

**Comment by adamretter** [comment]
@dizzzz Still just chasing a final issue.

**Comment by adamretter** [comment]
@joewiz Indeed BaseX has its own simple implementation of a collator for this. However, I think for us it will be easier to use ICU4j if we can figure it out.

**Comment by ljo** [comment]
A bit delayed, but I am on it now.

**Comment by adamretter** [comment]
@ljo Any news please?

**Comment by ljo** [comment]
Just to let you know it almost there, was hoping for last night already, but hopefully running the last test round now.

**Comment by adamretter** [comment]
@dizzzz @ljo It seems I only needed the `asciiCollator.setStrength(Collator.PRIMARY);` bit. I have updated the PR.

@joewiz Hopefully this works for you now?

**Pull request merged**
