### PR TITLE
Switch from a very very old jEdit-syntax to RSytnaxTextArea

### PR DESCRIPTION
**Pull request by adamretter**
1. Fixes an issue with extended characters on Mac; Closes issue https://github.com/eXist-db/exist/issues/606

2. You get a much nicer editor; Copy and Paste seems to work again on the Mac amongst other things.

3. Better XML Syntax highlighting + code folding.

4. RSyntaxTextArea is current, maintained and supported.

### CODE REVIEW

**Comment by dizzzz** [comment]
Nice!!!!

**Comment by dizzzz** [comment]
We need to update the webstart side too....

**Comment by adamretter** [comment]
@dizzzz I don't know much about Webstart, can you take care of it?

**Comment by dizzzz** [comment]
@adamretter yes sure no problem

**Comment by dizzzz** [comment]
@adamretter ok, created a PR....

**Comment by adamretter** [comment]
@dizzzz yup, saw that thanks. Normally I'd be all over it, but I'm out for dinner this eve! If no one else gets to it first I will take a look AM, thanks :-)

**Comment by dizzzz** [comment]
Enjoy your dinner, the PR will not vaporise in a day :-)

**Pull request merged**
