### PR TITLE
move svn extension to https://github.com/shabanovd/eXist-svn

### PR DESCRIPTION
**Pull request by shabanovd**

### CODE REVIEW

**Comment by dizzzz** [comment]
you did not preserve the change history .... is that on purpose?

**Comment by shabanovd** [comment]
yes, because history stay here

**Comment by dizzzz** [comment]
I ask because maintaining history is not that difficult ....

**Comment by shabanovd** [comment]
no needs

**Comment by ljo** [comment]
OK. But then we could say the same about the geospatial index extension I upgraded and moved to an indexing app? That the history stays here that is.

**Pull request merged**
