### PR TITLE
Only compile aspects with AspectJ compiler

### PR DESCRIPTION
**Pull request by adamretter**
* Can now compile eXist Aspects successfully with Java 8

### CODE REVIEW

**Comment by shabanovd** [comment]
will this speed up compilation procedure in general?

**Comment by adamretter** [comment]
Yes this also removes the need to compile all Java classes with `javac` and `iajc`. I see a compilation speed up of ~50% here.

**Comment by shabanovd** [comment]
So, no problems, just speed up?

**Comment by dizzzz** [comment]
And.... we can use fully use features of java 8...

**Comment by dizzzz** [comment]
@adamretter that is right? now we can change build.properties?

**Comment by dizzzz** [comment]
@adamretter we need these changes in the netbeans scripts as well? https://github.com/eXist-db/exist/blob/1ed92e2c5423bd0e533645b0830daf8525cbe194/nbbuild.xml#L81  prepping on aspect there a few more script?  I realise there is some dead wood around https://github.com/eXist-db/exist/search?utf8=✓&q=aspectj

**Comment by adamretter** [comment]
@shabanovd No problems.

@dizzzz Yes you can use 1.8 in build.properties on a JDK 8 now. However, I am still working on moving us to JDK 8 properly, as there are 5 failing tests when you switch 1.7 for 1.8. That work is going on here - https://github.com/adamretter/exist/commits/j8. Regards NetBeans, I don't use it anymore, any change you still do, if so can you update that build script based on my change to `build-imp`l.xml?

**Comment by dizzzz** [comment]
Yes sure !

**Pull request merged**
