### PR TITLE
Cleanup/java api

### PR DESCRIPTION
**Pull request by shabanovd**
I'm preparing code base for new storage backend based on mapdb. Going to do round of small PR to cleanup java API. Mainly, I need to switch variables from implementation to interface.

### CODE REVIEW

**Comment by adamretter** [comment]
I am not happy with the final commit of `BrokerPool` -> `Database`. This has always been a mess since it was added, I don't want to see more incremental changes in this area because I am never seeing this work being finished and the mess just gets messier.

If you want to use an Interface to abstract BrokerPool, then that is fine by me, but I would like to see one pull request, where there is a commit that completely defines that interface, and one or more commits that completely replaces BrokerPool with Database throughout the *entire* code-base not justa  few files here and there. I would be happy to review such a pull-request.

Regards this pull-request, if you drop the last commit i.e. 22a8f01 then I will merge the rest of it.

**Comment by shabanovd** [comment]
I see two messages in your reply:
 - this PR can't be accepted because it continue something wasn't finish yet. So, I must not continue that! .... That's so cool @adamretter, should I point to your PR that just start something without finish?
 - this PR must be very complex because small one you will not review ... should I point to opposite comment on another PR that wasn't accepted because it was very complex???

I'm getting lost in "eXist rules" that change each day. Hope it'll stabilize soon.

**Comment by adamretter** [comment]
No not at all. I said if you want to continue something that is unfinished (which you started and stopped many times before) then send a complete pull-request that finishes it. To be clear, by "it" in this instance I mean creating an Interface for BrokerPool.

This is a good small pull-request and I have reviewed it. My main complaint with your one previous huge pull-request is that it was just a dump of many many different change topics, and I was not the only one complaining about that, in fact I don't recall anyone else apart from yourself thinking that was 100% fine.

You have my comments (above) and they are clear about how to proceed with this pull-request and also clear about how to proceed with the changes that you want to make. Also the required effort is minimal. I would rather work with you than against you, although I really do feel you are trolling me sometimes. If my comments above are unclear, please ask and I will try and clarify, otherwise I will assume that you know how to proceed.

**Comment by shabanovd** [comment]
should I close this PR?

**Comment by shabanovd** [comment]
I will not, so closing? ... think that PR to eXist become waste of my time -(

**Comment by adamretter** [comment]
@shabanovd Interesting that you should say that, as you often make me feel that way too.

If you want to do this in a constructive way perhaps you could tell me what it is that you don't agree with in my comments and why? Then we can look at and discuss...

**Comment by shabanovd** [comment]
I did code review for 3 areas: Schedule, Configurator and a bit of Security Manager ... @adamretter should I continue?

**Comment by wolfgangmm** [comment]
@shabanovd I assume this does not break compatibility for extension modules because the relevant methods of BrokerPool are still there? People finally started to update the various xars to prepare for the release. I don't want to put up further obstacles before the release.

**Comment by shabanovd** [comment]
@wolfgangmm yes, all methods stays. I follow strategy deprecated -> one release as minimum -> remove.

**Comment by shabanovd** [comment]
@adamretter where are we with this one?

**Comment by adamretter** [comment]
@shabanovd I took all your changes that were not either:
1. Related to the `Database` interface
2. Moving if statements into single lines
3. Adding a method `thing()` in addition to an existing `getThing()`
and merged them to *develop* here - https://github.com/eXist-db/exist/commit/f0ed6aa0e4c7299bfb1e752bc000b54bc28fc2e4

I am not against the Database interface refactoring, but as I said before I would like to see 1 PR that focuses on just that and makes changes to the entire code-base rather than just being piecemeal.

**Comment by shabanovd** [comment]
@adamretter so you create conflicts that I have to resolve manually during merge? ... no joy

**Comment by adamretter** [comment]
@shabanovd I suspect very few conflicts. I would have thought you would be happy that I spent 2 hours to review and merge your changes

**Comment by shabanovd** [comment]
@adamretter I'm not because you throw away 2 days of my work. This going to stay as memory for me to do not spend time for nothing.

**Comment by adamretter** [comment]
@shabanovd I am not sure what you expect? I suggested some changes to the pull-request and you said that you did not want to do them. I tried to help by merging the acceptable changes. I personally  think I have done the most that I can to try and help you get these changes into the code base!

**Comment by shabanovd** [comment]
@adamretter you can continue pick cherries of "acceptable changes" from my branches. That is most of what I can do!

**Pull request closed without merging**
