### PR TITLE
Fix the signing of core Jar files

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1475

### CODE REVIEW

**Comment by dizzzz** [comment]
I see that some echo's are removed that describe how to have the keystore file created. That might confuse some ppl, or.... are the instructions somewhere else these days?

**Comment by adamretter** [comment]
@dizzzz The instructions that I removed are obsolete. They don't hold true for quite some time

**Comment by dizzzz** [comment]
Are you sure? Not so long it worked fine and it was the easiest way to generate a keystore......

**Comment by dizzzz** [comment]
Ah I remember issues reported on exist-open ; somehow I thought these were fixed.

The solution is very easy: just add

```xml
<property file="${basedir}/build.properties" />
<property file="${basedir}/local.build.properties" />
```

to 'jarsigner.xml' and things work again

**Pull request merged**
