### PR TITLE
Make sure the context is preserved when dynamically compiling a query

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1583

### CODE REVIEW

**Comment by joewiz** [comment]
@adamretter Thank you so much! Do you think it's worth adding the test from #1583 to prevent future regressions?

**Comment by line-o** [comment]
@joewiz Since this is merged, it should go in a separate PR

**Comment by adamretter** [comment]
@joewiz yes that would seem sensible, I seem to have missed it. Could you send a PR for that please?

**Comment by joewiz** [comment]
@adamretter @line-o Sure, will do.

**Pull request merged**
