### PR TITLE
Update Homebrew release notes

### PR DESCRIPTION
**Pull request by joewiz**
### Description:

This PR updates the eXist release documentation with recent changes in Homebrew:

1. As of Homebrew 2.6.0:

    > All brew cask commands have been deprecated in favour of brew commands (with --cask) when necessary.

2. The old cask-repair utility is deprecated:

    > `cask-repair` is deprecated. I will accept PRs to fix bugs, but spending more time on it is difficult to justify. I recommend using `brew bump-cask-pr`. It doesn’t do as much in niche cases, but it does more in other slightly more relevant cases. It covers the vast majority os bump needs better. It ships in Homebrew, so there’s nothing to install. Do `brew bump-cask-pr --help` to see how to use it.

This switches our procedure to use the new, official `brew bump-cask-pr` utility recommended in the eXist CONTRIBUTING document.

### Reference:

1. https://brew.sh/2020/12/01/homebrew-2.6.0/
2. https://github.com/vitorgalvao/tiny-scripts/commit/09b68e4d83fa56e3a22f127f18f18f7816ccd548#diff-47b6313694b8a6f736f1a394498f41d0a0088b1ddf3277b1758d2bf7385e043f
3. https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md

### Type of tests:

n/a

### CODE REVIEW

**Comment by line-o** [comment]
Thanks for taking the time and updating the documentation.
Could you also add that to the pad were we track findings from the last release?
Otherwise I fear your additions might get lost.

**Comment by joewiz** [comment]
@line-o If you're proposing **storing** eXist release documentation outside of this file, I think this would need to be discussed first, i.e., at a community call.

**Comment by windauer** [comment]
@joewiz for sure the content of the pad should go into the release howto and there are no intentions that it leaves anywhere else. I guess Juri wanted to avoid bit more complex merging by asking you to put the content directly in the pad. But since @joewiz only touched the homebrew part and @line-o and me only other parts merging will be easy and I don't see any issues to merge this PR already! Ours is to come very soonish as well.

**Comment by joewiz** [comment]
@windauer Ah, ok. Perhaps it's best if you prepare your PR first, since your changes may be more global. I can rebase/adjust once yours is merged. No rush on getting this merged.

**Comment by line-o** [comment]
@joewiz  #3962 is the PR with the updated guide how-to release exist-db

**Comment by joewiz** [comment]
@line-o Great, thanks! I'll rebase this and mark it ready for review as soon as #3962 is merged.

**Comment by joewiz** [comment]
Closed by https://github.com/eXist-db/exist/pull/4141.

**Pull request closed without merging**
