### PR TITLE
Switch to NIO.2 for filesystem operations

### PR DESCRIPTION
**Pull request by adamretter**
Requires https://github.com/eXist-db/exist/pull/767!

Closes https://github.com/eXist-db/exist/issues/692

* File moves are now atomic.

* File copying and data copying is now handled directly by the JVM/OS.

* FileLock flush synchronisation is now guaranteed by the OS.

* Along the way I also found many Input and Output streams that were not closed or could be left open by an exception, these have been fixed.

### CODE REVIEW

**Comment by dizzzz** [comment]
In general it looks good, great cleanup of code. I saw one location where bytes were copied in a loop, as where I typically use 'IOUtils.copy()' or so ; quite a lot of changes, the WebUI is not responsive so I can find it anymore :-(

**Comment by dizzzz** [comment]
requires... it looks you merged the changes of #767 already into this commit?

**Comment by adamretter** [comment]
@dizzzz Not merged, just based. So when 767 is merged this will reflect that.

**Comment by ljo** [comment]
@adamretter Yes, very nice cleanup.

**Comment by dizzzz** [comment]
PR looks ok for me.

**Comment by adamretter** [comment]
@dizzzz Thanks

**Pull request merged**
