### PR TITLE
[Bugfix] Repair missing tmp dir TemporaryFileManager

### LINKED ISSUE #3826: [BUG] TemporaryFileManager should not rely on created directories in /tmp [linux]
For the second time my linux server (with no activity for weeks) stopped working (=dashboard showed up empty). When opening eXide with a direct URL, the following message is visible:

image

After restart the issue is gone. The trace is

```
2021-04-20 15:39:34,196 [qtp2094024223-135] ERROR (FilterInputStreamCacheFactory.java [instantiate]:94) - /tmp/exist-db-temp-file-manager-3709372318163436707/exist-db-temp-6085100929286095030.tmp
java.nio.file.NoSuchFileException: /tmp/exist-db-temp-file-manager-3709372318163436707/exist-db-temp-6085100929286095030.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:371) ~[?:?]
        at java.nio.file.Files.createFile(Files.java:648) ~[?:?]
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:137) ~[?:?]
        at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160) ~[?:?]
        at java.nio.file.Files.createTempFile(Files.java:868) ~[?:?]
        at org.exist.util.io.TemporaryFileManager.getTemporaryFile(TemporaryFileManager.java:113) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.exist.util.io.FileFilterInputStreamCache.<init>(FileFilterInputStreamCache.java:61) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.exist.util.io.FileFilterInputStreamCache.<init>(FileFilterInputStreamCache.java:55) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.exist.util.io.FilterInputStreamCacheFactory.instantiate(FilterInputStreamCacheFactory.java:87) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.exist.util.io.FilterInputStreamCacheFactory.getCacheInstance(FilterInputStreamCacheFactory.java:69) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.exist.xquery.value.BinaryValueFromInputStream.<init>(BinaryValueFromInputStream.java:54) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.exist.xquery.value.Base64BinaryDocument.<init>(Base64BinaryDocument.java:38) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.exist.xquery.value.Base64BinaryDocument.getInstance(Base64BinaryDocument.java:42) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.exist.xquery.modules.expathrepo.GetResource.eval(GetResource.java:74) ~[exist-expathrepo-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
```

it turns out that ` /tmp/exist-db-temp-file-manager-3709372318163436707/` does indeed NOT exist anymore. Manually creating the directory solved the issue, eXist-db is working again!

it turns out that ubuntu/rhel have a processes running that regularly cleans up the database:
- http://manpages.ubuntu.com/manpages/hirsute/en/man8/tmpreaper.8.html
- https://www.thegeekdiary.com/centos-rhel-67-why-the-files-in-tmp-directory-gets-deleted-periodically/

My preliminary conclusion is that the TemporaryFileManager should not rely on a directory that has been created in that class. 
The options:
- don't create a directory for eXist-db in /tmp
- check for the directory and create when the directory is missing when the mentioned method is invoked.

I prefer the 1st :-)

crashing code: [TemporaryFileManager ](https://github.com/eXist-db/exist/blob/5bc6a35fd6d4a91742637aefe4ad53c2324284ee/exist-core/src/main/java/org/exist/util/io/TemporaryFileManager.java#L113)

### PR DESCRIPTION
**Pull request by dizzzz**
Fixes #3826 

Appears to be a problem on Centos/REHL and Ubuntu.

### CODE REVIEW

**Review by line-o — APPROVED** [review]
LGTM. Thanks for the extra mile :)

**Comment by adamretter** [comment]
@dizzzz  Just a warning -  I can see there is another problem that you will experience that this PR doesn't solve. The TemporaryFileManager may be in the middle of using a temporary file whilst your OS cleanup task then deletes it. This will almost certainly cause a query to abort and could potentially corrupt the db (for example when storing a file and a temp file is used as scratch).

The solution is really to make the temp folder location configurable and move it outside of the folder where you are experiencing the problems with temp file cleaning.

**Comment by dizzzz** [comment]
Hi @adamretter I can not image that an OS can delete a file that is still open and used by a process. The issue solved here is that atleast for a server that is not being used for just more than a day (?) is converted into a un-usable server.

**Comment by dizzzz** [comment]
@adamretter , is it an idea to have (by default) the `-Djava.io.tmpdir=` set to a new directory `EXIST_HOME/tmp`  ? or does the system /tmp file have performance benefits?

**Comment by adamretter** [comment]
@dizzzz I am not sure that `-Djava.io.tmpdir` will affect all parts of eXist-db as it should.

> or does the system /tmp file have performance benefits?

Depends on your systems disks and mount points etc.

**Comment by dizzzz** [comment]
@adamretter despite this PR is not perfect in all theoretical aspects, but it is good enough for ppl to have a bit more stable environment out of the box?

**Comment by adamretter** [comment]
@dizzzz absolutely. It moves things forward

**Comment by dizzzz** [comment]
thnx @adamretter

**Pull request merged**
