### PR TITLE
Remove code which duplicates Commons IO

### PR DESCRIPTION
**Pull request by adamretter**
A very simple small change to remove a class which duplicates behaviour that is available in an already used dependency.

### CODE REVIEW

**Comment by dizzzz** [comment]
I remember to implement my own counter as the commons-io classes are doing a lot more under the hood, leading to overhead.

**Review by line-o — DISMISSED** [review]
LGTM

**Comment by adamretter** [comment]
@dizzzz Where do you see the overhead? I would think that reading the data from the database would far eclipse any overhead in the counting.

**Comment by dizzzz** [comment]
I tried te remember from my head; need to check :-)

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
