### PR TITLE
Fix docker builds

### LINKED ISSUE #4894: [BUG] docker `latest` tag hasn't been updated for 2 months
see https://github.com/moby/moby/issues/37965

we have considerable drift on CI because our apps are no longer tested against `develop` because of this.

### PR DESCRIPTION
**Pull request by duncdrum**
remove superfluous layers see experimental builds if it works

close #4894

### CODE REVIEW

**Comment by duncdrum** [comment]
build succeeds, container tests do too, push fails because this is from a PR from a fork, but attempt is visible.

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
@duncdrum @reinhapa ?

**Comment by adamretter** [comment]
If I am not mistaken, whilst this is interesting, it removes support for Apache FOP, and therefore we may not want to merge this. Is that correct?

**Comment by duncdrum** [comment]
> it removes support for Apache FOP
it does not the layers are superfluous not the deps

**Review by reinhapa — APPROVED** [review]

**Comment by adamretter** [comment]
> it does not. The layers are superfluous, not the deps

@duncdrum Sorry can you explain that please? In your PR here, it appears that you have commented out the dependencies that are required for Apache FOP - https://github.com/eXist-db/exist/pull/4895/files#diff-e06009c91b03b0212493cef67386d831bde8dc3729db1c33707e1f24458c1ad2R31

Am I mistaken... or are those lines not now commented out?

**Comment by duncdrum** [comment]
@adamretter the dependencies are part of the java base image, no need to create new layers via `COPY`

**Comment by adamretter** [comment]
@duncdrum So I think you are saying that the dependencies required for Apache FOP are available in `gcr.io/distroless/java17:latest` and so we don't need to copy them in from `debian:bullseye-slim`. Is that correct?

**Comment by duncdrum** [comment]
@adamretter yes

**Comment by adamretter** [comment]
@duncdrum Okay great. Thank you :-)

**Comment by adamretter** [comment]
@duncdrum I think you missed a file. The same changes will need to be made to `Dockerfile-DEBUG` too. Additionally can we just remove all the commented out stuff. There doesn't seem to be any value in leaving it there, no?

**Comment by duncdrum** [comment]
@adamretter i would wait to check the fallout from the default apps. We know that there are problems on develop, but as of now all our tests show green. Once we re back on solid footing we can delete things , clean up the docker Pom, and inline the experimental images

**Comment by duncdrum** [comment]
@reinhapa no the deploy for `:latest` is running again, which constitutes the hotfix. Once this had time to percolate, i ll do a cleanup PR, with outstanding cosmetic changes.

**Pull request merged**
