### PR TITLE
fn:replace and fn:analyze-string are now implemented with Saxon

### PR DESCRIPTION
**Pull request by adamretter**
In an attempt to fix some bugs with eXist-db's `fn:replace` and `fn:analyze-string`, these new versions just wrap the Saxon equivalents.

If people like this, we could also extend it to `fn:matches`.

### CODE REVIEW

**Comment by joewiz** [comment]
@adamretter Are the Saxon-specific flags now supported as well? (See https://www.saxonica.com/documentation9.5/functions/fn/matches.html.)

> Saxon implements some extensions to the flags argument. The value of this argument contains the standard flags defined in the spec (`i`, `m`, `s`, `x`, `q`) followed optionally by a semicolon and then Saxon-specific flags. The Saxon-specific flags are:
> 
> - `j` - Use the standard Java regular expression engine, allowing native regex syntax
> - `n` - Use the standard .NET regular expression engine, allowing native regex syntax
> - `g` - Switch on diagnostics
> - `k` - Treat unknown Unicode block names as matching any character (this is the default for XSD 1.1)
> - `K` - Treat unknown Unicode block names as an error (this is the default for XSD 1.0 and for XPath/XSLT/XQuery)

See discussion of this in Saxon and BaseX at https://github.com/eXist-db/exist/issues/846.

**Comment by joewiz** [comment]
+1 to the idea of extending your approach to `fn:matches`.

Do you by chance show any change in XQTS performance as a result of this PR?

**Comment by adamretter** [comment]
> Are the Saxon-specific flags now supported as well?

@joewiz yes I think so, but obviously not the .NET one ;-)

This work was actually done in March, but I forgot to backport it to eXist-db...

I haven't run the XQTS for this against eXist-db. I would welcome someone else trying it and posting results though...

**Review by dizzzz — CHANGES_REQUESTED** [review]
PR is not complete?


image

**Comment by adamretter** [comment]
@dizzzz Ah I think I screwed up the rebase a little... Should be fixed now I hope.

**Review by dizzzz — APPROVED** [review]
The drawback I see is that this is effectively a tighter integration with SAXON; here the external API can changed between versions...

(note: I tried to update to saxon10 without luck yet)

**Comment by adamretter** [comment]
@dizzzz That's correct. eXist-db would become more dependant on Saxon internal APIs. In FusionDB where we implemented fn:transform we already have such a dependency, perhaps eXist-db will in future too?

**Comment by dizzzz** [comment]
I very agree :-)

**Review by dizzzz — APPROVED** [review]

**Review by ljo — APPROVED** [review]
With the fixed rebase it looks good. The tighter dependency is of course something we need to note for coming strategic decisions.

**Review by wolfgangmm — APPROVED** [review]
Do we know which bugs this fixes? If so, it might be good to at least list them in the release notes, so users know in case they have relied on buggy behaviour. As far as I can see, `analyze-string` is used quite a lot.

**Comment by joewiz** [comment]
@adamretter I can confirm that with this PR, the [Saxon-specific `j` flag](https://www.saxonica.com/documentation9.5/functions/fn/matches.html) is indeed now supported. (I didn't really know how to test the other Saxon-specific flags; I just checked `j`.) For example, users could now use this approach to access the handy [`\b` regex metacharacter](https://www.regular-expressions.info/wordboundaries.html) for word boundaries, which isn't supported in standard XPath regex:

```xquery
analyze-string("foo bar", "\b", ";j")
```

Your idea to extend this PR to include `fn:matches` makes a lot of sense, since users might expect that from the example above, the following one should also work:

```xquery
matches("foo bar", "\b", ";j")
```

But, naturally, this variant currently fails with the following error:

> err:FORX0001 Invalid regular expression flag: ; 

Are you still open to extending this PR to include `fn:matches`?

**Comment by joewiz** [comment]
@adamretter I tried running XQTS but got this compilation error:

```

**Comment by dizzzz** [comment]
`FastByteArrayInputStream` has been replaced by the apache.org foundation alternative.

**Comment by dizzzz** [comment]
hopefully fixed with https://github.com/eXist-db/exist-xqts-runner/pull/10

**Comment by joewiz** [comment]
Thanks to @adamretter and @dizzzz, I have now been able to run XQTS on this PR's branch and on the develop branch. There were no differences in `fn:replace` tests, but there was a slight difference in `fn:analyze-string`:

**eXist 5.3.0-SNAPSHOT develop 8ff4383d6d19fe7a525b49702fa4aa515e4ef5aa** - 7 failures

> Screen Shot 2020-10-27 at 4 43 13 PM


**this PR** - 6 failures

> Screen Shot 2020-10-27 at 4 13 41 PM

Analyzing the test results, both branches fail identically on the same 6 tests (analyzeString-010, 009, 011, 015, 014, and 903), but this PR passes on one more test that the develop branch fails on: [analyzeString-017](https://github.com/w3c/qt3tests/blob/master/fn/analyze-string.xml#L210-L218). 

This test performs the expression:

```xquery
analyze-string("banana", "(b)(x?)")
```

eXist-develop returns the following incorrect result - with one nested group element instead of two sibling group elements:

```xml
<fn:analyze-string-result xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <fn:match>
        <fn:group nr="1">b<fn:group nr="2"/></fn:group>
    </fn:match>
    <fn:non-match>anana</fn:non-match>
</fn:analyze-string-result>
```

This PR returns the following correct result:

```xml
<fn:analyze-string-result xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <fn:match>
        <fn:group nr="1">b</fn:group>
        <fn:group nr="2"/>
    </fn:match>
    <fn:non-match>anana</fn:non-match>
</fn:analyze-string-result>
```

All in all, I would say this PR is net win: no regressions, improved XQTS results, and a new hook for accessing Java native regex.

It's possible some code depends on the buggy behavior, but I think if we state in the release notes that this PR results in eXist passing [analyzeString-017](https://github.com/w3c/qt3tests/blob/master/fn/analyze-string.xml#L210-L218), then developers upgrading their apps would be able to check their code accordingly.

As thrilled as I'd be to see this PR extended to `fn:matches`, I remembered that [our stance on making this function spec compliant](https://github.com/eXist-db/exist/issues/59#issuecomment-521397805) was that it would require a major release. One option to us, then, would be to (1) issue a deprecation notice now in this PR (bound for the next patch or minor release), that eXist's buggy handling of regex would go away in an upcoming major release. Then, if you were open to it, (2) open a PR tagged as 6.0.0, extending this PR to `fn:matches`. How does that sound?

**Comment by dizzzz** [comment]
For wolf's request regarding the release notes: should file a ticket for this? how to make sure that we document it?
Happy to pull-in  the PR.....

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
