### PR TITLE
Consistent License Declarations

### PR DESCRIPTION
**Pull request by adamretter**
eXist-db is licensed under the LGPL 2.1 license.

Prior to this PR, throughout the eXist-db code base there are may variations of the LGPL 2.1 license declaration text applied to each source code file. I encountered over 50 variations.

This PR standardises the declaration so that it is consistent. The text of the consistent declaration is:

```
eXist-db Open Source Native XML Database
Copyright (C) 2001 The eXist-db Authors

info@exist-db.org
http://www.exist-db.org

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
```

## Q&A
1. Why was the year `2001` used?
From my research it appears that assigning a copyright year in the past is relatively safe. Assigning one in the future is not. Ranges in copyright declarations are nonsensical as the date is meant to assert the start of the copyright period. eXist-db was created in 2001, and so using the consistent `2001` date makes sense. The alternative would be to maintain the date in every file individually, but that would be a maintenance nightmare, and likely one that we would often forget to do

2. How was the copyright name `The eXist-db Authors` chosen?
Previously we had a wide variety of copyright names used, including:
    1. eXist-db team 
    2. eXist-db Team
    3. The eXist-db team
    4. The eXist-db Team
    5. eXist team
    6. eXist Team
    7. The eXist team
    8. The eXist Team
    9. The above with team/Team replaced with project/Project.
   10. ...various others
We wanted a singular name, that describes that often a single source code file has many contributors, looking around at other projects it seemed that the form "The <project name> Authors" was often used.

3. How do I see the license problems?
Just run `mvn license:check`

4. How do we ensure this doesn't happen again in future?
Once we have fixed the licensing issues, we can set the `license-maven-plugin` to fail the build if code is modified/added without the correct license header.

## TODO
There are still some things to do to get the eXist-db licensing sorted out:

- [X] dbXML (now Xindice) licences in exist-core
- [X] Code copied from Saxon in exist-core without licenses
- [x] Code copied from Apache in exist-core without licenses
    Migrating changes/improvements to Apache Commons-IO project:
    - [X] https://github.com/apache/commons-io/pull/108
    - [X] https://github.com/apache/commons-io/pull/109
    - [X] https://github.com/apache/commons-io/pull/110
    - [X] New release of Commons-IO - https://github.com/eXist-db/exist/pull/3435
    - [x] https://github.com/apache/commons-io/pull/119
    Migrating changes/improvements to Apache Commons-Codec project:
    - [X] https://github.com/apache/commons-codec/pull/46
    - [X] New release of Commons-Codec - https://github.com/eXist-db/exist/pull/3517
- [X] Public Domain code in exist-core
- [X] @wolfgangmm's  explicit copyright on code that he originally authored in exist-core
- [X] Code copied from "Mort Bay Consulting (Australia) Pty. Ltd." (Jetty?) in exist-start
- [X] Code in `org.exist.repo` of exist-core is Copyright Florent Georges and is MPL 1.0 license
- [x] @adamretter's  explicit copyright on code that he originally authored which is not LGPL licensed

*NOTE:* I am trying to figure out if the dbXML license is even an Open Source license at all. If not... :-(

### CODE REVIEW

**Comment by adamretter** [comment]
The dbXML code in eXist-db has the dbXML 1.0 license.

The dbXML 1.0 license is actually just an Apache Software License, Version 1.1, with modified organisation details.

Apache Software License, Version 1.1, is ratified by OSI, so it is Open Source :-)

**Comment by joewiz** [comment]
Restarted the 1 failing Appveyor CI build.

@adamretter A conflict has emerged.

**Comment by adamretter** [comment]
@joewiz Okay thanks, I have resolved it now.

**Comment by dizzzz** [comment]
image

**Comment by dizzzz** [comment]
ok at least the checks continue
image

**Comment by dizzzz** [comment]
The 'Dockerfile' needs adjustments... but which? @adamretter

**Comment by adamretter** [comment]
@dizzzz Because of eXist-db's very complicated licensing, I was contributing to a new version of the license plugin, hence the 3.1-SNAPSHOT. I see that it has been released now as 4.0.rc1 and that you updated it, thanks :-)

**Comment by dizzzz** [comment]
I tried to add a valid license to the Dockerfile but on that part I failed :(

**Comment by adamretter** [comment]
@dizzzz what targets are you running?

**Comment by dizzzz** [comment]
-P docker  clean install

**Comment by adamretter** [comment]
@dizzzz If you enter the module directory e.g. cd `exist-docker`, you can then run `mvn license:check` you should get a list of any potential issues with licensing. That is the same goal that is run across the entire project in CI and during `package`.

If you want to try an automated fix, you can run `mvn license:format` within that module... just make sure to open up the changed files and manually check that the changes are correct before you commit them.

**Comment by adamretter** [comment]
@dizzzz it also just occurred to me that that Dockerfile is actually likely AGPL. As the original Docker for eXist-db that I created was AGPL.

**Comment by duncdrum** [comment]
All good with a switch to LGPL from my side

**Comment by dizzzz** [comment]
@adamretter the PR builds Ok right now!

**Comment by adamretter** [comment]
@dizzzz @joewiz This one is now ready to be merged

**Comment by joewiz** [comment]
The only CI failure is the usual openjdk14 on Travis. Since we have Dannes's approval, I'll merge.

**Pull request merged**
