### PR TITLE
(4.x.x) fix context sequence for higher order functions and sorting

### PR DESCRIPTION
**Pull request by tuurma**
### Description:
fix context sequence for higher order functions and sorting
result of a joint effort by @line-o @windauer @wolfgangmm @JoernT and @tuurma

Has been already approved in #2443 but redoing the PR since I followed incorrect procedure before

### Reference:
solves #1960

### Tests
relevant tests have been added with this PR

### CODE REVIEW

**Comment by tuurma** [comment]
develop and 5.0.0 ports are already provided by @windauer in #2447 and #2448

**Comment by adamretter** [comment]
Requires #2140 first

**Comment by tuurma** [comment]
@dizzzz can I ask you for a review? this is just a backport of ` PR you've approved already

**Comment by adamretter** [comment]
@tuurma  You have some merge conflicts and also #2140 is now merged. Could please rebase this on the develop HEAD? We can then look to get this PR merged.

Also I think we need a review/sign-off from @wolfgangmm on this one, as he developed the higher-order-function stuff. I am concerned that the change in this PR that `null`s the `contextsequence` is maybe a bit extreme and might break closures.

**Comment by line-o** [comment]
@adamretter nulling the context-sequence is spec compliant. It was @wolfgangmm who checked that at the time the fix was developed.

**Comment by dizzzz** [comment]
build fails...

```
    [junit] Running xquery.xquery3.XQuery3Tests
    [junit] Tests run: 337, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 12.228 sec
BUILD FAILED
/home/travis/build/eXist-db/exist/build/scripts/junit.xml:152: Test xquery.xquery3.XQuery3Tests failed
```

**Comment by adamretter** [comment]
@dizzzz Exactly why we needed #2142 merged first ;-)

**Pull request merged**
