### PR TITLE
Migrate to java11

### PR DESCRIPTION
**Pull request by dizzzz**
In an ambition to default to Java11 for eXist-db, changes are made in the build system.

According to @reinhapa  eg due to much more efficient String handling, performance could increase significantly.

this PR is (now) to test GHA.

Java8 tests are expected to fail.... or should not run at all?

### CODE REVIEW

**Review by reinhapa — APPROVED** [review]
LGTM

**Comment by dizzzz** [comment]
hmmm 
image

**Comment by line-o** [comment]
The test execution time on Linux is quite good compared to java8, no?

**Comment by duncdrum** [comment]
the docker JVM also needs to be switched to `J11` see the failing `tests images` steps

**Comment by dizzzz** [comment]
@dependabot rebase

**Comment by dizzzz** [comment]
@duncdrum  where needs that to be done?

**Comment by duncdrum** [comment]
@dizzzz I'm doing it like this https://github.com/duncdrum/distroless-exist/blob/25338457a7902fb34d0010417bf50613b662c0d2/Dockerfile#L24 but that wasn't desirable here, so you need to check back with @adamretter

**Comment by line-o** [comment]
@dizzzz I would favour you rebase on to current develop head instead of creating unnecessary merges.

**Comment by dizzzz** [comment]
@line-o I actually never rebase code :-( I think I don't even know how to do so; I think I was once asked to do this way, and... I remember that rebasing can have (for me) unclear side effects? Can you teach me other wise, and avoid/understand these unwanted side effects?

**Comment by line-o** [comment]
Sure! Screen share Monday before the community call?

**Comment by dizzzz** [comment]
yikes the following in exist-parent.xml is faking the build results: 
image

**Comment by dizzzz** [comment]
[patch.diff.txt](https://github.com/eXist-db/exist/files/9639473/patch.diff.txt)

**Comment by dizzzz** [comment]
hmmm errors with Java16 but the run looks OK :-( 
image

**Comment by line-o** [comment]
@dizzzz Just copying the docker file from @duncdrum did not seem to do the trick. The COPY operations refer to some folder `dump` that does not exist in our setup.

**Comment by reinhapa** [comment]
> hmmm errors with Java16 but the run looks OK :-( image

@dizzzz It seems the following JVM Flag needs to be added `--add-opens=java.base/java.lang.reflect=ALL-UNNAMED` in order to run properly in that test environment.

**Comment by line-o** [comment]
We should discuss the way we are going forward in light of #4574

**Comment by reinhapa** [comment]
@dizzzz seems as @adamretter has already started a draft for JDK 17 with Jetty 10 here: #4575

**Comment by line-o** [comment]
@reinhapa jetty 11 even

**Comment by reinhapa** [comment]
> We should discuss the way we are going forward in light of #4574

For me JDK 17 would also be a way to go...

**Comment by line-o** [comment]
I added this to next weeks agenda @reinhapa

**Pull request closed without merging**
