### PR TITLE
collectionsDb.remove must be write-locked

### PR DESCRIPTION
**Pull request by shabanovd**

### CODE REVIEW

**Comment by shabanovd** [comment]
@dizzzz tests passing if you did ask that

**Comment by dizzzz** [comment]
@shabanovd  yes.... (not only the travis ones... these are just a subset)

**Comment by shabanovd** [comment]
@dizzzz I use same subset only

**Comment by dizzzz** [comment]
@shabanovd not that this is a bit tricky, because there is quite some missing (though I do not know in detail what)

**Comment by adamretter** [comment]
@shabanovd Good spot!
But, could you add a test as well please?

**Comment by shabanovd** [comment]
@adamretter I have no idea how to do it. Please do, if you have know-how.

**Comment by dizzzz** [comment]
I'd have no idea

**Comment by adamretter** [comment]
@shabanovd @dizzzz This one is much harder to test. I have a new LockManager for eXist which I am using in Granite which traces such things and allows you to verify them, but I haven't yet provided it to eXist-db (I might do in future). For the moment, I guess this will be okay without a test, otherwise it will take you a huge amount of work

**Pull request merged**
