### PR TITLE
(4.x.x) Upgrade Xerces to latest version

### PR DESCRIPTION
**Pull request by dizzzz**
Update to latest xerces version (see [change log](http://xerces.apache.org/xerces2-j/releases.html))

# Contents:
- security updates
- performance improvements
- XML Schema 1.1 support

# XML Schema 1.1
Read more via
- http://www.datypic.com/services/xmlschema/new-in-1.1.pdf
- https://blogs.oracle.com/rammenon/xml-schema-11-ndash-what-you-need-to-know 
- http://www.datypic.com/books/defxmlschema/chapter14.html 
- https://blogs.sap.com/2018/03/31/xml-schema-1.1-assertions-in-cloud-integration/

# How to use
Adhoc validation using the [JAXV](https://docs.oracle.com/javase/10/docs/api/javax/xml/validation/package-summary.html) based xquery extension function
```xquery
validation:jaxv-report(<xml/>,<xsd/>,"http://www.w3.org/XML/XMLSchema/v1.1")
```

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz Can the `in progress` label now be removed?

**Comment by dizzzz** [comment]
@adamretter  if this looks OK for you, yes :-) I will sync the changes to the other branches tonight then

**Comment by duncdrum** [comment]
@dizzzz please add a note about schema1.1 support to [the docs](http://www.exist-db.org/exist/apps/doc/validation.xml?field=all&id=D3.3.2#D3.19.17)

**Comment by adamretter** [comment]
@dizzz would you be able to send a PR for a quick update to the docs as requested by @duncdrum ?

**Comment by dizzzz** [comment]
yes i will do.... not sure yet what to write....

**Comment by adamretter** [comment]
@dizzzz okay so we just need a `develop` port. Then we are good to land all 3 PR's

**Comment by dizzzz** [comment]
@adamretter wes I understand. I will contact you asap to have my clone on github cleaned...

**Pull request merged**
