### PR TITLE
updating info on legacy full text index

### PR DESCRIPTION
**Pull request by jensopetersen**
existing info is misleading

### CODE REVIEW

**Comment by joewiz** [comment]
The previous comment mentioned that there were still dependencies on the legacy full text index, and that the plan was to remove these so the old full text index could be removed. @wolfgangmm: is this already done? If so, can we remove this comment/entry altogether?

**Comment by adamretter** [comment]
@wolfgangmm I would be very happy to delete the old legacy full-text index... just say the word and the pull-request will be on the way.

**Comment by dizzzz** [comment]
Didnt we do this exercise on the 1.4 branch a long time ago? I recall it will be a tough job, deps are on many locations in the code.

Removal.... Is certainly a good idea but I fear for regression. To start with we should remove the &= like expressions in the grammar files? Then users can not use it at all anymore.

**Comment by adamretter** [comment]
@dizzzz I don't mind a tough job! Just let me know if I can go for it...

**Comment by dizzzz** [comment]
@adamretter I would certainly not mind, maybe I can help a bit. But... since there is a risk of instability in the core for some time, we need to be open on this improvement. @ljo @wolfgangmm  @shabanovd  ?

**Comment by jensopetersen** [comment]
Sure, it has to go eventually, but it doesn't do any harm leaving it as it is until after next release – there are quite a number of actual bugs waiting to be addressed.

**Comment by shabanovd** [comment]
I had remove old full text index for long time in my branch and it used in production without any issue around it, so I'm happy to help if/when agree to do so.

**Comment by shabanovd** [comment]
I recall that @wolfgangmm mention some sites that still depend on it.

**Comment by adamretter** [comment]
@jensopetersen Of course, but removing code often leads to less bugs to maintain ;-)

@shabanovd Let's wait and see what @wolfgangmm says then...

**Pull request closed without merging**
