### PR TITLE
[5.x.x] backport of encoding and file module fixes

### PR DESCRIPTION
**Pull request by line-o**
### Description:

Backport a number of fixes from develop regarding default encoding and file:sync.
This PR also adds and enhances file module tests. 

### Reference:

refs #4321
refs #4311
refs #4290

### Type of tests:

XQSuite tests

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]
rebase is needed

**Comment by adamretter** [comment]
@line-o Once this is rebased, we could merge this.

In future when creating a backport, can you do so as a 1-1 mapping between PRs please. i.e. if you want to backport a PR then create a single backport PR which contains only those changes and uses the same commit messages. Please do not mix multiple original PRs into a single backport PR.

This helps when we look back at the histories, so that we can clearly and easily compare the two branches and understand what was backported from where. Thanks

**Comment by line-o** [comment]
I can't follow.
What made a rebase necessary @dizzzz?
@adamretter this is exactly what I did cherry-picking each commit and  only modify those that needed manual changes.

**Comment by dizzzz** [comment]
image

**Comment by line-o** [comment]
Just to put that in writing, _later_ commits changed the codebase in the exact same places as this PR and those were merged first.

**Comment by line-o** [comment]
This PR allows edits. So interested parties can resolve that conflict. As I have no stake in this other than I wanted to help I will not devote more of my free time on this.

**Comment by dizzzz** [comment]
sorry to hear :-( it is just one file. somehow my git client failed working.... hmmm

**Comment by joewiz** [comment]
The many CI failures seem to be due to owasp:dependency-check-maven having hit its limit (I think).

**Comment by dizzzz** [comment]
I guess there is a cache issue here..... can we ignore this?

image

**Comment by dizzzz** [comment]
Two tests on windows fail....  not sure yet if it is PR related

image

**Comment by dizzzz** [comment]
image

**Pull request merged**
