### PR TITLE
[bugfix] Previously the docId comparison always returned true

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by dizzzz** [comment]
looks like an obvious fix to me, @wolfgangmm ?

**Comment by dizzzz** [comment]
hmm is this a true test error, @adamretter ?

```
BUILD FAILED
/home/travis/build/eXist-db/exist/build/scripts/junit.xml:124: Test org.exist.xquery.update.UpdateInsertTest failed
```

**Comment by adamretter** [comment]
@dizzzz @wolfgangmm Let me investigate that test failure. I can't see why this change should affect it, but maybe there is a bug elsewhere that depended on this bad behaviour...

**Comment by adamretter** [comment]
@dizzzz @wolfgangmm Okay I just pushed a fix. It was a simple NPE. Interestingly though a simple failure here can cause corruption of the database, we should probably try and make this more robust in the future...

**Comment by shabanovd** [comment]
will this PR conflict with https://github.com/eXist-db/exist/pull/1034 ?

**Comment by adamretter** [comment]
@shabanovd It is not in conflict. It contains the first same commit as https://github.com/eXist-db/exist/pull/1034

I couldn't continue to wait for this PR, so I got on with the next one. If you merge this one now, then https://github.com/eXist-db/exist/pull/1034 will merge just fine when it is ready.

**Pull request merged**
