### PR TITLE
define void-elements for HTML5 writer

### LINKED ISSUE #46: Empty tag "source" should be self-closing in HTML5
When serializing output as HTML5, the `<source>` tag is output with a separate closing tag, instead of being a self-closing tag -- it's an empty tag according to the specification:

http://www.w3.org/TR/html51/embedded-content-0.html#the-source-element

I think this is because the HTML5 serializer is a subclass of the XHTML serializer, and this uses a list of element names (emptyTags) to determine which tags should be output as self-closing tags, and "source" isn't on the list:

https://github.com/eXist-db/exist/blob/develop/src/org/exist/util/serializer/XHTMLWriter.java

Outputting `<source>` with a separate closing tag results in validation errors from the HTML5 validator.

### PR DESCRIPTION
**Pull request by shabanovd**
close #46

### CODE REVIEW

**Comment by dizzzz** [comment]
I think the PR is not complete?

**Comment by shabanovd** [comment]
why do you think so?

**Comment by dizzzz** [comment]
so.... just alone that I ask the question should trigger you :-)

so subclasses define a new `protected final static ObjectHashSet` which was already defined in the superclass. I am not sure if this is 'clean, clear and required' ....

**Comment by shabanovd** [comment]
the set are different, that's why new set created. I do not see how it can be related to your question of incompleteness ;-)

it's static, as I understand it, to make that set to be singleton

**Comment by dizzzz** [comment]
yes you are write ; it is the drawback of reviewing code in a mobile app

**Pull request merged**
