### PR TITLE
Fix Java 11 startup failure (4.x.x)

### PR DESCRIPTION
**Pull request by joewiz**
### Description:

A PR submitted to the appbundler project fixes the problem: https://bitbucket.org/infinitekind/appbundler/pull-requests/49/account-for-change-in-location-of-jdk/diff. I rebuilt appbundler with this fix and confirmed that the new jar allows eXist to start under Java 11.

### Reference:

Closes https://github.com/eXist-db/exist/issues/2171.

### Type of tests:

None available.

### CODE REVIEW

**Comment by adamretter** [comment]
@joewiz Good work Sir!

One thing - I think we should perhaps also update the `tools/appbundler/README.md`. Could you make the changes to reflect your Java version, date etc, and also perhpas add a note about applying that PR as a patch to the build (as it is not merged yet).

**Comment by joewiz** [comment]
@adamretter Good call, will do.

**Comment by joewiz** [comment]
@adamretter I was preparing my README when I realized that I built the appbundler jar under Java 11.  Here's what I was preparing to submit:

> This version of appbundler is taken from https://bitbucket.org/infinitekind/appbundler, which fixes a number of issues with the original appbundler from https://java.net/projects/appbundler. Infinitekind only provides the source, so the eXist-db project builds its own binary.
> 
> The current binary `lib/appbuilder-20181003.jar` was built by Joe Wicentowski on Oct 3, 2018 from https://bitbucket.org/infinitekind/appbundler/pull-requests/49/account-for-change-in-location-of-jdk/diff (a PR that fixes a critical bug in launching appbundler-based apps under Java 11 but hasn't been merged yet) using Oracle JDK 11+28 (appbuilder builds with `target="1.8"`) and Xcode 10.0 on macOS 10.14.

Should I recompile under Java 8, or should we trust this target=1.8 setting in ant? (Here's the place in the project's ant file that specifies target=1.8: https://bitbucket.org/infinitekind/appbundler/src/52e19c095b8d38284c27e82851f459a62316d871/build.xml#lines-42:60.)

**Comment by joewiz** [comment]
The appbundler PR has now been merged in (without changes), so I'd revise my readme:

> This version of appbundler is taken from https://bitbucket.org/infinitekind/appbundler (rev. dcd72b3). This project fixes a number of issues with the original appbundler, https://java.net/projects/appbundler.
> 
> Infinitekind only provides source code for appbundler, no releases, so the eXist-db project has to create its own build.
> 
> The current binary `lib/appbuilder-20181003.jar` was built by Joe Wicentowski on Oct 3, 2018 using rev. dcd72b3, Oracle JDK 11+28 (appbuilder builds with `target="1.8"`), and Xcode 10.0 on macOS 10.14.

Still, the only open question is whether I need to rebuild with Java 8, or whether a build with Java 11 (with the project's existing `target="1.8"` compilation script) is ok.

**Comment by joewiz** [comment]
Could someone from @eXist-db/core advise: Do I need to recompile the appbundler jar with Java 8, or will a build with Java 11 (with the project's existing target="1.8" compilation script) be ok? I'd be happy to recompile if that's safest.

**Comment by dizzzz** [comment]
To be sure, compile with java8 is the safest for java8 users

**Comment by dizzzz** [comment]
On the other hand: Travis shows that all java versions compile ok. I’d say no risk

**Comment by adamretter** [comment]
@joewiz yes it has to be built with Java 8.

@dizzzz whoever added the appbundler, did so without tests. So Travis won't matter here

**Comment by joewiz** [comment]
Ok, thanks, I've rebuilt the jar with java 8, updated the readme, and rebased all 3 commits. 

Assuming CI tests pass, I would propose a hotfix release to allow eXist to function with Java 11.

**Comment by joewiz** [comment]
Looks like 3 appveyor environments passed in ~30min, but one failed because it hit the 1hr limit: https://ci.appveyor.com/project/AdamRetter/exist/builds/19310285/job/vee31d2bjtseyk56/messages.

**Comment by joewiz** [comment]
Travis CI has passed. Can we conclude that the timeout failure that affected one of the four appveyor tests was a quirk?

**Comment by joewiz** [comment]
Thanks, Adam and Dannes!

**Comment by duncdrum** [comment]
i can confirm running 4.5.0 with java 11 on macOS

**Pull request merged**
