### PR TITLE
[5.x.x] Ensure that EXPath packages installed in $EXIST_HOME/data/expathrepo are filesystem portable

### PR DESCRIPTION
**Pull request by adamretter**
Backport of https://github.com/eXist-db/exist/pull/4902

### CODE REVIEW

**Comment by reinhapa** [comment]
@adamretter seems there are some conflicts to be solved first...

**Comment by dizzzz** [comment]
image

**Review by dizzzz — CHANGES_REQUESTED** [review]
merge issues

**Comment by adamretter** [comment]
@dizzzz @reinhapa It was simply that I opened the PR accidentally against `develop` instead of `develop-5.x.x`. I have now corrected cted that.

**Comment by adamretter** [comment]
@dizzzz @reinhapa is this now ready to merge please?

**Review by reinhapa — APPROVED** [review]

**Comment by adamretter** [comment]
@dizzzz Would you be able to review this one please?

**Review by dizzzz — APPROVED** [review]

**Comment by adamretter** [comment]
Thanks @dizzzz

**Pull request merged**
