### PR TITLE
(5.0.0) Basic support for available text resources of Dynamic Context

### PR DESCRIPTION
**Pull request by adamretter**
Backport of https://github.com/eXist-db/exist/pull/1994

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz I have fixed that now.

**Comment by dizzzz** [comment]
@adamretter any idea on the test issues?

```
    [junit] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
    [junit] Running org.exist.collections.triggers.TriggerConfigTest
    [junit] Tests run: 12, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 5.011 sec
BUILD FAILED
/home/travis/build/eXist-db/exist/build/scripts/junit.xml:153: Test org.exist.collections.triggers.TriggerConfigTest failed
```

**Comment by adamretter** [comment]
Rebased - let's see how the CI goes

**Comment by dizzzz** [comment]
aaargh:

```
    [junit] Running org.exist.xquery.modules.sql.ExecuteFunctionTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.516 sec
    [junit] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
    [junit] Running org.exist.xquery.update.IndexIntegrationTest
    [junit] Using temporary storage location: /tmp/org.exist.test.ExistEmbeddedServer2539211178458792981
    [junit] Tests run: 3, Failures: 1, Errors: 4, Skipped: 0, Time elapsed: 6.853 sec
BUILD FAILED
/home/travis/build/eXist-db/exist/build/scripts/junit.xml:153: Test org.exist.xquery.update.IndexIntegrationTest failed
Total time: 14 minutes 17 seconds
```

**Comment by adamretter** [comment]
@dizzzz should be fixed now.

**Pull request merged**
