### PR TITLE
Various Improvements to tests

### PR DESCRIPTION
**Pull request by adamretter**
1. Execute tests in parallel where possible to reduce run-time of the test suite
2. Reinstate some tests which were previously `@Ignore` but now run ok
3. Fix a few tests

### CODE REVIEW

**Comment by dizzzz** [comment]
```
     [xslt] Loading stylesheet C:\projects\exist\tools\yajsw\wrapper-log4j.xsl
BUILD FAILED
C:\projects\exist\build\scripts\build-impl.xml:819: The following error occurred while executing this line:
C:\projects\exist\tools\yajsw\build.xml:77: javax.xml.transform.TransformerFactoryConfigurationError: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
	at javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:187)
	at javax.xml.transform.FactoryFinder.find(FactoryFinder.java:264)
	at javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:106)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:396)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:257)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:307)
```

**Comment by dizzzz** [comment]
With the recent PR this should be OK....

**Comment by adamretter** [comment]
@dizzzz that is fixed by the Windows build PR you just merged - https://github.com/eXist-db/exist/pull/1700

**Comment by adamretter** [comment]
Thanks @dizzzz :-)

**Pull request merged**
