### PR TITLE
Launcher jetty 9

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1063

### CODE REVIEW

**Comment by ljo** [comment]
@adamretter great that you added the possibility to do launcher debugging. Happy about this with the right jetty config sent. So @dizzzz just go if I should not do it.

**Comment by dizzzz** [comment]
thnx @adamretter for picking up this soo quickly!

**Comment by joewiz** [comment]
+1, thanks @adamretter! I can confirm that starting on "macOS" works via `java -jar start.jar`. Oddly, the method I was accustomed to using - `open start.jar` - no longer works. I wonder why?

**Comment by dizzzz** [comment]
@joewiz that is strange, but it looks a Mac thingy though. I'll check to night

**Comment by joewiz** [comment]
Similarly, double-clicking on start.jar, which used to work, no longer does. Thanks @dizzzz.

**Comment by dizzzz** [comment]
@joewiz but then... `java -jar start.jar` should fail as well ?

**Comment by adamretter** [comment]
@joewiz Both of those are local configuration specific to your Mac. For example when I run `open start.jar` it launches BetterZip and shows me the contents of the Jar, because that is how I configured the file type association on my Mac.

**Comment by joewiz** [comment]
`java -jar start.jar` does work: I see startup logging in my terminal window and in exist.log, and the launcher starts and is accessible via menu bar and confirmed by accessing database resources like the Dashboard. When I try to start via `open start.jar` or double-clicking start.jar in the Finder, the splash screen doesn't appear (as it used to), the taskbar icon doesn't appear (same), no console logging occurs, and the Dashboard is inaccessible. Here's what I see via each method:

```bash
$ open start.jar
$ ps aux | grep java
joe             59868   0.0  0.0  2434840    792 s001  S+   11:23AM   0:00.00 grep java
joe             59861   0.0  0.0        0      0   ??  Z    11:23AM   0:00.00 (java)
joe             59862   0.0  0.1  8285300  14024   ??  Ss   11:23AM   0:00.02 /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -jar /Users/joe/workspace/exist/start.jar
```

```bash
$ java -jar start.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java -Xmx1024m -Xms64m -Dfile.encoding=UTF-8 -Xdock:name="eXist-db" -Xdock:icon="icon.png" -Dapple.laf.useScreenMenuBar="true" -Dapple.awt.UIElement=true -Dexist.home="/Users/joe/workspace/exist" -Djava.endorsed.dirs="/Users/joe/workspace/exist/lib/endorsed" -jar start.jar org.exist.launcher.Launcher
starting 
started process 59766
Joes-Mac-mini:exist joe$ 13 Jul 2016 11:19:58,502 [Thread-4] INFO  (JettyStart.java [run]:136) - Configuring eXist from Optional[/Users/joe/workspace/exist/conf.xml] 
13 Jul 2016 11:19:58,503 [Thread-4] INFO  (JettyStart.java [run]:138) - Running with Java 1.8.0_92 [Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM) in /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre] 
13 Jul 2016 11:19:58,504 [Thread-4] INFO  (JettyStart.java [run]:145) - Running as user 'joe' 
13 Jul 2016 11:19:58,504 [Thread-4] INFO  (JettyStart.java [run]:146) - [eXist Home : /Users/joe/workspace/exist] 
13 Jul 2016 11:19:58,504 [Thread-4] INFO  (JettyStart.java [run]:147) - [eXist Version : 3.0.RC2] 
13 Jul 2016 11:19:58,505 [Thread-4] INFO  (JettyStart.java [run]:148) - [eXist Build : 20160713] 
13 Jul 2016 11:19:58,505 [Thread-4] INFO  (JettyStart.java [run]:149) - [Git commit : develop-e9e2f90] 
13 Jul 2016 11:19:58,505 [Thread-4] INFO  (JettyStart.java [run]:151) - [Operating System : Mac OS X 10.11.5 x86_64] 
13 Jul 2016 11:19:58,505 [Thread-4] INFO  (JettyStart.java [run]:152) - [log4j.configurationFile : file:///Users/joe/workspace/exist/log4j2.xml] 
13 Jul 2016 11:19:58,505 [Thread-4] INFO  (JettyStart.java [run]:153) - [jetty.home : /Users/joe/workspace/exist/tools/jetty] 
13 Jul 2016 11:19:58,506 [Thread-4] INFO  (JettyStart.java [run]:154) - [jetty.base : /Users/joe/workspace/exist/tools/jetty] 
13 Jul 2016 11:19:58,506 [Thread-4] INFO  (JettyStart.java [run]:155) - [jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/standard.enabled-jetty-configs] 
13 Jul 2016 11:19:59,830 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty.xml] 
13 Jul 2016 11:19:59,920 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-gzip.xml] 
13 Jul 2016 11:19:59,945 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-http.xml] 
13 Jul 2016 11:19:59,979 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-jaas.xml] 
13 Jul 2016 11:19:59,983 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-jmx.xml] 
13 Jul 2016 11:20:00,019 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-requestlog.xml] 
13 Jul 2016 11:20:00,030 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-ssl.xml] 
13 Jul 2016 11:20:00,039 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-ssl-context.xml] 
13 Jul 2016 11:20:00,054 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-https.xml] 
13 Jul 2016 11:20:00,059 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-deploy.xml] 
13 Jul 2016 11:20:00,078 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-plus.xml] 
13 Jul 2016 11:20:00,096 [Thread-4] INFO  (JettyStart.java [run]:193) - [loading jetty configuration : /Users/joe/workspace/exist/tools/jetty/etc/jetty-annotations.xml] 
13 Jul 2016 11:20:00,100 [Thread-4] INFO  (JettyStart.java [startJetty]:457) - [Starting jetty component : org.eclipse.jetty.server.Server] 
13 Jul 2016 11:20:00,100 [Thread-4] INFO  (JettyStart.java [lifeCycleStarting]:605) - Jetty server starting... 
13 Jul 2016 11:20:01,629 [Thread-4] INFO  (JettyStart.java [lifeCycleStarted]:614) - Jetty server started. 
13 Jul 2016 11:20:01,769 [Thread-4] WARN  (JettyStart.java [run]:244) - Could not find OpenID extension. OpenID will be disabled! 
13 Jul 2016 11:20:01,770 [Thread-4] WARN  (JettyStart.java [run]:251) - Could not find OAuthServlet extension. OAuth will be disabled! 
13 Jul 2016 11:20:01,772 [Thread-4] INFO  (JettyStart.java [run]:260) - ----------------------------------------------------- 
13 Jul 2016 11:20:01,772 [Thread-4] INFO  (JettyStart.java [run]:261) - Server has started, listening on: 
13 Jul 2016 11:20:01,773 [Thread-4] INFO  (JettyStart.java [run]:263) - 	http://10.20.4.103:8080/ 
13 Jul 2016 11:20:01,773 [Thread-4] INFO  (JettyStart.java [run]:263) - 	https://10.20.4.103:8443/ 
13 Jul 2016 11:20:01,773 [Thread-4] INFO  (JettyStart.java [run]:266) - Configured contexts: 
13 Jul 2016 11:20:01,773 [Thread-4] INFO  (JettyStart.java [run]:272) - 	/ 
13 Jul 2016 11:20:01,774 [Thread-4] INFO  (JettyStart.java [run]:272) - 	/exist 
13 Jul 2016 11:20:01,774 [Thread-4] INFO  (JettyStart.java [run]:310) - ----------------------------------------------------- 
```

(and, in a separate shell:)

```bash
$ ps aux | grep java
joe             59776   0.0  0.0  2434840    792 s001  S+   11:20AM   0:00.00 grep java
joe             59766   0.0  2.6  6888484 436112   ??  Ss   11:19AM   0:17.26 /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java -Xmx1024m -Xms64m -Dfile.encoding=UTF-8 -Xdock:name="eXist-db" -Xdock:icon="icon.png" -Dapple.laf.useScreenMenuBar="true" -Dapple.awt.UIElement=true -Dexist.home="/Users/joe/workspace/exist" -Djava.endorsed.dirs="/Users/joe/workspace/exist/lib/endorsed" -jar start.jar org.exist.launcher.Launcher
```

**Comment by joewiz** [comment]
@adamretter But by default .jar files are associated with "Jar Launcher (default) (15.0.1)". This is the case unless you manually associate the .jar extension with another app.

**Comment by adamretter** [comment]
@joewiz When you ran `open start.jar` it executed `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java` on your mac, so it seems to me that for some reason your mac wants to try and launch a Jar file as an Applet, which eXist is definitely not.

**Comment by joewiz** [comment]
@adamretter Interesting. I'll investigate.

**Comment by joewiz** [comment]
@adamretter A possibly related point: @windauer mentioned that, using the current head of the develop branch to build a .dmg installer for my team for use on macOS, the resulting .app file will not start on his Mac system. I noticed the same problem with the nightly .dmg that I retrieved from your site yesterday, which was dated July 6 (I didn't see any more recent builds when I checked yesterday). I wonder what troubleshooting info we could provide to help diagnose this?

**Comment by adamretter** [comment]
@joewiz I don't believe any of this is related to the Jetty 9 change. Can you open a new issue? although, if your using an LTS build for the DMG, you should open a support ticket with eXist Solutions.

**Comment by joewiz** [comment]
@adamretter This makes sense, given that I saw it on your July 6 build. Thanks!

**Comment by adamretter** [comment]
@joewiz I took a quick look regardless. To understand what is happening with the .app, one would need to turn off *System Integrity Protection* on their Mac, and then use dtrace/dtruss to trace `open eXist-db.app` and find out why it quits. I am not that keep to turn this off on the device I use for work every day ;-) Perhaps someone else has a spare Mac kicking around?

**Comment by joewiz** [comment]
@adamretter Interesting. I share your fear of disabling SIP, but perhaps that's the best way forward. Thanks for these tips.

**Comment by wolfgangmm** [comment]
I already had a look at this last Sunday and suspected it is related to the yajws native classes now being used to elevate permissions on windows. Somehow this seems to trigger an error on OSX. Switching back to a Java-only method of starting the process did in part fix the issue. Unfortunately I'm at a conference this week and could not dig further, but I'll continue on it once I'm back.

**Comment by adamretter** [comment]
@wolfgangmm Ah ha! Enjoy your conference....

**Comment by joewiz** [comment]
Interesting. s/yajws/yajsw. Assuming this change happened on May 18, when https://github.com/eXist-db/exist/pull/1016 was merged, I downloaded two nightlies to see whether this change resulted in the problem we're seeing. Indeed, the .app from the .dmg nightly of May 17 starts right up, whereas the May 19th version doesn't start.

I also see a difference between the process of the May 17th (158eaa3) and May 19th (50d037f) versions. Here's how each appears when I start them via start.jar (opening its application package and double-click directly on its start.jar):

**May 17:**

> $ ps aux | grep java
> joe              34956   0.2  2.8  7290824 467980   ??  S     5:06PM   0:18.43 /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Dwrapper.java.library.path=/Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/.tools/wrapper/ -Xms256m -Dfile.encoding=UTF-8 -Xmx1024m -Xdock:name=eXist-db -Xdock:icon=icon.png -Dapple.laf.useScreenMenuBar=true -Dapple.awt.UIElement=true -Dexist.home=/Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/. -Djava.endorsed.dirs=/Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/./lib/endorsed -jar /Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/./start.jar org.exist.launcher.Launcher

**May 19**

> $ ps aux | grep java
> joe              34935   0.0  0.1  8284660  17660   ??  Ss    5:03PM   0:00.02 /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -jar /Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/start.jar

When I swap the May 17th version out and put the May 19th version in its place, the startup command from the May 17th process output successfully starts the May 19th version:

> $ /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Dwrapper.java.library.path=/Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/.tools/wrapper/ -Xms256m -Dfile.encoding=UTF-8 -Xmx1024m -Xdock:name=eXist-db -Xdock:icon=icon.png -Dapple.laf.useScreenMenuBar=true -Dapple.awt.UIElement=true -Dexist.home=/Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/. -Djava.endorsed.dirs=/Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/./lib/endorsed -jar /Users/joe/Desktop/eXist-db.app/Contents/Resources/eXist-db/./start.jar org.exist.launcher.Launcher

This suggests that something about the changes in https://github.com/eXist-db/exist/pull/1016 resulted in the startup command or sequence not being well formed on macOS.

**Pull request merged**
