### PR TITLE
Separates the concerns of Transactions and Recovery

### PR DESCRIPTION
**Pull request by adamretter**
Until now if you set `<recovery enabled="no"...` in `conf.xml` then eXist would not start up, instead throwing a series of `NullPointerExceptions`.

This occurred because the use of `Txn` has become deeply embedded in eXist, however switching off recovery, would also disable the `TransactionManager` (i.e. set it to `null`).

This patch seperates the concerns of Transactions and Recovery. Enabling eXist still to work in terms of Transactions, yet just disabling the journal (and recovery of which) when recovery is disabled in `conf.xml`.

This PR includes a few pieces of cleanup to related classes, however the main aspect of the change is in the commits:

1. https://github.com/eXist-db/exist/pull/989/commits/5129f36266ec28cb1a59e3cd847b4f720ff77691
2. https://github.com/eXist-db/exist/pull/989/commits/6818ed5a041a7a6e9e85c036122a992ecf33bf8e

### CODE REVIEW

**Comment by dizzzz** [comment]
@wolfgangmm @ljo @shabanovd  ?

**Comment by wolfgangmm** [comment]
I tested the PR and did not see any negative effects. Seems ok to me.

**Comment by adamretter** [comment]
@wolfgangmm all good?

**Comment by wolfgangmm** [comment]
I'm struggling to get my usual stress tests running on latest develop due to some API changes. I will report once I succeeded.

**Comment by joewiz** [comment]
A minor typo in the issue title: s/Seperates/Separates.

**Comment by adamretter** [comment]
@joewiz Fixed!

**Comment by adamretter** [comment]
@wolfgangmm We had hoped you would open source your stress tests. Then we could help with such changes :-)

**Comment by wolfgangmm** [comment]
@adamretter In fact the best and most up to date stress test is currently the one against @joewiz https://history.state.gov site. The code for the entire site is available on github and builds automatically: https://github.com/HistoryAtState/hsg-project. jmeter tests based on real user traffic are here: https://github.com/joewiz/hsg-test/blob/master/src/test/jmeter/combined.jmx. That's basically what I'm testing against most of the time right now. It takes some time to set up, but any stress test which is worth to consider must contain a large amount of data and a representative set of user actions.

**Comment by adamretter** [comment]
@wolfgangmm any updates on this one?

**Comment by wolfgangmm** [comment]
I did not forget it and still have the branch running. I'll try to test it as soon as I can.

**Pull request merged**
