### PR TITLE
Update various libraries to the latest versions

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by shabanovd** [comment]
@joewiz is right, there was move operation, no replacement

**Comment by dizzzz** [comment]
either a bug in the GitHub or wrong jar files. Somehow I'd could not imagine the last :-)

**Comment by dizzzz** [comment]
the contents of the quartz jar:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.7.1
Created-By: Apache Maven Bundle Plugin
Bnd-LastModified: 1462989254619
Build-Jdk: 1.6.0_45
BuildInfo-Host: tc-perf-003.eur.ad.sag
BuildInfo-Revision: 2469
BuildInfo-Timestamp: 20160511-105333
BuildInfo-URL: http://svn-mirror.terracotta.eur.ad.sag/svn/quartz/tags
 /quartz-2.2.3
BuildInfo-User: jenkins-slave
Built-By: jenkins-slave
Bundle-Description: Enterprise Job Scheduler
Bundle-DocURL: http://www.terracotta.org
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion: 2
Bundle-Name: quartz
Bundle-RequiredExecutionEnvironment: JavaSE-1.6
Bundle-SymbolicName: org.quartz-scheduler.quartz
Bundle-Vendor: Terracotta, Inc.
Bundle-Version: 2.2.3
```

**Comment by dizzzz** [comment]
same for neko:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.8.4
Created-By: 1.7.0_65-b17 (Oracle Corporation)
Built-By: Andy Clark, Marc Guillemot

Name: org/cyberneko/html/
Specification-Title: Hyper-Text Markup Language (HTML)
Specification-Version: 4.01
Specification-Vendor: World Wide Web Consortium (W3C)
Implementation-Title: CyberNeko HTML Parser
Implementation-Version: 1.9.22
Implementation-Vendor: Andy Clark, Marc Guillemot
Implementation-URL: http://nekohtml.sourceforge.net/index.html
```

**Comment by dizzzz** [comment]
so I am convinced GitHub is wrong here, I'll pull in.

**Comment by adamretter** [comment]
@dizzzz @joewiz the problem is not GitHub, Git actually records it that way. I don't know why it does that sometimes, but it had always done it. This has been the case in many PRs in the past, however it doesn't seem to matter as the end result is correct.

**Comment by dizzzz** [comment]
From what I know..... git uses some heuristics to detect file moves/renames. If a file disappears on one location, and a new file appears on a different location, and the file is is x+% identical (think of move of java class from package to package), git can label the files as moved/renamed ; though we might actually have a new file.

(X=90%)

**Comment by joewiz** [comment]
Interesting! Good to know!

**Pull request merged**
