### PR TITLE
[bugfix] Update installer props which seem to be out of date

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by dizzzz** [comment]
looks safe to me, what happened on travis?

**Comment by adamretter** [comment]
@dizzzz I don't know, I restarted the build on Travis and it passed. Certainly my changes were not related as the failure was in `AllXqueryTests`

**Comment by dizzzz** [comment]
Yes I know :-/

**Comment by dizzzz** [comment]
post RC2

**Comment by shabanovd** [comment]
@dizzzz why? is it critical?

**Comment by dizzzz** [comment]
I thought I pulled it in ; yes it is important for the installer...

**Pull request merged**
