### PR TITLE
Remove annoying log statements

### PR DESCRIPTION
**Pull request by dizzzz**
Remove annoying log statements, at least when not debugging eXistdb

```
2015-10-14 21:27:25,204 [eXistThread-32] INFO  (EXistServlet.java [adjustPath]:164) -  In: /db/apps/eXide/modules/session.xql
2015-10-14 21:27:25,204 [eXistThread-32] INFO  (EXistServlet.java [adjustPath]:183) - Out: /db/apps/eXide/modules/session.xql
2015-10-14 21:27:31,418 [eXistThread-32] INFO  (EXistServlet.java [adjustPath]:164) -  In: /db/apps/eXide/modules/compile.xql
2015-10-14 21:27:31,418 [eXistThread-32] INFO  (EXistServlet.java [adjustPath]:183) - Out: /db/apps/eXide/modules/compile.xql
2015-10-14 21:27:31,440 [eXistThread-33] INFO  (EXistServlet.java [adjustPath]:164) -  In: /db/apps/eXide/modules/outline.xql
2015-10-14 21:27:31,440 [eXistThread-33] INFO  (EXistServlet.java [adjustPath]:183) - Out: /db/apps/eXide/modules/outline.xql
```

### CODE REVIEW

**Comment by ljo** [comment]
Is there a reason why you change only 1 of the 2 LOG.info() to LOG.debug() when enclosing them in  isDebugEnabled tests?

**Comment by dizzzz** [comment]
Nope.... Clearly overlooked :)

**Comment by dizzzz** [comment]
Fixed....

**Comment by adamretter** [comment]
Can you squash the two commits? Otherwise looks good

**Comment by dizzzz** [comment]
Can you give a hint how to do? Previous attempts failed horribly on be....

**Comment by adamretter** [comment]
Probably best to read a few articles like this - https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

It has a section on squashing commits. Make sure you have a backup first ;-)

**Comment by adamretter** [comment]
@dizzzz You don't need to close to squash the commits

**Comment by dizzzz** [comment]
@adam I think this PR will not appear again; it is too much work, how silly as it seems; I typically ruin my local clone,,, and then....

**Comment by dizzzz** [comment]
I give up

**Pull request closed without merging**
