### PR TITLE
Fix purging of old zip backups

### LINKED ISSUE #2387: BackupSystemTask is not limiting the backups as folders
### What is the problem
A backup job as below is not limiting the number of backups in case when suffix is not equal with ".zip
```xml
<job type="system" class="org.exist.storage.BackupSystemTask" cron-trigger="0 0 3 ? * * *">
        <parameter name="dir" value="/home/claudius/exist-db/backup" />
        <parameter name="prefix" value="full-backup-" />
        <parameter name="collection" value="/db" />
        <parameter name="user" value="admin" />
        <parameter name="password" value="password" />
        <parameter name="zip-files-max" value="2" />
</job>
```
### What did you expect
I would expect only two backups to be maintained.

### Describe how to reproduce or add a test
Anyone can reproduce this issue, by using the above backup job in conf.xml.

### Context information
- eXist-db 4.4.0 / ab5716180
- java version "1.8.0_191"
- ubuntu 18
- 64 bit
- How is eXist-db installed? - JAR installer

### PR DESCRIPTION
**Pull request by lingv-ro**
Closes #2387

### What is the problem
A backup job as below is not limiting the number of backups in case when suffix is not equal with ".zip
```xml
<job type="system" class="org.exist.storage.BackupSystemTask" cron-trigger="0 0 3 ? * * *">
        <parameter name="dir" value="/home/claudius/exist-db/backup" />
        <parameter name="prefix" value="full-backup-" />
        <parameter name="collection" value="/db" />
        <parameter name="user" value="admin" />
        <parameter name="password" value="password" />
        <parameter name="zip-files-max" value="2" />
</job>
```
### What did you expect
I would expect only two backups to be maintained.

### Describe how to reproduce or add a test
Anyone can reproduce this issue, by using the above backup job in conf.xml.

### Context information
- eXist-db 4.4.0 / ab5716180
- java version "1.8.0_191"
- ubuntu 18
- 64 bit
- How is eXist-db installed? - JAR installer

### CODE REVIEW

**Comment by joewiz** [comment]
@lingv-ro @claudius108 Could you please clarify what this PR is? Please provide a description in the body of the PR, ideally a completed issue template.

**Comment by claudius108** [comment]
What is the problem

A backup job as below is not limiting the number of backups in case when suffix is not equal with ".zip

<job type="system" class="org.exist.storage.BackupSystemTask" cron-trigger="0 0 3 ? * * *">
        <parameter name="dir" value="/home/claudius/exist-db/backup" />
        <parameter name="prefix" value="full-backup-" />
        <parameter name="collection" value="/db" />
        <parameter name="user" value="admin" />
        <parameter name="password" value="password" />
        <parameter name="zip-files-max" value="2" />
</job>

What did you expect

I would expect only two backups to be maintained.
Describe how to reproduce or add a test

Anyone can reproduce this issue, by using the above backup job in conf.xml.
Context information

    eXist-db 4.4.0 / ab5716180
    java version "1.8.0_191"
    ubuntu 18
    64 bit
    How is eXist-db installed? - JAR installer

**Comment by joewiz** [comment]
@claudius108 Thank you! I've moved the description up into the original post to make it easier for reviewers.

**Comment by duncdrum** [comment]
failing test fixed by #2606 feeling adventurous ...

**Pull request merged**
