### PR TITLE
[improvement] Improve invoking logger using log4j2 and slf4j templating

### PR DESCRIPTION
**Pull request by dizzzz**
Change logger string concatenation by correct log4j2 templating. Can improve performance.

Mechanically changed by feature of Intellij.

image

### CODE REVIEW

**Review by line-o — COMMENTED** [review]
There is a test that fails now because of a call to `Log.error`.

Also we might want to do something about the hundreds of warnings about illegal reflective access that are reported (`--illegal-access=warn`).

**Comment by line-o** [comment]
https://github.com/eXist-db/exist/pull/3830/checks?check_run_id=2400210987#step:6:9486

**Comment by dizzzz** [comment]
ah. mocking log calls. interesting :-)

**Comment by dizzzz** [comment]
PR is ready for review

**Review by joewiz — APPROVED** [review]

**Pull request merged**
