### PR TITLE
[4.x.x] Switch CI from Temurin to Liberica

### PR DESCRIPTION
**Pull request by adamretter**
Backport of https://github.com/eXist-db/exist/pull/5466

Liberica should still provide JDK 8 on macOS

### CODE REVIEW

**Review by dizzzz — COMMENTED** [review]
Interesting build error....

   [junit] 1407 [WARN] DefaultCacheManager: The cacheSize="256" setting in conf.xml is too large. Java has only 466432k available. Cache manager will not use more than 155477k to avoid memory issues which may lead to database corruptions.
Error: nit] 1704 [ERROR] PluginsManagerImpl: java.lang.ClassNotFoundException: org.exist.storage.md.MDStorageManager

**Comment by adamretter** [comment]
> WARN] DefaultCacheManager: The cacheSize="256" setting in conf.xml is too large. Java has only 466432k available. Cache manager will not use more than 155477k to avoid memory issues which may lead to database corruptions.

@dizzzz I think this one may be due to the limited amount of RAM available in CI and that we need not worry about it.

> Error: nit] 1704 [ERROR] PluginsManagerImpl: java.lang.ClassNotFoundException: org.exist.storage.md.MDStorageManager

@dizzzz I have appended a commit to change this from an Error into a Warning in the log.

**Comment by dizzzz** [comment]
@adamretter could it be that a 32bit VM is used?

**Comment by adamretter** [comment]
> @adamretter could it be that a 32bit VM is used?
> 

No. I don't think so

**Comment by adamretter** [comment]
@dizzzz @reinhapa I believe this is now ready to merge please?

**Comment by reinhapa** [comment]
@adamretter the windows build still fails...

**Review by reinhapa — APPROVED** [review]

**Comment by adamretter** [comment]
> the windows build still fails. Wilk this be resolve with the folllow up restore output change?
@reinhapa I didn't have the Ant script quite correct for passing the property to disable the journal recovery log output. I have fixed that now, and CI is all passing now :-)

**Pull request merged**
