### PR TITLE
fix build and NPE on master

### LINKED ISSUE #4911: [BUG] Building on `master` is broken
Building on the `master` branch is broken. 

To reproduce:

1. checkout `master` branch
2. run `mvn -q -DskipTests -Ddocker=false -Ddependency-check.skip=true -Dmac.signing=false -Dizpack-signing=false -Denv.CI=true -P '!mac-dmg-on-unix,!installer,!concurrency-stress-tests,!micro-benchmarks' clean package`
3. Result: 
```
[ERROR] Failed to execute goal ch.mfrey.maven.plugin:copy-maven-plugin:1.0.0:copy (autodeploy-expath-pkgs-for-appassembler) on project exist-distribution: Execution autodeploy-expath-pkgs-for-appassembler of goal ch.mfrey.maven.plugin:copy-maven-plugin:1.0.0:copy failed: A required class was missing while executing ch.mfrey.maven.plugin:copy-maven-plugin:1.0.0:copy: org/codehaus/plexus/util/FileUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>ch.mfrey.maven.plugin:copy-maven-plugin:1.0.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:~/.m2/repository/ch/mfrey/maven/plugin/copy-maven-plugin/1.0.0/copy-maven-plugin-1.0.0.jar
[ERROR] urls[1] = file:~/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : org.codehaus.plexus.util.FileUtils
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :exist-distribution
```

**What did you expect**
Build to succeed. Tested with multiple simpler  incantations of the build command, same behaviour is observable on CI. 

**Context**
 - os MacOS 13.3.1(a)
 - Ubuntu 22.04.2 (with Temurin 8)
 
 ```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /opt/homebrew/Cellar/maven/3.9.1/libexec
Java version: 1.8.0_372, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "13.3.1", arch: "aarch64", family: "mac"
```

### LINKED ISSUE #5273: [BUG] NPE thrown on frequent updates of an XML resource
### Description:

Frequent updates on any XML resource stored in the database will cause a NullPointerException when it hits the fragmentation limit.

```xquery
update replace $stored-node with $new-node
```

This will result in

1. the document effectively being removed from the database
2. the data of that document to be no longer present in any configured index

### Reference:

Affected versions 6.1.0 and later (6.2.0, 6.3.0-SNAPSHOT, 7.0.0-SNAPSHOT)
Regression introduced in c553667

### Type of tests:

Evaluate following query

```xquery
xquery version "3.1";

(:sm:create-account("test", "test", "test"),:)
(:sm:create-group("test"),:)
xmldb:create-collection("/db", "test"),
sm:chgrp(xs:anyURI("/db/test"), "test"),
sm:chmod(xs:anyURI("/db/test"), "rwxrws---"),
xmldb:store("/db/test", "test.xml", <test><foo/></test>),
sm:chmod(xs:anyURI("/db/test/test.xml"), "rw-rw----"),
xmldb:create-collection("/db/apps", "test"),
sm:chmod(xs:anyURI("/db/apps/test"), "rwxrwxrwx"),
xmldb:store("/db/apps/test", "update.xql", "update replace doc('/db/test/test.xml')/test/foo with <foo updated='{util:system-time()}' />, doc('/db/test/test.xml')/test/foo", "application/xquery"),
sm:chown(xs:anyURI("/db/apps/test/update.xql"), "test"),
sm:chgrp(xs:anyURI("/db/apps/test/update.xql"), "test"),
sm:chmod(xs:anyURI("/db/apps/test/update.xql"), "rwxr-sr-x")
```

Then open `/exist/apps/test/update.xql` as guest

### PR DESCRIPTION
**Pull request by line-o**
### Description:

This PR is deliberately targeting the master branch and does two things:

1. it fixes the build of exist-db #4911
2. it fixes the NPE when an XML-resource is defragmented #5273

### Reference:

Backport of #5276
fixes #4911
fixes #5273

### Type of tests:

One jUnit test was added that forces defragmentation of a resource on first update to check if the process finishes and the update went through.

### CODE REVIEW

**Review by adamretter — COMMENTED** [review]
We never commit to `master` directly. As per the documented, master just points to the latest release commit. Please close this.

**Comment by dizzzz** [comment]
@adamretter please could you then indicate how this should be done?

It is in essence a hot fix for a defunc master

6.x release and then... cherry-pick to master?

**Comment by dizzzz** [comment]
We have no idea what is acceptable for you...

**Comment by dizzzz** [comment]
The NPE I agree on.... that is a bug-fix for the app;
The other is a build fix?

**Comment by line-o** [comment]
The only alternative that I see is that we create a release branch: `release-6.2.1`

**Comment by adamretter** [comment]
> please could you then indicate how this should be done?

Sure, it's in the documentation - https://github.com/eXist-db/exist/blob/develop/exist-versioning-release.md#release-process

> We have no idea what is acceptable for you...

I find that a bit of a strange comment... This is not at all about what is acceptable to me, it is about following the rules that we all reviewed, agreed to and documented. Those rules were created to make sure that we have a consistent, working, and repeatable process for doing the releases.

I recall that before we documented the process very few people knew how to do a release, doing so was very time consuming and difficult, and each one looked a bit different to the previous one.

This release process document has been in place since 2017 (or earlier?) and every release has followed those instructions since (https://github.com/eXist-db/exist/commits/develop/exist-versioning-release.md).

**Comment by adamretter** [comment]
> The only alternative that I see is that we create a release branch: release-6.2.1

If you follow the process you should not need to create a release branch, you can just tag the appropriate commit.

**Comment by dizzzz** [comment]
@adamretter 

> I find that a bit of a strange and jarring comment... 

That was not my intention, but clearly we (me) need some (more) guidance and would like to fix some long-time issues.

**Review by dizzzz — CHANGES_REQUESTED** [review]
based on feedback... we need to have an other route

**Comment by line-o** [comment]
@adamretter the document you refer to only mentions the develop branch which is not suitable to create a 6.2.1 as it contains a snapshot of version 7 and contains breaking changes.
There is no mention of the development branches for earlier versions. But as I already wrote develop-6.x.x does already contain quite a few changes and might therefore not be suitable either.
@dizzzz I will keep this open until we decided how to create a patch release

**Comment by line-o** [comment]
No longer needed.

**Pull request closed without merging**
