### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### eXist-db/exist now has a Chat Room on Gitter

@windauer has just created a chat room. You can visit it here: [https://gitter.im/eXist-db/exist](https://gitter.im/eXist-db/exist?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/eXist-db/exist?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by dizzzz** [comment]
Is this.... a shameless plug of a service?

**Comment by gitter-badger** [comment]
It is an automated pull request, and dont worry, badgers *do* feel shame.



:cry:

**Comment by dizzzz** [comment]
well I found it an interesting addition, but for many moments I thought it was created by, or commissioned for one our team members. In a way an automated PR is...... well anyway.

**Comment by adamretter** [comment]
Is this a good idea? I mean we have:
1. The mailing list
2. IRC
3. Stackoverflow
4. Twitter
5. GitHub issues

I seem to be the only one who responds to 3 and is reguarly on 2 and 4. Do we need yet another channel and if so could we shutter some of the other ones?

**Comment by dizzzz** [comment]
Well  do (3) often too but I am most of the time too late :-) 
At this moment (2) will be phased out probably, hence the PR.

**Comment by wolfgangmm** [comment]
I agree the goal should be to limit the number of communication channels rather than increase them. We were searching for a replacement for the various chats (jabber, hangout, skype ...) we are using for communication between us and eventually the old irc channel. gitter was one service Lars tested yesterday, but the fact that you need to have a github account to join rules it out somehow. I'll ask Lars to deactivate the created room.

**Comment by adamretter** [comment]
I think the existing 5 channels are fine. IRC is particuatly convenient for me as other projects I contribute to also use IRC. I would like to see others tracking the xquery and exist tags on stackoverflow though

**Comment by dizzzz** [comment]
For myself speakin, I follow s.o. for the tags meantioned.

I stopped using IRC for many reasons.......

**Pull request closed without merging**
