### PR TITLE
The content of comments should not be escaped

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/2728

### CODE REVIEW

**Comment by adamretter** [comment]
@duncdrum the problem with eXist-db/dashboard#88 is that you cannot have `--` inside a comment.

**Comment by duncdrum** [comment]
@adamretter and in joerns build he escaped the `—`  inside a comment which somehow gets expanded into an not well-formed xml inside exist

**Comment by dizzzz** [comment]
isn't there a 4.x port needed?

**Comment by adamretter** [comment]
@dizzzz I understood from last-weeks community call that 4.7.0 was meant to be the last in 4.x.x line?

**Comment by dizzzz** [comment]
make sense.... but maybe some bug fixes when it is really needed? (eg patch it in codebase so at least ppl can use it?)

**Pull request merged**
