### PR TITLE
XQueryURLRewrite challenge is now configurable

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1861

### CODE REVIEW

**Comment by duncdrum** [comment]
pls add a line about this feature to [the docs](http://www.exist-db.org/exist/apps/doc/production_good_practice.xml?field=all&id=D3.21.14#sect-attack-surface)

**Comment by joewiz** [comment]
@adamretter Should a test be included?

**Comment by adamretter** [comment]
@joewiz we don't have any infrastructure for testing such things (web.xml changes) sadly. Luckily the change is very very simple

**Comment by joewiz** [comment]
@adam I see! Thanks for letting me know.

**Pull request merged**
