### PR TITLE
Allow distinct Lucene Analyzers to be specified and then used during indexing vs. querying

### PR DESCRIPTION
**Pull request by sten1ee**
(based on https://github.com/eXist-db/exist/pull/2908)

In our usage of eXist, we're utilising a 'State of the art' LuceneAnalyzer for Sanskrit language developed by our colleagues from BDRC It has several modes of operation, but the one that we use - 'lenient mode' - requires one Analyzer to be used during the indexing phase, but then a different (or a differently configured) one to be used during querying.
Currently, eXist does not provide support for this use case, but this PR is aiming to achieve this feat.

### CODE REVIEW

**Comment by sten1ee** [comment]
As suggested by @wolfgangmm 
I started looking into the "Facets and Fields" documentation.
I understood some of it, and then decided to convert one of the TC that I've created for this PR to the 'new field paradigm'.
Started with the TC in ```extensions/indexes/lucene/src/test/xquery/lucene/analyzers.xml```
(see the first commit of this PR, lines 82-88)
I have created a field index named "line-again" and was querying it like that:
```<code>ft:query-field("line-again", "herzen")</code>```
according to the doc this line should be converted to that:
```<code>ft:query(. "line-again:herzen")</code>```
But that results in this failing:
```
org.exist.xquery.XPathException: java:org.exist.xquery.StaticXQueryException exerr:ERROR Error while evaluating expression: ft:query(. "line-again:herzen"). org.exist.xquery.XPathException: err:XPST0003 unexpected token: line-again:herzen [at line 1, column 12]
 [at line 146, column 27]. Error while evaluating expression: ft:query(. "line-again:herzen"). org.exist.xquery.XPathException: err:XPST0003 unexpected token: line-again:herzen [at line 1, column 12]
 [at line 146, column 27]
```

**Comment by sten1ee** [comment]
Small issue with the layout of a particular paragraph of the documentation;
It looks mis-layout in my browser (Version 76.0.3809.100 (Official Build) (64-bit) on MacOS 10.14.6):

image

**Comment by sten1ee** [comment]
Would someone please explain how come that (supposedly broken TC) passes:
https://github.com/eXist-db/exist/pull/2991/commits/4531d699fd3339b6a28dc1deac2eea794e1d9c8c
Note that I've removed the ```analyzer="line-again:index"```
from ```<text field="line-again" qname="l" analyzer="line-again:index"/>```
hence the default, StandardAnalyzer must be used both for indexing and querying.
How come it passes then?
And why if I replace 'herzen' with 'herzenn', I get this exception:
```
java.lang.IllegalStateException: Could not extract actual value

	at org.exist.test.runner.ExtTestFailureFunction.actualToString(ExtTestFailureFunction.java:116)
	at org.exist.test.runner.ExtTestFailureFunction.eval(ExtTestFailureFunction.java:72)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74)
	at org.exist.xquery.DynamicTypeCheck.eval(DynamicTypeCheck.java:61)
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:305)
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:223)
	...
```

**Comment by sten1ee** [comment]
First things first -- anyone having an idea why the JDK11 build on Windows fails?

**Comment by duncdrum** [comment]
yes windows cannot use multi-threading the same way as our linux builds, appveyor has a 50min timeout which our single-thread build is very close to, so this was a standard timeout. Nothing to worry about i restarted it.

**Comment by adamretter** [comment]
@duncdrum Windows uses multi-threading in the same way AFAIK. Our `appveyor.yml` still specifies - `-T 2C`

**Comment by duncdrum** [comment]
@adamretter i don't think it works the same, or why else are win builds consistently 20min longer than linux despite having 19 fewer test?

**Comment by adamretter** [comment]
@duncdrum different hardware, different virtualisation, and different OS ;-)

**Comment by duncdrum** [comment]
win will always be a mystery to me. @sten1ee all green

**Comment by sten1ee** [comment]
Now what?

Couple of months ago Wolfgang said (in a mail) to me:
_As I wrote in my comments here: https://github.com/eXist-db/exist/pull/2908, I consider ft:query-field to be deprecated in 5.x.x and would rather like to see a PR which is not limited to ft:query-field but more widely applicable. Do you think this would be possible?_

Yes, I think it is possible.
How to do it? -- It's a different question already.
Do I want to do it? -- Honestly? No.

I find it hard to even figure out the "What?" and "How?" part of it, without some adequate interaction/support.

So, let me backtrack a frame or two and ask this question:
Why deprecate ft:query-field in first place?
What's wrong with it?

**Comment by sten1ee** [comment]
@wolfgangmm, could you please respond to my post from 30 October.
As I need to move into direction of getting this feature "in".

**Comment by adamretter** [comment]
I think this looks good :-)

**Comment by adamretter** [comment]
Unless @wolfgang says otherwise, then I am happy to merge

**Comment by wolfgangmm** [comment]
I don't see tests using your approach with `ft:query` using fields. But ok, I'll try to add some today or tomorrow.

**Comment by sten1ee** [comment]
> I don't see tests using your approach with `ft:query` using fields. But ok, I'll try to add some today or tomorrow.

Adding some test would be great, thanks @wolfgangmm !
The PR is not finalised; (And in particular - there are no tests, as you note)
I wanted to get your critical review on the general approach, so I had the time to just push the commit and then had to run (no time for comment here).

Another thing that is missing is the actual implementation of `QueryOptions.getQueryAnalyzerId()`. Currently it returns plain `null` whereas it should take care to parse the relevant part of the options.
Let me make a design poll here:
As we were discussing this with @domlatham
I was thinking of the following xml format:
```xml
<options>
    <default-operator>and</default-operator>
    <!-- other options -->
    <query-analyzer-id>bo</query-analyzer-id>
</options>
```
while he proposed this instead: `<query-analyzer id='bo'/>`
I also find the later more succinct than the former.
But ... it goes against the general trend in the options format -- all other options are specified in the form `<opt-name> opt-value </opt-name>`. 
So - which one should be implemented, according to you?

**Comment by sten1ee** [comment]
I need to know: How to get the collection name (or path) that corresponds to given LuceneConfig ?

More detailed explanation: check out this code snippet:
```java
                analyzer = config.getAnalyzerById(opts.getQueryAnalyzerId());
                if (analyzer == null) {
                    String msg = String.format("getAnalyzerById(%s) returned null!", opts.getQueryAnalyzerId());
                    LOG.error(msg);
                }
```
It'd be much more informative, if the error message it logs in case no such analyzer is found, indicates the name of the collection, whose collection.xconf file contains the definition of this LuceneConfig

**Comment by sten1ee** [comment]
And one last thing: I think of reverting the initial change of this PR
as its approach is now obsolete:
```java
public Analyzer getAnalyzer(String field) {
    LuceneIndexConfig config = namedIndexes.get(field);
    String id = config != null ? config.getAnalyzerId() : null;
    if (id == null)
        return analyzers.getDefaultAnalyzer();

    final String indexSuffix = ":index";
    if (id.endsWith(indexSuffix)) {
        // Substitute <analyzer-id>:index with <analyzer-id>:query
        String qid = id.substring(0, id.length() - indexSuffix.length()) + ":query";
        Analyzer queryAnalyzer = analyzers.getAnalyzerById(qid);
        if (queryAnalyzer != null)
            return queryAnalyzer;

        LOG.warn(String.format("Failed to substitute %s with %s analyzer", id, qid));
    }
    return analyzers.getAnalyzerById(config.getAnalyzerId());
}
```

**Comment by sten1ee** [comment]
@adamretter, @wolfgangmm 
I've added TCs;
AppVeyor is failing the Java 8 build on Windows (for the usual reasons I guess).
Review and perhaps Merge?

**Comment by sten1ee** [comment]
@adamretter, @wolfgangmm: PING

**Comment by adamretter** [comment]
@sten1ee I am afraid that this stuff is really @wolfgangmm's domain

**Comment by sten1ee** [comment]
Happy New Year, everyone!
@adamretter and I am afraid @wolfgangmm is dead and/or gone

**Comment by adamretter** [comment]
@sten1ee I see this is on the Agenda for next Monday's community call. As far as I know @wolfgangmm is alive.

**Comment by sten1ee** [comment]
@adamretter, anything changed with regards to this PR?

**Comment by adamretter** [comment]
@sten1ee I don't know. I see that it was discussed at the call but I didn't attend. Perhaps @wolfgangmm @joewiz or @duncdrum who were present would be able to update you?

**Comment by line-o** [comment]
I am currently reviewing and experimenting with this feature and can confirm that it is:
- working
- and useful to solve real-life use-cases

I would like to add/change some of the tests. Would you want me to create a PR on your feature-branch, @sten1ee ?

**Comment by line-o** [comment]
Next up would be to document this properly. https://exist-db.org/exist/apps/doc/lucene seems to be the appropriate place to add a how-to covering one or two use-cases.

**Comment by sten1ee** [comment]
> I would like to add/change some of the tests. Would you want me to create a PR on your feature-branch, @sten1ee ?

@line-o: I don't mind

> Next up would be to document this properly. https://exist-db.org/exist/apps/doc/lucene seems to be the appropriate place to add a how-to covering one or two use-cases.

@line-o: would you volunteer to document this properly?
I am a bit out-of-the-loop right now; it's been almost 2 months since I finished working on that feature.

**Comment by line-o** [comment]
@sten1ee if you are OK with moving this to #3227, please close this one.

**Comment by sten1ee** [comment]
Post-close:
This is the docs PR for that feature:
https://github.com/eXist-db/documentation/pull/445

**Comment by sten1ee** [comment]
The corresponding [docs PR#445](https://github.com/eXist-db/documentation/pull/445) was approved and merged.
So nothing stands in the way of the [successor of this PR](https://github.com/eXist-db/exist/pull/3227)

**Pull request closed without merging**
