### PR TITLE
Improve module code quality

### PR DESCRIPTION
**Pull request by dizzzz**
Using Intellij for finding and fixing low hanging fruit

### CODE REVIEW

**Comment by dizzzz** [comment]
hmmm where is Travis ?

**Review by line-o — APPROVED** [review]
Looks good. Thanks for the cleansing :)

**Comment by line-o** [comment]
Yep, looks weird. Travis check is missing

**Comment by adamretter** [comment]
@dizzzz Would it be interesting to you to have access to SonarQube? I could add eXist-db to Evolved Binary's SonarQube instance if you like?

**Comment by dizzzz** [comment]
@adamretter yea that could be a good idea....

**Pull request merged**
