### PR TITLE
contentextraction: ContentReceiver is not abstract

### PR DESCRIPTION
**Pull request by RemiKoutcherawy**
extensions/contentextraction/src/org/exist/contentextraction/ContentRece
iver.java:48: error: ContentReceiver is not abstract and does not
override abstract method setCurrentNode(IStoredNode) in Receiver
[javac] public class ContentReceiver implements Receiver {
[javac]        ^
[javac] 1 error

### CODE REVIEW

**Comment by adamretter** [comment]
@RemiKoutcherawy Sorry but this looks like a bad pull-request, I think you need to rebase it still.

**Comment by dizzzz** [comment]
is the issue in v2.2 v3.0 ?

**Comment by adamretter** [comment]
I am not too sure about some of the changes in this, in particular the addition to `Receiver` of `setCurrentNode(IStoredNode<?>)`. I started trying to clean this up here - https://github.com/adamretter/exist/commits/731

We should at least take the fixes to the Eclipse project classpath (which I split into its own commit).

**Comment by dizzzz** [comment]
@adam i don;t understand ; in v3.0RCx the code compiles without problems, so no modifications are needed to fix things here,

there for my question to @RemiKoutcherawy : which exist version did you find this issue?

**Comment by adamretter** [comment]
@dizzzz The relevant commits of Remi are:

https://github.com/RemiKoutcherawy/exist/commit/db9fc7c600ecf6f4b511f0acae2e84bbf340fab9
https://github.com/RemiKoutcherawy/exist/commit/8a48da8f5e6d07a2b4fdf2a8e9c62013b89d0764
https://github.com/RemiKoutcherawy/exist/commit/8ceab2b299ef2fbb1d66d58076b433b8863813c8

**Comment by dizzzz** [comment]
so essentially..... the change is about 
(1) changing some eclipse project files  [some one should take ownership, or we should remove :-?; or we should generate these from intellij/netbeans files]  and 
(2) change our codebase to satisfy a bug in eclipse ?

**Comment by RemiKoutcherawy** [comment]
Hi
> so essentially..... the change is about 
> (2) change our codebase to satisfy a bug in eclipse ?
> 
Yes !

The bug was in Eclipse not supporting old syntax
I found the workaround there :
https://bugs.eclipse.org/bugs/show_bug.cgi?id=465339
I noticed the comment
" That's much more than a workaround, that's a step from pre-java-5 doom towards enlightenment :) "
and proposed you to change your codebase toward enlightenment !

BTW sorry for my bad pull requests, sometimes I cannot figure neither 
why the code does'nt compile, neither what it is supposed to do.

Rémi

**Comment by dizzzz** [comment]
@RemiKoutcherawy dont worry about the PR, git is sometime a bit difficult..

**Comment by dizzzz** [comment]
What to do with this PR? update of eclipse is ok (enough)?

**Comment by adamretter** [comment]
@dizzzz I highlighted the relevant commits. The rest is just cruft around bad merge/rebase. I am going to close this.

**Pull request closed without merging**
