### PR TITLE
make collections' and documents' id immutable

### PR DESCRIPTION
**Pull request by shabanovd**
That's step to collections no lock design.

### CODE REVIEW

**Comment by adamretter** [comment]
Without yet reading through the code, could you tell me how you deal with the 2^32 limit on document and collection ids. I am interested as this becomes more significant if document and collection ids are not recycled.

**Comment by shabanovd** [comment]
@adamretter why do you think that ids do not recycled?

**Comment by adamretter** [comment]
I was going on the title of the PR. If an ID is immutable, it cannot be recycled otherwise its reference is mutable.

**Comment by shabanovd** [comment]
@adamretter you confuse yourself ;-)
"immutable reference" called uniqueness and it was implemented by metadata storage. Id immutability is subject of [java object immutability](https://docs.oracle.com/javase/tutorial/essential/concurrency/imstrat.html).

**Comment by shabanovd** [comment]
@dizzzz if you do not create `BinaryDocument` directly then no needs for update. Search point that you have only one use at `org.exist.jms.replication.shared. MessageHelper`, right?

**Comment by dizzzz** [comment]
@shabanovd that is right indeed, in this code a document is received and stored as a binary document.  *if* this code needs to be updated, it would be a bad thing. More extension can rely on this api, the community cannot afford yet another 'in-ex-ternal' API change; that means that devs would need to support immediately two versions of eXist. Myself, I don't have the time for that.  In this case, the original interface API should remain for some time, marked deprecated.

Or do I misread?

**Comment by shabanovd** [comment]
@dizzzz are you saying that we should stop eXist improving because of 'in-ex-ternal' API change or I misread?

I did send already https://github.com/eXist-db/exist/pull/1324 and this PRs that removing lock-base design to non-blocking algorithm. And I did remove collection lock completely but I do not send it as one big PR because of complexity of that change. So, I split it into smaller change sets and send one by one for review.

_If_ I understand you comment above right you ask me to do not do that, right?

I have change that redesign store procedure from two passes strategy to single pass and that will break API for sure. Should I throw it out too because of 'in-ex-ternal' API change?

Do you have proposal for eXist improvement without 'in-ex-ternal' API change?

**Comment by dizzzz** [comment]
My concrete question is.... do I need to change code in my extension? If not, I am happy. I can't judge though .....

**Comment by dizzzz** [comment]
So am not asking you to stop any development or improvements! My question is quite simple, and again a forum/mail/.... seems to be a bad way of communicating :/

**Comment by shabanovd** [comment]
@dizzzz ok, let's discuss it on monday call

**Comment by dizzzz** [comment]
Please could you answer my question?

**Comment by shabanovd** [comment]
@dizzzz I did - `if you do not create BinaryDocument directly then no needs for update.`

**Pull request closed without merging**
