### PR TITLE
(4.x.x) Remove openjdk 9 and 10 from build

### PR DESCRIPTION
**Pull request by dizzzz**
Openjdk 9 and 10 are EOL, we will not make fixes specific for these versions.

Proposal: get rid of them

### CODE REVIEW

**Comment by dizzzz** [comment]
J12... well it all depends on if we plan to make any code changes for this coming 1-2 years ... at it is a release to stay shortly?

**Comment by duncdrum** [comment]
yes its not LTS, but I think we should be looking ahead to see where errors will occur down the line. Also sooner or later it will be the default Java on some distros (just like J10 did on some ubuntus), if exist breaks on those i d like to know about it.

**Comment by adamretter** [comment]
@duncdrum @dizzzz at present eXist-db does not compile on JDK 12, so that would have to be addressed first/separately.

**Comment by duncdrum** [comment]
@adamretter @dizzzz I think that we should stick with J9 & J10 until we are ready to replace them with J12 on Travis.  We could do that now and set the J12 jobs to be allowed to fail, or do the switch when we are ready to address J12 build problems.  If the more people want to get rid of J9 & J10, i ll go along, i don't feel strongly about this.

**Comment by dizzzz** [comment]
imo there is nothing wrong with saying 'no' to non LTS versions, as they are floating targets. The update frequency is (IMO) to high for serious business. 

But well if others say openjdk9/10 should be tested, i will accept :-) but I really dislike the overhead in travis.

**Pull request closed without merging**
