### PR TITLE
Merge RC branch

### PR DESCRIPTION
**Pull request by shabanovd**
Here changers that I made in year. That code in production minimal for 2 months.
 - latest metas storage;
 - lucene & ngram configuration java API;
 - chunk around match highlighter;
 - facet search java & xquery functions;
 - bugfixes.

PS Constructive comments are welcome -)

### CODE REVIEW

**Comment by adamretter** [comment]
@shabanovd Do you still plan to rebase this so we can look at merging it in?

**Comment by shabanovd** [comment]
On new year holidays I did spend 2 day to merge latest changers into my branch. And when work was almost done I got your mail "[HEADS-UP] Revert/Rebase", so I did stop.

I do not know when I'll have next free days for that. BTW, you can see that 2.2.0 was merged in.

**Comment by adamretter** [comment]
As you are not sure you will have any time and this has been waiting around for a very long time now. Would you be happy for me to pull this work apart and work each feature/bugfix in as a separate pull-request from a distinct branch?

**Comment by shabanovd** [comment]
"very long time now" not because of me!

**Comment by adamretter** [comment]
I am trying to help you here @shabanovd. I see you now closed this pull-request, can I assume that you now don't want any help with this then or that you no longer want to merge it? or perhaps closing it was a mistake?

**Comment by wolfgangmm** [comment]
I think there are some important bug fixes hidden in here, so if Adam wants to help by splitting it into smaller pull-requests, I think that's a solution, isn't it?

**Comment by shabanovd** [comment]
@adamretter, you did ask to close, no?

"Would you be happy for me to pull this work apart and work each feature/bugfix in as a separate pull-request from a distinct branch?"

**Comment by adamretter** [comment]
@shabanovd no I did not mean to close it. I meant that I would take it into a fork here and rework your commits into separate branches which would then produce small pull-requests which I have reviewed

**Comment by shabanovd** [comment]
@wolfgangmm, I have no idea how pull-requests can be spitted. Especially, after refactoring with package renaming and moving classes around. No ideas how to resolve that now.

**Comment by adamretter** [comment]
@shabanovd Okay, but I know how to do it... would you like me too?

**Comment by shabanovd** [comment]
@adamretter, you will not need that pull-request after that anyway.

**Comment by shabanovd** [comment]
@adamretter, you are welcome -)

**Pull request closed without merging**
