### PR TITLE
[6.x.x] Switch CI from Temurin to Liberica

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/pull/5304

Liberica should still provide JDK 8 on macOS

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]

**Comment by adamretter** [comment]
@dizzzz @reinhapa I believe this can be merged please... I think the [XQTS / W3C XQuery Test Suite (pull_request)] CI failure was already present before this change

**Review by reinhapa — APPROVED** [review]

**Comment by reinhapa** [comment]
@adamretter could you may take a look into the XQTS tests

**Comment by adamretter** [comment]
> could you may take a look into the XQTS tests

@reinhapa I think this might be 6.x.x specific? It says: `The action 'Run XQTS' has timed out after 60 minutes.` which means something locked up or failed to complete. I think this is fixed in 7.x.x isn't it? e.g. https://github.com/eXist-db/exist/actions/runs/11241881967/job/31254373997?pr=5480

**Comment by reinhapa** [comment]
Lets run the build again and see what the result will be...

**Pull request merged**
