### PR TITLE
[bugfix] Avoid IndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by dizzzz** [comment]
Is it so simple ? :=)

**Comment by adamretter** [comment]
@dizzzz Well that one is, there are still many many bugs in the Configurator, but that's a different story...

**Comment by dizzzz** [comment]
Good to have the exception gone !  At least we can see now some more potential issues:

```
2016-01-25 09:05:39,886 [WrapperListener_start_runner] ERROR (Configurator.java [configureByCurrent]:509) - Could not insert configured object
2016-01-25 09:05:39,886 [WrapperListener_start_runner] ERROR (Configurator.java [configureByCurrent]:556) - Field 'managers' must have '@org.exist.config.ann
otation.ConfigurationFieldClassMask' annotation [manager], skipping instance creation.
2016-01-25 09:05:39,892 [WrapperListener_start_runner] ERROR (Configurator.java [configureByCurrent]:509) - Could not insert configured object
2016-01-25 09:05:39,892 [WrapperListener_start_runner] ERROR (Configurator.java [configureByCurrent]:556) - Field 'managers' must have '@org.exist.config.ann
otation.ConfigurationFieldClassMask' annotation [manager], skipping instance creation.

```

**Comment by adamretter** [comment]
@dizzzz indeed although I think those errors are misleading and that the real error lies elsewhere

**Pull request merged**
