### PR TITLE
Remove betterForm and Update to latest Saxon

### PR DESCRIPTION
**Pull request by adamretter**
I can no longer maintain the old betterForm extension. I have updated it previously for the past two releases of Saxon.

However, having again tried to update it for the latest version of Saxon, I have not managed to do this after several days of expended effort. There are just too many changes!
I am no longer prepared to maintain the betterForm extension and without anyone else be willing to do so, I see our only option is to remove it.

This PR both removes the betterForm extension, and updates us to the latest version of Saxon.

Closes https://github.com/eXist-db/exist/issues/1682
Closes https://github.com/eXist-db/exist/issues/1586
Closes https://github.com/eXist-db/exist/issues/1352
Closes https://github.com/eXist-db/exist/issues/1335
Closes https://github.com/eXist-db/exist/issues/560

### CODE REVIEW

**Comment by dizzzz** [comment]
@JoernT can you elaborate on the future of betterForms? I "heard" rumours that there is some revision being done?

**Comment by JoernT** [comment]
@adamretter first of all big thanks for your efforts. I generally not opposed to removing it as i see the saxon dependency as a big burden. However we have to check internally cause there's at least one customer project still relying on it. I'll report back how we can go on. Same might be true for people from the community that might use it - so, at least we should ask the list before we take the final step as we have no replacement for it.

@dizzzz well, that are only rumors ;) We're lacking the budget to actually do that cause it will take *at least* 3 months of work to do that and we have no justification for such a big investment - haven't heard much about XForms users lately. If i do a rewrite one day it would hardly conform to the standard but just take the best parts of it and port them into todays' world.

**Comment by adamretter** [comment]
TODO - Add scripts to downgrade Saxon version and re-enable betterForm; as per-community call from 2017-03-12.

**Comment by JoernT** [comment]
@all just a reminder - when removing betterFORM we also need to migrate to the new existdb-dashboard, usermanager, packagemanager etc. as there will be no Dojo any more to run the old dashboard. I'm happy to assist necessary changes

**Pull request closed without merging**
