### PR TITLE
Remove document metadata indirection

### PR DESCRIPTION
**Pull request by adamretter**
I back-ported this improvement from FusionDB.

I previously removed the lazy-loading do Document metadata in eXist-db due to concurrency issues. However, the indirection between a persistent document and its metadata was left in-place.

This PR removes the indirection. This removes one object per Document object, resulting in a memory reduction for DocuemntImpl. It also reduces the function call indirection involved in looking up document metadata, resulting in a small-performance increase.

### CODE REVIEW

**Comment by dizzzz** [comment]
I will have a look, as it is a larger PR i need some time

**Comment by dizzzz** [comment]
in macOS, a deadlock is seems te be detected....

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CollectionLocksTest.stress_noDeadlock_writeWrite_subtree:554->stress_noDeadlock:690 Stress test likely showed a thread deadlock
```

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
@adamretter looks good
@line-o @joewiz @wolfgangmm  for this change I need to update the replication extension.

**Comment by adamretter** [comment]
@dizzzz regarding:
> Stress test likely showed a thread deadlock

macOS on Travis can be quite slow at times. Those tests have a timeout in them, whereby if the test does not complete before a timeout, then it assumes a deadlock has occurred and reports as such. This sometimes pops up on Travis form time to time, re-running the tests usually causes it to go away - you can now see all tests are passing ;-)

**Comment by dizzzz** [comment]
I restarted it already :/

**Comment by adamretter** [comment]
@dizzzz No problem - all is passing OK :-)

**Comment by wolfgangmm** [comment]
Needs wrapper `getMetadata` to go into 5. This method should be deprecated and then removed in 6.

**Comment by adamretter** [comment]
@wolfgangmm @dizzzz I just pushed a commit which makes this API compatible with the eXist-db 5.x.x series whilst not sacrificing memory use.

**Review by wolfgangmm — APPROVED** [review]
Looks ok to me now. @dizzzz do you want to check if your replication extension works with the  added wrapper?

**Comment by dizzzz** [comment]
On my way....

**Comment by dizzzz** [comment]
Looks good!

**Review by dizzzz — APPROVED** [review]

**Comment by adamretter** [comment]
@dizzzz @wolfgangmm thanks for the review and merge

**Comment by dizzzz** [comment]
As always

**Pull request merged**
