### PR TITLE
file:serialize() can not append to file

### PR DESCRIPTION
**Pull request by dizzzz**
Fixes https://github.com/eXist-db/exist/issues/1441 

Test case in issue report.

### CODE REVIEW

**Comment by dizzzz** [comment]
5 days no review no pull-in.... for this simple change :-(

**Comment by wolfgangmm** [comment]
@dizzzz Sorry, I have spent the entire week plus weekend on hunting memory leaks, which did not allow for anything else (including paid work).

**Comment by adamretter** [comment]
@dizzzzSorry I didn't think it was ready. As of your comments, I was waiting for the tests from the issue report to be added.

**Comment by dizzzz** [comment]
Ah ok :) no for me I considered it ready...

**Comment by joewiz** [comment]
From the telco: @dizzzz, we're just waiting for you to add the test, and @adamretter will happily merge.

**Comment by dizzzz** [comment]
updated the code.... I guess it could never have worked....

**Comment by adamretter** [comment]
@dizzzz thanks, can you also add an entry for your tests to `build/scripts/junit.xml`, probably just below:
```xml
<test fork="yes" name="xquery.modules.compression.CompressionTests" todir="${junit.reports.dat}"/>
```

**Comment by dizzzz** [comment]
Yes... I was looking for this :)
Regarding the write options... does this make sense? At least it works :)

**Pull request merged**
