### PR TITLE
[6.x.x] Refactor to highlight materialization query execution model

### PR DESCRIPTION
**Pull request by adamretter**
Backport of https://github.com/eXist-db/exist/pull/5079

### CODE REVIEW

**Review by reinhapa — APPROVED** [review]

**Review by dizzzz — APPROVED** [review]
see my remarks in other PR

**Comment by line-o** [comment]
I would like to understand why this change is necessary to be back ported to 6.x.x. @adamretter what does this add for users of 6.x.x?

**Comment by adamretter** [comment]
> what does this add for users of 6.x.x?
@line-o It adds exactly the same facilities as described in https://github.com/eXist-db/exist/pull/5079

**Comment by dizzzz** [comment]
IMO it is good to have 6 and 7 branch as equal as possible for the time being

**Comment by adamretter** [comment]
Thanks you @dizzzz :-)

**Pull request merged**
