### PR TITLE
Compare this XQTS run with previous XQTS run

### PR DESCRIPTION
**Pull request by adamretter**
Attempt at comparing results of previous XQTS run against this run.
See - https://github.com/eXist-db/exist/issues/3632

----
This open source contribution to the eXist-db project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

### CODE REVIEW

**Comment by line-o** [comment]
related #4707

**Comment by adamretter** [comment]
At present running the XQTS in GitHub Actions CI fails due to an `OutOfMemoryError`.

GitHub actions documentation [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) describes the following hardware options:

Hardware specification for Windows and Linux virtual machines:
* 2-core CPU (x86_64)
* 7 GB of RAM
* 14 GB of SSD space

Hardware specification for macOS virtual machines:
* 3-core CPU (x86_64)
* 14 GB of RAM
* 14 GB of SSD space

----

The https://github.com/eXist-db/exist-xqts-runner executes in a highly parallelised manner, this could cause a great deal of memory to be used during execution. Some next steps to investigate:

1. How much peak memory is used by the exist-xqts-runner to complete a run of the XQTS with eXist-db 6.1.0?
2. Is there an as yet unknown memory leak in the exist-xqts-runner and/or eXist-db itself?
3. Consider a configuration option to statically set the number of concurrent Actors in the exist-xqts-runner
4. Would a macOS instance that provides 2x the memory of a Linux instance be better suited for this?

----
The complete error from GitHub Actions CI is:
```
Error:  [SECURITY][01/31/2023 00:36:59.232] [XQTSRunnerSystem-akka.actor.default-dispatcher-439] [akka.actor.ActorSystemImpl(XQTSRunnerSystem)] Uncaught error from thread [XQTSRunnerSystem-akka.actor.default-dispatcher-439]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[XQTSRunnerSystem]
java.lang.OutOfMemoryError: Java heap space
	at java.math.BigInteger.valueOf(BigInteger.java:1109)
	at org.exist.xquery.value.IntegerValue.<init>(IntegerValue.java:85)
	at org.exist.xquery.value.IntegerValue.<init>(IntegerValue.java:80)
	at org.exist.xquery.RangeSequence$RangeSequenceIterator.nextItem(RangeSequence.java:89)
	at org.exist.xquery.Atomize.atomize(Atomize.java:85)
	at org.exist.xquery.GeneralComparison.genericCompare(GeneralComparison.java:577)
	at org.exist.xquery.GeneralComparison.genericCompare(GeneralComparison.java:521)
	at org.exist.xquery.GeneralComparison.eval(GeneralComparison.java:476)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:280)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:445)
```

**Comment by joewiz** [comment]
I get a lot of memory related errors (e.g., "GC overhead limit exceeded") when trying to run exist-xqts-runner with eXist 6.2.0-SNAPSHOT develop HEAD (changing exist-xqts-runner's built.sbt from 6.1.0 to 6.2.0-SNAPSHOT) on my 3.8 GHz 8-Core Intel Core i7, 40 GB RAM, macOS 13.2 system, running Adoptium Temurin 1.8.0_362-b09. Here's my console log: [exist-xqts-runner-output.txt](https://github.com/eXist-db/exist/files/10564586/exist-xqts-runner-output.txt).

**Comment by dizzzz** [comment]
@joewiz  did you set the G1C garbage collector?

**Comment by joewiz** [comment]
@dizzzz The command I ran was `sbt "run -x HEAD"` (i.e., as described in the README and help text). I would be happy to try another variation of the command, if you could suggest one?

**Comment by adamretter** [comment]
By limiting the maximum memory size for the JVM to 6GB and dumping the Heap on an `OutOfMemoryError`, we can see that a single XQuery Sequence containing some 53,459,536 `xs:integer` values accounts for almost all of the memory in-use.

As each `xs:integer` value in eXist-db uses 104 bytes of memory, we can see that `104 * 53,459,536 = ~5.3 GB`.

The trace seems to show a simple XQuery being executed from the XQTS that creates this large sequence of `xs:integer` values. The next question for me to answer is, which XQuery in the XQTS is generating such a large sequence...

Screenshot_select-area_20230314004711

**Comment by joewiz** [comment]
Wow... Could it be https://github.com/w3c/qt3tests/blob/master/fn/subsequence.xml#L810-L822 or https://github.com/w3c/qt3tests/blob/master/op/to.xml#L1195-L1202 - or thereabouts?

**Comment by adamretter** [comment]
@joewiz I added a temporary change to eXist-db to stop the processing of a query and print out the query if it detects it is trying to perform a General Comparison of two sequences, where one sequence exceeds 20,000 items.

The good news is that:
1. The XQTS Runner now completes (excluding the queries mentioned above) in CI in 5.75 minutes.
2. This has allowed me to identify 8 queries from the XQTS that will cause eXist-db to use a lot of memory and ultimately cause the exist-xqts-runner not to operate in CI.

The logs here https://github.com/eXist-db/exist/actions/runs/4427940077/jobs/7766290435?pr=4661 reveal the following queries:
1. *** Right sequence size is large at: 500004. Query is: `-1000000000000000000000 < -1000000000000000500003 to -1000000000000000000000`
2. *** Right sequence size is large at: 500000004. Query is: `1000000000000000020001 < 1000000000000000000000 to 1000000000000500000003`
3. *** Right sequence size is large at: 1000004. Query is: `100001000002 < 100000000000 to 100001000003`
4. *** Right sequence size is large at: 10000004. Query is: `1000000000000000020001 = 1000000000000000000000 to 1000000000000010000003`
5. *** Right sequence size is large at: 1000004. Query is: `100000000002 = 100000000000 to 100001000003`
6. *** Left sequence size is large at: 500000. Query is: `$result = 1`
7. *** Left sequence size is large at: 500000. Query is: `$result = 1`
8. *** Left sequence size is large at: 860302. Query is: `declare variable $p external := xs:untypedAtomic('860302'); (1 to xs:integer($p)) = $p`

The `$result = 1` queries can be deferred for later investigation as they are not the cause, instead they are just assertions executed in XQuery on the result of an original XQTS query.

By searching for the above queries in the XQTS we find the following test-set/test-case:
1. op-to/RangeExpr-411d
    `-1000000000000000000000 < -1000000000000000500003 to -1000000000000000000000`
2. opt-to/RangeExpr-409d
    `1000000000000000020001 < 1000000000000000000000 to 1000000000000500000003`
3. op-to/RangeExpr-408d
    `100001000002 < 100000000000 to 100001000003`
4. opt-to/RangeExpr-409c
    `1000000000000000020001 = 1000000000000000000000 to 1000000000000010000003`
5. opt-to/RangeExpr-408c
    `100000000002 = 100000000000 to 100001000003`
8. (8.) prod-GeneralComp.eq/GenCompEq-21
    `declare variable $p external := xs:untypedAtomic('860302'); (1 to xs:integer($p)) = $p`

----
There are two issues that I have identified:

1. eXist-db's `GeneralComparison#genericCompare(Sequence, Sequence, Item)` function is not suitable for processing large sequences. The function will attempt to atomize the lhs and rhs sequences before it processes them, in the worst case scenario this leads to the query requiring enough memory for 2 x lhs and 2 x rhs items!

2. Fundamentally at the core of the query processor in eXist-db each expression or function in eXist-db has an `eval` function that performs some computation. That function eagerly matreializes all results into a Sequence. There are a few exceptions to this, but in general that is the case throughout eXist-db. Unfortunately this design cannot scale when working with large numbers of items and finite amounts of memory. The previous generation of database systems instead used the Iterator/Volcano model to work around this, whilst eXist-db is still using the Materialization model. The latest generation of database systems use the Vectorized/Batch Model instead for better performance. For more details on these models and their pros/cons see - https://ethz.ch/content/dam/ethz/special-interest/infk/inst-cp/inst-cp-dam/education/courses/2020-fall/data-management-systems/slides/DMS-HS20-Query_Processing_Execution_Models.pdf#page=26

**Comment by adamretter** [comment]
I have excluded the following XQTS tests as a workaround to the eXist-db memory problems:
1. RangeExpr-411d
2. RangeExpr-409d
3. RangeExpr-408d
4. RangeExpr-409c
5. RangeExpr-408c
6. GenCompEq-21

**Comment by adamretter** [comment]
@joewiz I now have the comparisons working in CI as discussed. I think it is ready for final review.

**Comment by joewiz** [comment]
@adamretter The additional listing of the newly passing, skipping, failing, and erroring tests looks great! 

One minor issue. There appears to be a duplicate of the `cr:new` child elements - a `cr:pass` within the `cr:pass`, a `cr:skipped` within the `cr:skipped`, etc. 

And one question: I see the `cr:failures` and `cr:errors` to display the child nodes of the `testcase` element - showing the `failure` and `error` elements. Was this intentional? I can see the benefits of keeping them in. But in this report - an unusual case, to be sure - this leads the report to be 113k lines instead of 31k lines. In a normal PR these additional lines might provide ready reference to the new problems introduced in the PR. I was curious about your thoughts.

**Comment by adamretter** [comment]
> One minor issue. There appears to be a duplicate of the cr:new child elements - a cr:pass within the cr:pass, a cr:skipped within the cr:skipped, etc.

@joewiz Now fixed.

> And one question: I see the cr:failures and cr:errors to display the child nodes of the testcase element - showing the failure and error elements. Was this intentional? 

Absolutely. Those failures and errors give immediate feedback to the author of the PR that may be helpful. So as there is such a large factor of change the results here will be large for this PR, but typically we would expect them to be small in future PRs.

**Comment by adamretter** [comment]
@joewiz Are you happy to merge this now?

**Comment by joewiz** [comment]
@adamretter I'll be happy to do so once we get the **required 2nd approval**. I am generally hesitant to merge PRs in the eXist core, particularly when it involves Java. But this one doesn't, and I've reviewed it carefully, so as soon as we get the 2nd approval, that person or I can merge.

**Review by reinhapa — APPROVED** [review]

**Review by joewiz — APPROVED** [review]

**Pull request merged**
