### PR TITLE
Adopt FastUtil primitive maps

### PR DESCRIPTION
**Pull request by adamretter**
eXist's implementations have problems with hash-collisions and chaining.

### CODE REVIEW

**Comment by dizzzz** [comment]
nice.... 2 q's:
- what is "lib/core/fastutil-8.2.2-min.jar.md" about ... the contents is strange
- missing licence file ?

**Comment by wolfgangmm** [comment]
I was happy when we finally got fastutil removed. Need some testing before feeling well about reintroducing it.

**Comment by joewiz** [comment]
@dizzzz See https://github.com/eXist-db/exist/commit/649108f09570f07d4650714aa49b28d6cb826707.

**Comment by adamretter** [comment]
@joewiz @wolfgangmm that was 15 years ago!!! Fastutil has for sure moved on since then and is well maintained. It also doesn't have the collision bugs I discovered in eXist-db's

**Comment by adamretter** [comment]
@dizzz the md (markdown) file contains the details of how I produced a "min" jar from the official fastutils release... which is inline with the advice on the fastutils website

**Comment by wolfgangmm** [comment]
Yeah, it's a long time, but still doesn't hurt to be cautious. I remember it was a monster library back then. For my sanity I just need to be confident it has changed.

**Comment by adamretter** [comment]
@wolfgangmm sure the full library is 18mb. Which is why I used autojar as they suggest to just take what we need. Hence the "-min" postfix and ".md" file. Our min library is just 1.8mb

**Comment by wolfgangmm** [comment]
I quickly checked memory after restoring a larger backup on 4.x.x and develop. Nothing suspicious to be seen. I did not run stress tests yet, but if this PR is needed on the way to fix 5.0.0, I would agree to merge it.

**Pull request merged**
