### PR TITLE
[hotfix] repair appveyor build

### PR DESCRIPTION
**Pull request by dizzzz**
- upgrade Ubuntu
- remove docker part

### CODE REVIEW

**Review by duncdrum — APPROVED** [review]
The changes are harmless, but i don't know what it is we are running linux builds on appveyor for. If we want to use these runs and their result, we should run docker tests, if we don't I'd say ditch the builds from the matrix and safe us all 1h per PR waiting on sequential builds

**Comment by dizzzz** [comment]
at least the build is green, that saves me/us a few clicks every time

**Comment by dizzzz** [comment]
ditching is ok for me for sure, red marks are not :-)
for me I still trust the appveyor builds as GHA has red marks still

**Comment by adamretter** [comment]
@dizzzz Updating to newer Ubuntu is fine by me. Just wondering why you disabled building eXist-db's Docker Image?

**Comment by dizzzz** [comment]
@adamretter I disabled docker as this was the part that was giving build failures according to the logs.

**Comment by duncdrum** [comment]
@dizzzz that should only be a problem on `Java 11` if there are docker related failures on Java8 that would indicate a problem if we trust appveyor more then github actions

**Comment by dizzzz** [comment]
Hi, "should" is the theory but in practice java8 and Java11 failed. Hence my fix. I really checked it.

**Pull request merged**
