### PR TITLE
Tests for ft:get-field and ft:search

### PR DESCRIPTION
**Pull request by tuurma**
Provide tests for #2312

### CODE REVIEW

**Comment by duncdrum** [comment]
while test PRs are my personal exist-db catnip, I suggest waiting on #2140 before merging

**Comment by tuurma** [comment]
certainly, especially since there's no fix as yet, so these tests just cannot pass

**Comment by adamretter** [comment]
Could you rebase this on the HEAD of develop please?

**Comment by tuurma** [comment]
@adamretter these tests would not pass since the issue they expose is not fixed yet, shall they be marked as ignored or not merged yet?

**Comment by tuurma** [comment]
aargh sorry, now I messed it up with commits which don't belong here... trying to fix

**Comment by duncdrum** [comment]
@tuurma can you rebase this please

**Comment by adamretter** [comment]
@tuurma Can you tell us the status of this please?

To get it merged, it at least needs:
1. to be rebased
2. and we need the backports.

**Comment by adamretter** [comment]
@tuurma any updates please?

**Comment by adamretter** [comment]
@tuurma can you provide an update please?

**Comment by duncdrum** [comment]
@tuurma can you let us know about the state of this PR from your side please?

**Comment by line-o** [comment]
Closing due to inactivity. Spoke with @tuurma

**Pull request closed without merging**
