### PR TITLE
Fixes the installation of systemd for YAJSW

### PR DESCRIPTION
**Pull request by adamretter**
`systemctl --user` is inhertently insecure (and as such unsupported in RHEL derived distributions); Instead install eXist as a system service

Users should now run `tools/yajsw/bin/installDaemon.sh` as a user that has `sudo` privileges (or as root) and follow the instructions to install eXist with systemd.

...I think when systemd shuts down the service it is not stopping eXist gracefully, there is still possibly something wrong with our YAJSW config. However we can deal with that in a subsequent PR.

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz I don't think it should change anything on Mac, as I don't think Mac uses Systemd? Could you test on your mac?

**Comment by dizzzz** [comment]
@adamretter yes i'll do

**Comment by dizzzz** [comment]
@ljo asked me to write that he'll have a look at yaws this week. He is a bit surprised of the issues though since he has been testing the work intensively before.

**Comment by dizzzz** [comment]
@adamretter on macOS the `installDaemon.sh` works fine [with `EXIST_HOME` set)

**Comment by dizzzz** [comment]
@ljo  ????

**Comment by ljo** [comment]
@dizzzz Yes, I started the review and testing before, but only came back to it this week. So on it.

**Comment by dizzzz** [comment]
Great !

**Comment by dizzzz** [comment]
macOS works just fine

**Comment by adamretter** [comment]
@ljo what news?

**Comment by adamretter** [comment]
@ljo thanks :-)

**Pull request merged**
