### PR TITLE
Move the Versioning Module to it's own Git repo

### PR DESCRIPTION
**Pull request by adamretter**
[refactor] Removed the Versioning extension module. It has been moved to its own Git repository. Closes https://github.com/eXist-db/exist/issues/570

### CODE REVIEW

**Comment by meshkin** [comment]
where is its Git repository?

**Comment by dizzzz** [comment]
@meshkin good question, @adam ? @wolfgangmm ? @ljo ?

**Comment by adamretter** [comment]
I think maybe Tobi or Lars were going to create this?

**Comment by zwobit** [comment]
Current repo is on [bitbucket](https://bitbucket.org/zwobit/versioning). It more or less just contains the old code from the existdb git repo. My plan is to create a xar out of it, so it is easily installable into existdb.

**Pull request merged**
