### PR TITLE
Reworked LJO's PR #1157 

### PR DESCRIPTION
**Pull request by dizzzz**
let's check if travis finds it ok. rework of https://github.com/eXist-db/exist/pull/1157

### CODE REVIEW

**Comment by dizzzz** [comment]
@ljo @wolfgangmm  @shabanovd ? it is a prerequisite for my other PR

**Comment by ljo** [comment]
I would prefer an absolute path since yajsw will to my findings act strangly otherwise.

**Comment by dizzzz** [comment]
@ljo please can you be more specific ? Inthin if you set EXIST_HOME explicitly for the build,  this value will be used,

**Comment by dizzzz** [comment]
@ljo that will only be possible if we set a variable in a higher ant build file. The challenge then is.... how to be sure this value is passed?

**Comment by dizzzz** [comment]
@ljo I have found a solution....

**Pull request closed without merging**
