### PR TITLE
Exclude jcip-annotations-1.0.jar dependency from extensions

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1614

### CODE REVIEW

**Comment by dizzzz** [comment]
@adamretter are you sure this PR works? I did the similar thing last week (...) but for me, eXist-db did not startup because..... of the letterform dependency.

**Comment by dizzzz** [comment]
Just to be sure: 'http://localhost:8080' ends for you into the dashboard ?

**Comment by adamretter** [comment]
@dizzzz indeed it does

**Comment by dizzzz** [comment]
Cool

**Comment by adamretter** [comment]
@dizzzz please do test yourself though ;-)

**Comment by rvdb** [comment]
@adamretter I've tried `build dist-war` with the updated `ivy.xml` files, but all 3 jncip-annotations jars are still included in the generated WAR file.

**Comment by rvdb** [comment]
Whoops, update: of course I should have first rebuilt eXist before building a WAR dist. Silly me: of course it works, the ivy.xml settings exclude the redundant jcip-annotations jars to be downloaded for the initial build, and subsequently they're no longer included in the WAR file. Sorry for the noise!

**Comment by adamretter** [comment]
@rvdb No problem at all. Thank you for testing :-)

**Comment by rvdb** [comment]
@adamretter thanks for fixing!

**Comment by dizzzz** [comment]
OK

**Pull request merged**
