### PR TITLE
Written day of week was off by +1

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1878

Corrects a small issue when converting between Calendar bases.

### CODE REVIEW

**Comment by adamretter** [comment]
Yes this will still say Monday for you.

**Comment by joewiz** [comment]
I just committed fixes to the failures - which were all in the tests, not in the fix (which is correct). 

The test suite absolutely should have failed on this PR, as demonstrated by https://github.com/adamretter/exist/blob/f2d40c60dcf88ff95698c3b9bddaee400877d7f4/test/src/xquery/dates/format-dates.xql#L572. The typo here - `date-str` instead of `$date-str` - could never have worked. 

I am puzzled how CI tests were passing on this PR. Are the CI servers somehow skipping this tests? If so, are they also skipping other XQuery tests?

**Comment by adamretter** [comment]
@joewiz Travis has a limitation on how long a build can take. In the past I think that was 10 minutes, so we had to reduce the amount of tests we were executing. To do that rather than execute `build.sh test` we would execute `build.sh travis` which just ran a subset of the "most important" tests.

I think the limits have been increased, and so I have opened a PR here to see if we can now run the entire test suite on Travis and AppVeyor - https://github.com/eXist-db/exist/pull/1887

**Comment by adamretter** [comment]
Thanks @dizzzz

**Pull request merged**
