### PR TITLE
Add further JDK's to Travis

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz both are JDK 11 versions. Looks like we have problems with the build on Java 11

**Comment by adamretter** [comment]
@dizzzz this is ready to land.

**Comment by dizzzz** [comment]
Adam: yes that would be very beneficial, as ppl will start using eXist with these java versions too.....

**Comment by dizzzz** [comment]
thnx @adamretter !

**Pull request merged**
