### PR TITLE
- patched wrapper from @adamretter. Linux x86_64 binaries

### PR DESCRIPTION
**Pull request by zwobit**
- start|status|stop tested gentoo + systemd 64bit

### CODE REVIEW

**Comment by zwobit** [comment]
see #429

**Comment by dizzzz** [comment]
woops.... why is wrapper.jar updated? I'd not do that, is it really patched for linux? Otherwise i'; like to keep the existing one?

**Comment by adamretter** [comment]
@zwobit I think this is a bad pull request from you. It contains 250+ commits over 3500+ files. I think you just meant to commit the patched wrapper... no?

**Comment by shabanovd** [comment]
@adamretter it happen because of changes Lars. Rebase required.

**Comment by adamretter** [comment]
@shabanovd Sorry what change of Lars?

**Comment by adamretter** [comment]
@dizzzz Yes it is really patched

**Comment by shabanovd** [comment]
@adamretter http://sourceforge.net/p/exist/mailman/exist-commits/?viewmonth=201506&viewday=26

**Comment by adamretter** [comment]
@shabanovd This one - https://github.com/eXist-db/exist/commit/cd9c36cd0ad4acb6c7b20280f52e8589ae29ab94 or this one - 928950d0d7a12b332997aa1845d9d9cafbe4b915

**Comment by zwobit** [comment]
see https://github.com/eXist-db/exist/pull/708

**Pull request closed without merging**
