### PR TITLE
Update IntelliJ run configurations for 5.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by adamretter**
These need to be updated to work with the new development version.

### CODE REVIEW

**Comment by line-o** [comment]
@adamretter The current snapshot version is 5.3.1
I would assume these versions need to be in line, correct?

**Review by line-o — COMMENTED** [review]
See my question above

**Comment by adamretter** [comment]
> The current snapshot version is 5.3.1

Actually it is 5.4.0-SNAPSHOT, as I discussed with Lars and then fixed it.

**Review by dizzzz — APPROVED** [review]

**Comment by line-o** [comment]
@adamretter I am wondering if this is OK to merge now?

**Comment by adamretter** [comment]
@line-o Yes I would this so, as it won't affect a decision about whether a 5.3.1 is needed.

**Pull request merged**
