### PR TITLE
Reduce mutable state in MutableCollection

### PR DESCRIPTION
**Pull request by adamretter**
This removes two fields from `MutableCollection` which were unnecessarily located there as they are not persisted. These are:

* `userReader` - this can now instead be supplied when calling `Collection#validateXMLResource` and `Collection#store`.
* `triggersEnabled` - this can now be set on the `DBBroker` instead.

`triggersEnabled` was only modified when restoring a backup which contained deleted entries from a system export. To pass `triggersEnabled` to a `DBBroker` across the XML:DB (remote) API, required refactoring eXist-db's restore code, so that `__contents__.xml` parsing always happens server-side. To this end we have introduced the XML:DB service `RestoreService`. This actually puts us in a better position in future to be able to offer a more consistent database backup/restore.

### CODE REVIEW

**Comment by adamretter** [comment]
@wolfgangmm from the user perspective of performing backup/restore there are no changes.

The Java Admin Client is no longer compatible between 4.x.x and 5.0.0 but I suspect it hasn't been for all possible operations for quite some time. Where should we document this? In the release notes?

**Comment by joewiz** [comment]
As discussed during the Community Call, we would appreciate if folks would test this PR and see if you can restore your backups, particularly larger ones.

**Comment by dizzzz** [comment]
I have a large backup set here, I can try

**Comment by duncdrum** [comment]
@adamretter pre-emptively upgrade instructions should appear in the [upgrading article](https://github.com/eXist-db/documentation/blob/a9bcb918d2ed9aaa0d0a5a5b62bfc75f0695f2af/src/main/xar-resources/data/upgrading/upgrading.xml)

**Comment by duncdrum** [comment]
see #1358 ??

**Comment by adamretter** [comment]
@duncdrum there is some overlap, but its not the same

**Comment by adamretter** [comment]
@dizzzz Yup. At that point I had only added the test and not the fix. All fixed now...

**Comment by duncdrum** [comment]
Is there still a need for adjusted documentation @wolfgangmm @adamretter ?

**Comment by adamretter** [comment]
@duncdrum AFAIK, the changes should be invisible to the user.

**Pull request merged**
