### PR TITLE
Fix for "Update insert fails"

### PR DESCRIPTION
**Pull request by dizzzz**
See #1663

@adamretter You added the (now removed) lines some time ago....

- [x] add tests
- [x] address concerns

### CODE REVIEW

**Comment by dizzzz** [comment]
Added testcases

**Comment by dizzzz** [comment]
OK, thnx for the feedback..... I'll study....

**Comment by dizzzz** [comment]
Hmmmm I think I do not understand the class then. As it is highly undocumented, I need help here from you or @wolfgangmm ....

**Comment by dizzzz** [comment]
@adamretter I looked a long time at the code, the current "hasChildNodes()" looks to be OK (I annotated the meaning of the "children" variable).

I think the current code state should be ok, tests run all fine (in a previous PR-revision some XSLT tests failed)

**Comment by dizzzz** [comment]
Action: run domts (need help from @adamretter  here)

**Comment by adamretter** [comment]
Okay so this little program shows how Xerces interprets the XML sample you provided:

```xml
package org.exist.dom.persistent;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.*;

import static java.nio.charset.StandardCharsets.UTF_8;

public class XercesElementTest {

    public static void main(final String args[]) throws ParserConfigurationException, IOException, SAXException {
        final String xmlStr = "<root attr=\"1\"/>";

        final DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        final DocumentBuilder builder = factory.newDocumentBuilder();
        try(final InputStream is = new ByteArrayInputStream(xmlStr.getBytes(UTF_8))) {
            final Document doc = builder.parse(is);

            final Element rootElem = doc.getDocumentElement();

            System.out.println("hasChildNodes=" + rootElem.hasChildNodes());
            System.out.println("getLastChild=" + rootElem.getLastChild());
        }
    }
}
```

It returns the output:
```
hasChildNodes=false
getLastChild=null
```

I can confirm that eXist-db's persistent Element implementation also returns the same results. So the problem seems to be that our `org.exist.dom.persistent#appendChildren(Txn, NodeList, int)` is no longer correct, since my DOM improvements.

**Comment by dizzzz** [comment]
thnx for verifying my changes.... so in essence you say my proposed change is not ok? too bad :-/

**Comment by adamretter** [comment]
@dizzzz Sadly the fix to `getLastChild` is not sufficient. I have a fix here, will incorprorate into your PR and your nice tests

**Pull request closed without merging**
