### PR TITLE
arrow operator raise error if xquery is < 3.1

### LINKED ISSUE #1328: Use of arrow operator in XQuery <3.1 should raise EXXQDY0003
### What is the problem

Use of the arrow operator in XQuery 1.0 or 3.0 doesn't raise an error.

### What did you expect

An error should be raised, since this syntax was added only in XQuery 3.1. 

### Describe how to reproduce or add a test

```xquery
xquery version "3.0";

"hello" => string-length()
```

returns `5` instead of `EXXQDY0003`

### Context information

- eXist-db version + Git Revision hash: eXist-db 3.0 develop 
- Java version: Java8u121
- Operating system: macOS
- 64 bit
- Any custom changes in e.g. conf.xml: no

### PR DESCRIPTION
**Pull request by shabanovd**
close #1328

### CODE REVIEW

**Comment by adamretter** [comment]
@shabanovd Can we have a test please?

**Comment by shabanovd** [comment]
@adamretter you did commit change without test or review and ask for test now .... how sweet is it

**Comment by adamretter** [comment]
@shabanovd which commit to you refer to please?

**Comment by shabanovd** [comment]
@adamretter you get your test, I hope to get my (here your [commit](https://github.com/eXist-db/xquery-xproc-xmlcalabash-module/commit/ebd5e25c803da729087f8b5c6767e427f18a3831))

**Comment by joewiz** [comment]
Dmitriy, please keep the issue tracker focused and on topic. If you have concerns about process, we do have a forum and process for productively and responsibly addressing them. :-)

**Comment by joewiz** [comment]
And back to the topic at hand, thanks so much for the quick fix and test!

**Comment by shabanovd** [comment]
@joewiz my comment on [commit](https://github.com/eXist-db/xquery-xproc-xmlcalabash-module/commit/ebd5e25c803da729087f8b5c6767e427f18a3831#diff-809c93b5c56419df337f8ae44ef6e295R133) was ignored ... so, "process" is not working. And I, simply, don't want to get instruction to follow rule from person that do not follow that rule himself. That is the highest antiproductively factor, IMHO.

**Comment by joewiz** [comment]
Please, this issue isn't the forum...

**Comment by shabanovd** [comment]
@joewiz there is "delete" button to clean it up ;-)

**Comment by joewiz** [comment]
@shabanovd Thank you!

Should this be added to the 3.2.0 milestone?

**Pull request merged**
