### PR TITLE
Improve custom analyzer config

### PR DESCRIPTION
**Pull request by adamretter**
This allows two additional parameter types when specifying a custom analyzer:
1. `java.lang.String[]`
2. `char[]`

Documentation is here: https://github.com/eXist-db/documentation/pull/706

### CODE REVIEW

**Review by duncdrum — COMMENTED** [review]
Docs need a second pass, any reason not to add the `paratermized type` annotations that sonatype is complaining about. Looks like a valid concern.

**Comment by adamretter** [comment]
@duncdrum I just added a commit to satisfy Codacy.

**Review by line-o — CHANGES_REQUESTED** [review]
I think this is a valuable addition to allow more types to be passed to Lucene analyzers.
Please add tests to ensure this works now and in the future.

**Comment by adamretter** [comment]
@line-o Sure no problem. I just added the tests

**Comment by adamretter** [comment]
@duncdrum @line-o @dizzzz Can someone merge this please?

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
