### PR TITLE
Use mvnd in GitHub Actions

### PR DESCRIPTION
**Pull request by adamretter**
Builds atop https://github.com/eXist-db/exist/pull/4917 to switch CI from using `mvn` to `mvnd` (i.e. Maven Daemon)

### CODE REVIEW

**Comment by adamretter** [comment]
Connecting to the Maven Daemon in Windows and macOS runners seems to intermittently fail even though I have provided a generous timeout of 90 seconds. I have made enquiries about that here - https://github.com/apache/maven-mvnd/issues/772#issuecomment-1501692763

**Review by reinhapa — APPROVED** [review]

**Comment by dizzzz** [comment]
OK to pull?

**Comment by duncdrum** [comment]
@dizzzz as long as the problems with mavend on win and macOS persist, I d say no. Otherwise we give up testing on the list of supported platforms. 

The config changes do not depend on mavend. We either wait for things to get sorted out upstream with mavend or create a new PR without mavend

**Comment by reinhapa** [comment]
> @dizzzz as long as the problems with mavend on win and macOS persist, I d say no. Otherwise we give up testing on the list of supported platforms.
> 
> The config changes do not depend on mavend. We either wait for things to get sorted out upstream with mavend or create a new PR without mavend

@duncdrum as far as I can see do the actual test pass on Windows, "only" the coverage part fails with a timeout... I'm in the process to check that build on my Windows instance at the moment...

**Comment by duncdrum** [comment]
@reinhapa unfortunately the mavend time-out linked above occurs on the start of ci run, so the test won’t run. 

If that issue has been fixed good to merge, but otherwise we should still hold, otherwise we risk PRs with stuck runs on both win and macOS

**Comment by adamretter** [comment]
I separated the non-mvnd related changes out into a new PR (which should be merged first) - https://github.com/eXist-db/exist/pull/4917

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
I missed the latest changes, my apologies. a A ll lok OK to me right now!

**Pull request merged**
