### PR TITLE
Look for controller.xq before controller.xql

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/3739

### CODE REVIEW

**Review by line-o — COMMENTED** [review]
LGTM
About a way to test this:
1. create a collection in `/db/apps` `my-app`
2. store a collection.xq in `/db/apps/my-app` that defines one route `my-route`
3. make a request to `/exist/apps/my-app/my-route` of the testserver

**Review by dizzzz — APPROVED** [review]

**Comment by adamretter** [comment]
@line-o I added the tests as suggested.

**Comment by line-o** [comment]
I would kindly ask for the refactoring of HTTPTests to be made better visible by having it in a separate commit.
And we should definitely have a hard look at the several differing approaches on how to test Requests.
Find or create the one that we want to go with and then refactor all HTTP tests to use that method.

**Comment by joewiz** [comment]
Restarting CI tests...

**Comment by adamretter** [comment]
@joewiz I just rebased it so it will run atop the latest CI changes

**Comment by duncdrum** [comment]
@adamretter can you rebase again please

**Comment by adamretter** [comment]
@duncdrum Done.

**Comment by duncdrum** [comment]
LGTM just needs the docs PR

**Comment by joewiz** [comment]
There are still quite a few CI failures - are these to be expected at this point in the CI overhaul?

From https://github.com/eXist-db/exist/pull/3757/checks?check_run_id=2159836570:

(timeout? cancelled after 360m)

From https://github.com/eXist-db/exist/pull/3757/checks?check_run_id=2159836544

```txt
Error:  Failed to execute goal org.owasp:dependency-check-maven:6.1.2:check (default) on project exist-mail: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
Error:  	AnalysisException: Failed to request component-reports
Error:  		caused by TransportException: Unexpected response; status: 429
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :exist-mail
Error: Process completed with exit code 1.
```

From https://github.com/eXist-db/exist/pull/3757/checks?check_run_id=2159836551:

```txt
Error:  Failed to execute goal org.owasp:dependency-check-maven:6.1.2:check (default) on project exist-index-spatial: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
Error:  	AnalysisException: Failed to request component-reports
Error:  		caused by TransportException: Unexpected response; status: 429
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :exist-index-spatial
Error: Process completed with exit code 1.
```

From https://github.com/eXist-db/exist/pull/3757/checks?check_run_id=2159836597:

```txt
Error:  Failed to execute goal com.mycila:license-maven-plugin:4.0.rc1:check (check-headers) on project exist-parent: Execution check-headers of goal com.mycila:license-maven-plugin:4.0.rc1:check failed: Plugin com.mycila:license-maven-plugin:4.0.rc1 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-model:jar:3.1.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-model/3.1.0/maven-model-3.1.0.jar: Connection reset -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Error: Process completed with exit code 1.
```

From https://sonarcloud.io/dashboard?id=eXist-db_exist&pullRequest=3757:

```txt
Coverage on 10 New Lines to cover: 0.0%
```

From https://ci.appveyor.com/project/eXistdbci/exist/builds/38328215:

```txt
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.0.rc1:check (check-headers) on project exist-docker: Some files do not have the expected license header -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :exist-docker
Command exited with code 1
Running "on_failure" scripts
```

**Comment by adamretter** [comment]
@joewiz I think these are all caused by transient network issues, so I just restarted a bunch of them...

**Comment by joewiz** [comment]
I restarted the GitHub Actions CI jobs and now only 4 of these fail - the macOS builds, all after 8-9 minutes. SonarCloud and AppVeyor also fail. Do we see these failures as completely unrelated to the PR, and thus no substantive barrier to merging it?

**Comment by adamretter** [comment]
> Do we see these failures as completely unrelated to the PR, and thus no substantive barrier to merging it?

Yes they are unrelated.

**Comment by adamretter** [comment]
Documentation is now done - https://github.com/eXist-db/documentation/pull/596

**Review by joewiz — APPROVED** [review]

**Pull request merged**
