### PR TITLE
Feature/flexible installer

### PR DESCRIPTION
**Pull request by amclark42**
Remove the step of copying the scripts from `bin` to `installer/scripts` in favor of keeping the scripts in the latter. This way, the installer always has the original copy of the scripts. This does not affect those building an installer from source, and allows people to build further, derivative installers that do not contain local filepaths.

To test:
- build an installer from source with `./build.sh installer`;
- install eXist-TEST1 in a separate location;
- build an installer from eXist-TEST1;
- install eXist-TEST2 in a separate location; and
- ensure that eXist-TEST2 starts up with `./bin/startup.sh`.

### CODE REVIEW

**Comment by amclark42** [comment]
Resolves #509

**Comment by joewiz** [comment]
When you said "in the latter" (`installer/scripts`), did you mean to say "in the former" (`bin`)?

**Comment by adamretter** [comment]
@amclark42 I am not sure that moving the scripts from `bin` to `installer/scripts` is a good idea as it breaks the ability to use eXist for those who clone directly from Git or obtain a tarball of the source code. The installer is just one mechanism for obtaining/installing eXist.

I think we need to determine another mechanism for fixing your issue. The shell scripts should remain in `installer/scripts`. I will try and work though your issue described here https://github.com/eXist-db/exist/issues/509 so that I can understand what is happening?

Am I right in thinking your issue boils down to creating an installer from a copy of eXist that has been installed using the installer?

**Comment by amclark42** [comment]
@adamretter That makes sense.

Yes, your summary of the issue is correct. I wanted the installer to use fresh copies of the scripts. Currently, if a derivative installer is built, the new installer will contain the JAVA_HOME-ish and EXIST_HOME-ish paths from the original installation.

Of course, as you noted in exist-open, one can work around this by setting those variables oneself. But I still do feel that the installer should use fresh scripts rather than ones altered for working use!

**Comment by adamretter** [comment]
@duncdrum not just yet

**Comment by adamretter** [comment]
Closed by https://github.com/eXist-db/exist/pull/2657

@amclark42 the installer scripts are now generated from templates

**Pull request closed without merging**
