### PR TITLE
[4.x.x] Fix an issue where XQuery Trigger state may leak

### PR DESCRIPTION
**Pull request by adamretter**
Backport of https://github.com/eXist-db/exist/pull/5481

**NOTE**: Needs https://github.com/eXist-db/exist/pull/5468 merged first and then this needs to be rebased

### CODE REVIEW

**Review by reinhapa — APPROVED** [review]

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
all builds fail...

**Comment by dizzzz** [comment]
https://github.com/eXist-db/exist/pull/5468  is in....

**Comment by adamretter** [comment]
> https://github.com/eXist-db/exist/pull/5468 is in.... (since a minute)

@dizzzz Thanks :-) Okay I have rebased it, let's see what CI says...

**Comment by adamretter** [comment]
@dizzzz The 1 flaky test failure on Windows in CI for `AllStorageTests` occurs because `StoreResourceTest.checkAttributes` seems to believe that updating a document takes less than 1ms occasionally. I have appended a commit that should address that.

**Review by reinhapa — APPROVED** [review]

**Pull request merged**
