### PR TITLE
[feature] Adds dependabot updates for github actions

### PR DESCRIPTION
**Pull request by reinhapa**
Enables `dependabot` updates for `github-actions`.

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
image
this extension is gone.....

**Review by dizzzz — CHANGES_REQUESTED** [review]
still not OK....

**Comment by reinhapa** [comment]
@dizzzz the Javadoc issue was addressed in #4743 ...

**Review by line-o — APPROVED** [review]

**Comment by line-o** [comment]
It's good now. XQTS cannot pass at the moment. @reinhapa thanks!

**Review by duncdrum — APPROVED** [review]

**Comment by duncdrum** [comment]
@dizzzz i agree good to merge

**Pull request merged**
