### PR TITLE
[bugfix] Fix an issue with concurrent access to BrokerPool

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/issues/1075

### CODE REVIEW

**Comment by shabanovd** [comment]
will `synchronized` do the same with simpler pattern?

**Comment by adamretter** [comment]
@shabanovd My approach still allows some read/write concurrency around instances, `synchronized` would not.

**Comment by shabanovd** [comment]
@adamretter how critical concurrency for `getInstance` call? I do not feel that it require high concurrency.

**Comment by adamretter** [comment]
@shabanovd Well `getInstance` is called from many places. But... this fixes the problem, do you see something wrong with the fix apart from maybe it's not how you would have done it yourself?

**Comment by shabanovd** [comment]
@adamretter just complexity of it that should be supported in future

**Comment by adamretter** [comment]
@shabanovd to make BrokerPool more understandable, I have an alternative which is https://github.com/eXist-db/exist/pull/1082; That also effectively includes a very similar fix to this PR, if you prefer that, I will close this PR.

**Comment by shabanovd** [comment]
@adamretter yes, #1082 is better step forward. Close this PR.

**Comment by adamretter** [comment]
Subsumed by https://github.com/eXist-db/exist/pull/1082

**Pull request closed without merging**
