### PR TITLE
add security mail to contributing.md

### PR DESCRIPTION
**Pull request by duncdrum**
see exist-db/exist#1554

### CODE REVIEW

**Comment by duncdrum** [comment]
please make sure that the email actually does what this PR advertises it does before pulling in.

**Comment by adamretter** [comment]
@wolfgangmm Where does `security@exist-db.org` go to? Assuming its a forwarder, could you put me on the list please?

**Comment by wolfgangmm** [comment]
@adamretter I created the account before merging the PR. Check your inbox, your confirmation is required ;-)

**Comment by adamretter** [comment]
@wolfgangmm thanks :-)

**Comment by adamretter** [comment]
@duncdrum Thank you for your excellent contribution :-)

**Pull request merged**
