### PR TITLE
[bugfix] Make build compatible with Java18 and beyond.

### LINKED ISSUE #5249: Building with Java 21 fails due to ancient Antlr plugin
I know, that support for Java 17 is planned for version 7.0, see the [blog post "January 2023 Releases" from 2023/01/15](https://exist-db.org/exist/apps/wiki/blogs/eXist/january-2023-releases) - over a year ago. 
Since Java 8 is EOL for non paying customers for [about two years now](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) and the current LTS is already Java 21, the following should be fixed in the development branch ASAP:

```
[ERROR] Failed to execute goal org.codehaus.mojo:antlr-maven-plugin:2.2:generate (default) on project exist-core: Execution default of goal org.codehaus.mojo:antlr-maven-plugin:2.2:generate failed: The Security Manager is deprecated and will be removed in a future release -> [Help 1]
```

Enviroment:
```
mvn --version
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec
Java version: 21.0.1, vendor: Oracle Corporation, runtime: /Users/cmahnke/.sdkman/candidates/java/21.0.1-graal
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "14.2.1", arch: "aarch64", family: "mac"
```

The problem is  introduced by the Maven plugin `org.codehaus.mojo:antlr-maven-plugin:2.2` (which was released [2010](https://mvnrepository.com/artifact/org.codehaus.mojo/antlr-maven-plugin/2.2)) in the `exist-core` module. Even though there seems to be a [fix](https://bugs.launchpad.net/ubuntu/+source/antlr-maven-plugin/+bug/2052993). A clean solution would get rid of this unmaintained dependency of the build system and maybe switch to AntLR 4 in the process.

### PR DESCRIPTION
**Pull request by dizzzz**
Fixes #5249

Contribution by https://github.com/omnifaces/antlr-maven-plugin

### CODE REVIEW

**Comment by dizzzz** [comment]
still to do..... add Java21 build

**Review by line-o — APPROVED** [review]
Excellent!

**Comment by dizzzz** [comment]
image

did not see this locally .....

**Comment by dizzzz** [comment]
it boils down to this line..... 

https://github.com/eXist-db/exist/blob/1df74966e55065d108610a311a07e48d32517f6f/extensions/indexes/range/src/test/java/org/exist/indexing/range/RangeIndexConfigTest.java#L114C1-L115C1 

It is very advance mocking of the logger.......

**Comment by dizzzz** [comment]
Cool, I found an alternative/better way of checking logs. Pending build.....

**Comment by dizzzz** [comment]
for reviewers.... 3 commits are interesting, the other 3 are just refactoring/pending code improvements

image

**Comment by dizzzz** [comment]
for reviewers: the core of the changes is in 4 commits, the remaining two touch a lot of files but is just pending refactoring.

image

**Review by duncdrum — APPROVED** [review]

**Review by reinhapa — DISMISSED** [review]

**Comment by line-o** [comment]
I fear this will will introduce merge conflicts with #5259. @dizzzz could you make sure to either incorporate those commits first?

**Comment by dizzzz** [comment]
@line-o that makes sense, apologies.

I need some help/instructions to revert f601694c91413d9e20f25a63a5ff52ab7d7ef6a2 and 3690d42cddb6888eceee8ee49f876da4eb42119f in a correct way

**Comment by line-o** [comment]
@dizzzz `git rebase -i` would be my tool of choice. This can either drop the commits entirely or lets you edit the two.

Rebasing your changes on top of my commits is also an option.

**Comment by dizzzz** [comment]
@line-o I think I addressed the issue

**Review by reinhapa — APPROVED** [review]

**Review by line-o — APPROVED** [review]

**Pull request merged**
