### PR TITLE
Switch to nonblocking free ids processing algorithms

### PR DESCRIPTION
**Pull request by shabanovd**
### Description:
Free ids stack use locking that lead to deadlock. Switch to nonblocking stacks and remove locks.

### CODE REVIEW

**Comment by shabanovd** [comment]
@wolfgangmm this address your deadlock situation

**Comment by adamretter** [comment]
Removing the locking for those items where it is not needed is a nice idea.

However if this is the cause of the deadlock seen by @wolfgangmm if we examine the code for the call-sites to `CollectionStore#getFreeCollectionId` and `CollectionStore#getFreeResourceId`  we can see this is not the root cause, and that this change would just move such a deadlock to `NativeBroker#getNextCollectionId` and `NativeBroker#getNextResourceId`.

Also looking at the existing code, it seems to me that there may be an existing race-condition concern around the inconsistent locking of the in-memory list of free ids in `CollectionStore` and the on-disk list in the `collections.dbx`.

**Comment by shabanovd** [comment]
@adamretter the problem much bigger than your description above. This is one small step to make eXist-db lock free, because any 2 locks will have deadlock and only no lock design avoid it.

**Comment by shabanovd** [comment]
@adamretter next problem that collection lock (write or read) required only for `documents`, `subCollections` or metadata modification or read. Good example of it [here](https://github.com/eXist-db/exist/blob/552be315ac6e7fb61fca4e811af5f4fc49fe5682/src/org/exist/collections/MutableCollection.java#L253-L262). Any other code that have two (or more) locks during processing will result deadlock.

**Comment by adamretter** [comment]
@shabanovd It will not be possible to make eXist-db lock free without replacing all storage backends, and even then you will loose some of the consistency that it currently has.

Regards to locks deadlocking, yes when you have two lock a deadlock is a possibility, but there is decades of research into lock scheduling and lock protocols to help us avoid such situations.

Let's just focus on this PR rather than talking theory. This PR IMHO does not solve any problem, it just moves the problem up one stack-frame.

**Comment by shabanovd** [comment]
@adamretter So, your statement that this PR do not solve any issue, right?

**Comment by adamretter** [comment]
@shabanovd My statement is, that as far as I can see, that this PR just moves the issue up one stack-frame

**Comment by shabanovd** [comment]
@adamretter then let's say this "@wolfgangmm this PR do not address your deadlock situation, but improve concurrency for free ids". Good to go?

**Pull request closed without merging**
