### PR TITLE
remove XACML code

### PR DESCRIPTION
**Pull request by shabanovd**

### CODE REVIEW

**Comment by ljo** [comment]
It is probably the best to remove this, yes, thanks.

**Comment by shabanovd** [comment]
@ljo thanks, `excluded` was set for `build` folder and search ignore it. It's fixed now.

**Comment by adamretter** [comment]
@shabanovd Why 3 commits which all have the same name? Could you not have squashed these?

**Comment by shabanovd** [comment]
@adamretter had problems with rebase, get tired and decide to commit as it

**Comment by dizzzz** [comment]
In the github webpage, it is possible now to squash commits during pulling in the PR.....

**Pull request merged**
