### PR TITLE
Add support for xml:space preserve in IndentingXMLWriter serializer

### PR DESCRIPTION
**Pull request by ljo**
Marks the beginning of whitespace week.

### CODE REVIEW

**Comment by dizzzz** [comment]
looks good to me, though I do not completely see the issue :-)

**Comment by ljo** [comment]
It makes the serializer respect xml:space attribute values of preserving whitespace or not for the current element. I have some testcases coming in with the other changes.

**Comment by adamretter** [comment]
@ljo Without tests I can't really say if this is correct...

**Comment by dizzzz** [comment]
tests will appear soon! (@ljo)

**Pull request merged**
