### PR TITLE
Fix for Windows paths with Spaces

### LINKED ISSUE #729: A space in JAVA_HOME on Windows 7 causes build.bat to fail
Using cmd.exe:

```cmd
git clone https://github.com/exist-db/exist.git
cd exist
set JAVA_HOME="c:\Program Files\Java\jdk1.8.0_45"
build.bat
```

Results in:
`Files\Java\jdk1.8.0_45"" was unexpected at this time.`

### PR DESCRIPTION
**Pull request by adamretter**
Closes #729

### CODE REVIEW

**Comment by dizzzz** [comment]
Are you sure it is fixed? AT least visually it is now not attractive:

```
D:\Sources\exist_DEV>set JAVA_HOME=C:\Localdata\Progra~1\Java\jdk1.8.0_31

D:\Sources\exist_DEV>build.bat
The system cannot find the file C:\Localdata\Progra~1\Java\jdk1.8.0_31.
The system cannot find the file D:\Sources\exist_DEV.
eXist Build
-------------------
JAVA_HOME=C:\Localdata\Progra~1\Java\jdk1.8.0_31
EXIST_HOME=D:\Sources\exist_DEV
_LIBJARS=C:\Program Files (x86)\IBM\RationalSDLC\ClearQuest\cqjni.jar;D:\Sources\exist_DEV\tools\ant\lib\ant-launcher-1.9.4.jar
_JAVA_OPTS=-Xms512m -Xmx512m -Djava.endorsed.dirs="D:\Sources\exist_DEV\lib\endorsed" -Dant.home="D:\Sources\exist_DEV\tools\ant" -Dexist.home="D:\Sources\exist_DEV" -Djavax.xml.transform.TransformerFactory="org.apache.xalan.pro
cessor.TransformerFactoryImpl"
Starting Ant...
ECHO is off.
Buildfile: D:\Sources\exist_DEV\build.xml
```

and

```
D:\Sources\exist_DEV>set JAVA_HOME=C:\Localdata\Program Files\Java\jdk1.8.0_31

D:\Sources\exist_DEV>build.bat
The system cannot find the file C:\Localdata\Program.
eXist Build
-------------------
JAVA_HOME=C:\Localdata\Program Files\Java\jdk1.8.0_31
EXIST_HOME=D:\Sources\exist_DEV
_LIBJARS=C:\Program Files (x86)\IBM\RationalSDLC\ClearQuest\cqjni.jar;D:\Sources\exist_DEV\tools\ant\lib\ant-launcher-1.9.4.jar
_JAVA_OPTS=-Xms512m -Xmx512m -Djava.endorsed.dirs="D:\Sources\exist_DEV\lib\endorsed" -Dant.home="D:\Sources\exist_DEV\tools\ant" -Dexist.home="D:\S
ources\exist_DEV" -Djavax.xml.transform.TransformerFactory="org.apache.xalan.processor.TransformerFactoryImpl"
Starting Ant...
ECHO is off.
Buildfile: D:\Sources\exist_DEV\build.xml
```

**Comment by adamretter** [comment]
So when I did my testing I used quotes around the path passed to set because it has spaces in it. If you don't do that I think you will get an unexpected result regardless of eXist.

What do you see if you run this:

```
set JAVA_HOME=C:\Localdata\Program Files\Java\jdk1.8.0_31
echo %JAVA_HOME%
```
I think you will see `C:\Localdata\Program`, which is obviously not right ;-)

If so, then perhaps what you meant to run was:

```
set JAVA_HOME="C:\Localdata\Program Files\Java\jdk1.8.0_31"
echo %JAVA_HOME%
```

**Comment by bwbohl** [comment]
I can confirm that paths with spaces need quotation marks on Windows, regardless of eXist.


Am 22.07.2015 um 16:46 schrieb Adam Retter <notifications@github.com>:

**Comment by adamretter** [comment]
@bwbohl Thanks, that was my understanding too.

**Comment by dizzzz** [comment]
@adamretter yes you are right, thnx !

**Pull request merged**
