### PR TITLE
[feature] Update to log4j 2.7

### PR DESCRIPTION
**Pull request by adamretter**
@dizzzz Just for you ;-)

### CODE REVIEW

**Comment by dizzzz** [comment]
I just realized that for the jul library we need to set an additional system property so jul calls actually end up in our logging.....

**Comment by joewiz** [comment]
Just curious: what's the jul library?

**Comment by dizzzz** [comment]
Java Util Logging https://logging.apache.org/log4j/2.0/log4j-jul/index.html 

> Usage
> To use the JDK Logging Adapter, you must set the system property java.util.logging.manager to org.apache.logging.log4j.jul.LogManager
> 
> This must be done either through the command line (i.e., using the -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager argument) or by using System.setProperty() before any calls are made to LogManager or Logger.
>

**Comment by adamretter** [comment]
@joewiz JUL is java.util.logging. Some of the libraries we depend on use the logging available as part of the JDK. The log4j jul library allows you to redirect those log messages to log4j

**Comment by adamretter** [comment]
@dizzzz I am fairly certain I already did that in the past. I will try and find where...

**Comment by dizzzz** [comment]
yes you did :-)

src/org/exist/start/Main.java
430:            System.setProperty("java.util.logging.manager", Optional.ofNullable(System.getProperty("java.util.logging.manager")).orElse("org.apache.logging.log4j.jul.LogManager"));

**Comment by joewiz** [comment]
@dizzzz Got it, thanks!

**Comment by adamretter** [comment]
@dizzzz :-)

**Comment by dizzzz** [comment]
my friend: http://beyondgrep.com .... grep on steroids

**Pull request merged**
