### PR TITLE
fix(ci): reenable docker builds

### LINKED ISSUE #3696: [feature] re-enable docker builds
Since the changes to `travis-ci.com` on `01.11.2020` we no longer publish docker images. So wherever exist goes from here, we need to reactivate the docker publishing pipeline.

### PR DESCRIPTION
**Pull request by duncdrum**
add deployment to docker, mirroring what we did on travis. 

secrets: DOCKER_USERNAME & DOCKER_PASSWORD must be configured in repo

close #3696

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]

**Review by dizzzz — CHANGES_REQUESTED** [review]
build issues

**Comment by wolfgangmm** [comment]
I configured the required secrets in the repo

**Comment by adamretter** [comment]
If we can merge https://github.com/eXist-db/exist/pull/3751 first please, then I can rebase this.

**Comment by duncdrum** [comment]
@adamretter we ll probably need to add the `-Ddocker=True` flag after the rebase

**Comment by duncdrum** [comment]
rebasing now

**Comment by duncdrum** [comment]
superseded by #3760

**Pull request closed without merging**
