### PR TITLE
Update to Tika version 1.20

### LINKED ISSUE #2173: Update contentextraction extension to Tika 1.20
Since adopting Tika 1.16 last September in https://github.com/eXist-db/exist/pull/1391, several updates to Tika have been released, with significant new features and bug fixes. Release notes are at:

- 1.17: http://tika.apache.org/1.17/index.html
- 1.18: http://tika.apache.org/1.18/index.html
- 1.19: http://tika.apache.org/1.19/index.html
- 1.19.1: https://tika.apache.org/1.19.1/index.html
- 1.20: https://tika.apache.org/1.20/index.html

### PR DESCRIPTION
**Pull request by adamretter**
Closes #2173

### CODE REVIEW

**Comment by joewiz** [comment]
@adamretter Thank you! This will also close https://github.com/eXist-db/exist/issues/2173.

**Comment by joewiz** [comment]
Travis failed on this one, but passed on the ports (#2559 and #2560). Please advise.

**Comment by duncdrum** [comment]
@joewiz java9 timed-out (see last line of log) classic case of rerun.

**Comment by joewiz** [comment]
@duncdrum Okay, thanks. I found the button to restart the job. Fingers crossed that this run doesn't exceed the time limit like the first one did.

**Comment by adamretter** [comment]
@duncdrum @joewiz some of the builds timing out on Travis or AppVeyor is not unusual. We are usually pretty close to their build time limit, and so if one of their hosts is particularly loaded we can occasionally exceed it.

**Comment by joewiz** [comment]
@adamretter Ah, I see. The build passed, so since @dizzzz approved, I'll merge the set. Thanks again!

**Pull request merged**
