### PR TITLE
[bugfix] root node should use supplied context if present

### PR DESCRIPTION
**Pull request by adamretter**
Gets us another 4 % in the XQTS 3.1

### CODE REVIEW

**Comment by duncdrum** [comment]
Looks like we need to inform our testsuite about the expected behavior

**Comment by adamretter** [comment]
@duncdrum these failures are related to the issue discussed here - https://github.com/eXist-db/exist/pull/3167

**Comment by line-o** [comment]
@adamretter I will not be able to push into this PR. Therefore, I will your change and my additions in a separate one.

**Comment by line-o** [comment]
this PR is superseded by #3605

**Pull request closed without merging**
