### PR TITLE
Allow more elaborate XPath expressions in the Lucene index spec (original PR #2169)

### PR DESCRIPTION
**Pull request by sten1ee**
Allow more elaborate XPath expressions in the Lucene index spec in collection.xconf (original PR #2169)
For more information, see the discussion in the original PR: https://github.com/eXist-db/exist/pull/2169

### CODE REVIEW

**Comment by sten1ee** [comment]
Looking at AppVeyor log, I can't understand what went wrong with the OpenJDK 9 build.
Help, anybody?

**Comment by wolfgangmm** [comment]
We agreed during the community call that I'll spend another day tomorrow to put your changes to the test again and merge the PR if I do not find issues.

**Comment by duncdrum** [comment]
great @sten1ee do you need help with the backports? basically create a feature-branch from `develop-4.0.0` and cherry pick this commit into it, then open a second PR. The do the same one last time for `develop-5.0.0` branch so it ll be three PRs in total?

**Comment by dizzzz** [comment]
@duncdrum @sten1ee the port the PR is available. Waiting for the builds to finish...

**Comment by sten1ee** [comment]
May be it just a useless concern, but:
Do you take care to backport the updated documentation too?
(IIRC it required a separate PR, i.e. it's a part of a separate repo)

**Comment by duncdrum** [comment]
@sten1ee the docus do not have a Release Candidate, which is the only reasons why we have to go through this whole backporting forwardporting dance here currently. You changes are merged and IIRC are already live with the latest version available via package-manager.  (if not they will be in the next release)
Thank you so much for your contribution, and for sticking with it.

**Comment by joewiz** [comment]
@sten1ee Let me echo Duncan's thanks for this contribution! 

Could you confirm that at the current time, only predicates with the pattern `[@attr=value]` are supported?

In a future extension of this, we may want to explore adding support for other operators and reconciling/aligning this method of specifying conditions with the one added in https://github.com/eXist-db/exist/pull/1233 and https://github.com/eXist-db/exist/pull/1252 and documented in https://exist-db.org/exist/apps/doc/newrangeindex#D3.21.18.

**Comment by sten1ee** [comment]
@joewiz Yes, currently only ```[@attr=value]``` are supported.
Looking at the code I see that currently no space is allowed between the ```[``` and the ```@```, i.e. ```[  @attr=value]``` will be an error.
For the sake of (both source code and product) documentation:
Parsing these attribute predicates is done in ```class org.exist.indexing.lucene.NodePathPattern```
More specifically (currently) line 142:
```
private Predicate parsePredicate(String input) {
```
Note that the present implementation is very naïve. But this is the place to plug in a proper predicate parser impl. in order to handle a wider variety of predicates.

**Pull request merged**
