### PR TITLE
adding Windows line endings (CRLF) to .bat files

### PR DESCRIPTION
**Pull request by jensopetersen**
https://github.com/eXist-db/exist/issues/474

### CODE REVIEW

**Comment by shabanovd** [comment]
git may overwrite it

**Comment by jensopetersen** [comment]
One file (don't remember which) had correct line endings, so perhaps it does not ….

**Comment by shabanovd** [comment]
it will each time someone commit to that file. http://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

**Comment by jensopetersen** [comment]
Yes, you are right. All existing .bat files have LF only, I was wrong. Please close PR without merging. 

So a Windows user should set git config core.autocrlf?

**Comment by dizzzz** [comment]
The installer can fix it right?

**Pull request closed without merging**
