### PR TITLE
Add Code Coverage

### PR DESCRIPTION
**Pull request by adamretter**
Adds support for Code Coverage reports with JaCoCo and also integrates Travis with Coveralls.io to report historical use/change of Code Coverage.

**NOTE**: There is a bug that this surfaces that we need to fix - https://github.com/jacoco/jacoco/issues/1042

### CODE REVIEW

**Comment by adamretter** [comment]
Waiting on: https://github.com/jacoco/jacoco/issues/1042

**Comment by line-o** [comment]
From the referenced jacoco issue:

> I suspect that this is caused by something in your tests or main code that use embedded Jetty - the above command won't be stuck and corruption of JaCoCo file also does not happen when `org.exist.management.JmxRemoteTest` and `org.exist.http.urlrewrite.URLRewritingTest` are excluded from execution.

**Review by dizzzz — APPROVED** [review]

**Comment by duncdrum** [comment]
should we maybe spread the load and run this on the javadoc workflow, instead of the test workflow?

**Review by duncdrum — APPROVED** [review]
the secrete not being availble before we merge this is WAI on gh-actions
the crucial line is https://github.com/adamretter/exist/runs/2361117888?check_suite_focus=true#step:6:10

we can thing about adding this to another less heavy workflow when we refactor the flows, soits not a stopper for coverage

**Comment by adamretter** [comment]
> run this on the javadoc workflow, instead of the test workflow?

That won't work, coverage is generated based on tests.

**Comment by duncdrum** [comment]
@adamretter based on the presence of tests in the code-base or based on the results of executing the tests?

**Comment by adamretter** [comment]
@duncdrum The tests have to be executed.

**Comment by joewiz** [comment]
@adamretter According to @duncdrum the Coveralls integration with eXist-db is broken and needs some configuration fixes.

**Pull request merged**
