### PR TITLE
Fixing wrong context item for fn:lang #504 by reverting changes by DS in...

### PR DESCRIPTION
**Pull request by ljo**
... commit c307fec3e5c397acefefc92286f221440dad354e.

### CODE REVIEW

**Comment by shabanovd** [comment]
how many tests from XQTS going to fail?

**Comment by ljo** [comment]
From what you wrote, eg working with attribute node in second parameter, it works as expected with this solution, as well as the expected cases like the #504 one. You did not reference any explicit xqts tests.

**Comment by shabanovd** [comment]
it was a fix of ~10s xqts tests, and if you say that you get no degradation there than ok.

**Comment by dizzzz** [comment]
general question: does the xqts tests still run? I guess we are waiting for the new suite, initiated by @adamretter ?

**Comment by ljo** [comment]
Added a commit with 3 unit tests showing how this version passes all, both fn:lang#1, context version, and fn:lang#2, parameter version, with both attribute and element nodes.

**Comment by dizzzz** [comment]
Great, thnx! 

For future tests you might want to consider writing an xquery testsuite ( http://exist-db.org/exist/apps/doc/xqsuite.xml#D1.2.7 ).

**Comment by ljo** [comment]
Yes, we should think about how to proceed with double test systems (junit, xqsuite).

**Pull request merged**
