### PR TITLE
[bugfix] Avoid potential NPE in serializer when issues

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by dizzzz** [comment]
Possiboy related to https://github.com/eXist-db/exist/issues/177 and https://github.com/eXist-db/exist/issues/166

**Comment by dizzzz** [comment]
@adamretter do you have an idea under which conditions a NPE can happen?
The code is an improvement for sure

**Comment by adamretter** [comment]
@dizzzz If you have a screwed up dom.dbx/collection.dbx then this can trigger it.

**Comment by dizzzz** [comment]
Any idea on my questions of re: 177 en 166 ? In the tracelog there are the line nrs you have changed.

**Comment by adamretter** [comment]
@dizzzz My changes, will not solve your issue. `null` is still potentially passed to the Lucene index after line 203.

**Pull request merged**
