### PR TITLE
Refactor/remove deprecated

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/exist/pull/1930
Closes https://github.com/eXist-db/exist/issues/1716
Closes https://github.com/eXist-db/exist/issues/1510
Closes https://github.com/eXist-db/exist/issues/582

This PR removes:

1. Obsolete and/or Abandoned XQuery extension modules
2. Abandoned/Undocumented/Unused extension modules
3. Deprecated XQuery functions for which there are replacements
4. Deprecated internal APIs where a better option exists

### CODE REVIEW

**Comment by duncdrum** [comment]
@adamretter 933a761 does not seem to belong here

**Comment by adamretter** [comment]
CI is green. So what are we waiting for?

**Comment by adamretter** [comment]
Docs are here - https://github.com/eXist-db/documentation/pull/317

**Comment by duncdrum** [comment]
changes to the WAR file weren't on my docs PR, needs another.

**Comment by dizzzz** [comment]
@adamretter needs (simple) rebase

**Comment by dizzzz** [comment]
@adamretter @wolfgangmm I personally like the removal of the WAR generation! but it might impact some old users. The containment is.... use a docker container?

**Comment by adamretter** [comment]
As requested I removed the WAR stuff from the docs - https://github.com/eXist-db/documentation/pull/318

**Pull request merged**
