### PR TITLE
(5.0.0) Fix a serialization issue with util:eval-and-serialize

### PR DESCRIPTION
**Pull request by adamretter**
Forward port of https://github.com/eXist-db/exist/pull/2453

### CODE REVIEW

**Comment by joewiz** [comment]
@eXist-db/core The other PRs with this change, https://github.com/eXist-db/exist/pull/2453 and https://github.com/eXist-db/exist/pull/2455, have both passed all CI checks. Only this one fails appveyor. Can someone trigger a re-run of appveyor please?

**Comment by adamretter** [comment]
@joewiz Okay I have re-triggered

**Comment by joewiz** [comment]
Ugh, failed again. Is the failure significant?

**Comment by dizzzz** [comment]
some build instabilities will be solved with https://github.com/eXist-db/exist/pull/2456 ; not this one however

**Comment by adamretter** [comment]
@joewiz Currently showing that AppVeyor and Travis passed.

The problem previously was downloading dependencies.

**Pull request merged**
