### PR TITLE
Fix missing build.properties in jarsigner.xml

### PR DESCRIPTION
**Pull request by jonjhallettuob**
Thank you for your contribution to the eXist-db codebase! We will review your changes and pull them in when the project agrees with them and if the project benefits from it, content and quality wise.

To be able to judge the Pull Request (PR) please be sure the following is present

- A (short) description of the content of changes.
- A context reference to e.g. a [Github Issue](https://github.com/eXist-db/exist/issues), a message in the  [eXist-open mailinglist](http://exist-open.markmail.org) or a [specification](https://www.w3.org/TR/xquery-3/).

Additionally please add a few tests to the PR. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) (XQuery - Run as Test)

> When the PR is filed, the complete PR will be tested using [travis-ci](https://travis-ci.org/eXist-db/exist), the build status is visible in the PR. Note that only a limited number of tests are executed (smoketest).

Please run the *full* junit testsuite before filing the PR! This can be done with `build.sh test` which generates a HTML report.

------

### CODE REVIEW

**Comment by joewiz** [comment]
Will you be filling in the template or providing some details or fuller description?

**Comment by adamretter** [comment]
@jonjhallettuob Can you tell us a little bit about why you need this? It seems to me on my system at least if I set properties in `local.build.properties` then they are used by the jarsigner target. For example I typically set:

```
keystore.file=...
keystore.alias=...
keystore.password=...
```

**Comment by jonjhallettuob** [comment]
Sorry, this is just showing my complete ignorance of building Java apps :-)

The background to this is that I've built a Puppet module around Adam's
script in https://github.com/adamretter/puppet-exist. I'd just copied
local.build.properties verbatim from that. I'll add the keystore to
local.build.properties in my Puppet module.

Thanks for your help,

Jon.

---
Jon Hallett
Senior Systems Administrator
IT Services
Research IT
University of Bristol
Beacon House
+44 (0)117 394 1619

**Comment by jonjhallettuob** [comment]
I've fixed the Puppet module, and it now happily signs the jars. Thanks again for your pointers.

Jon.

**Comment by adamretter** [comment]
@jonjhallettuob No problem, thanks for your contributions :-)

**Pull request closed without merging**
