### PR TITLE
sweeping old FT index staff

### PR DESCRIPTION
**Pull request by shabanovd**

### CODE REVIEW

**Comment by ljo** [comment]
I am testing this. I don't want the change in src/org/exist/indexing/IndexController.java though, since that public addIndexWorker() is the only way right now, from what I can see, to add expath indexing libraries. I was going to change the comment to reflect this when your changes came in. So the comment still needs be changed.

**Comment by adamretter** [comment]
@ljo I am not aware of any EXPath indexing modules?

**Comment by ljo** [comment]
@adamretter I am trying to push some out. Firstly a sparql one. But I need to overcome these registration obstacles before it can be released.

**Comment by adamretter** [comment]
@ljo interesting :-)

**Comment by shabanovd** [comment]
@ljo I was think exactly the same, but I was not sure that it do all required preparations.

There is the method 'IndexManager.registerIndex' that fit must better https://github.com/shabanovd/exist/blob/RC-no-move-fix/src/org/exist/indexing/IndexManager.java#L107

I'll make PR for that.

**Comment by ljo** [comment]
OK. Thanks.

**Comment by adamretter** [comment]
@ljo Does that mean you are happy with @shabanovd's change? If so I would be happy to review this and then perhaps merge

**Comment by ljo** [comment]
Merged after some manual resolutions.

**Pull request closed without merging**
