### PR TITLE
Db corruption after delete of resource under /db/config/*

### LINKED ISSUE #345: Fluent: NPE in Trigger.java (junit)
While running the junit/fluents tests, there are stacktraces visible; the tests pass nevertheless. This is the NPE, but there is more.

```
   [junit] 2014-09-29 21:27:14,968 ERROR [org.exist.collections.triggers.Trigger] : 
    [junit]  java.lang.NullPointerException
    [junit] 	at org.exist.dom.ElementImpl.getFirstChild(ElementImpl.java:959)
    [junit] 	at org.exist.config.ProxyNode.getFirstChild(ProxyNode.java:91)
    [junit] 	at org.exist.config.ConfigurationImpl.cache(ConfigurationImpl.java:125)
    [junit] 	at org.exist.config.ConfigurationImpl.getProperty(ConfigurationImpl.java:169)
    [junit] 	at org.exist.config.ConfigurationImpl.equals(ConfigurationImpl.java:463)
    [junit] 	at java.util.concurrent.ConcurrentHashMap.containsValue(ConcurrentHashMap.java:1066)
    [junit] 	at org.exist.config.Configurator.unregister(Configurator.java:1304)
    [junit] 	at org.exist.config.ConfigurationDocumentTrigger.afterDeleteDocument(ConfigurationDocumentTrigger.java:211)
    [junit] 	at org.exist.collections.triggers.DocumentTriggers.afterDeleteDocument(DocumentTriggers.java:326)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1546)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.fluent.Folder.delete(Folder.java:929)
    [junit] 	at org.exist.fluent.FolderTest.deleteRoot1(FolderTest.java:328)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    [junit] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:532)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1165)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1016)
```

### PR DESCRIPTION
**Pull request by shabanovd**
close #345

### CODE REVIEW

**Comment by ljo** [comment]
Looks ok.

**Comment by dizzzz** [comment]
so the changes is after --> before?

**Comment by ljo** [comment]
Yes, the rest is exception merging basically.

**Comment by shabanovd** [comment]
yes, because after remove there is no document anymore and that did lead to NPE at configurator

**Comment by adamretter** [comment]
Hmm, I can see a possible problem with this.

Two case:
1. If deleting a document fails.
2. Deleting a document is aborted; It could be prevented by a subsequent trigger.

Then in that instance you would have an unconfigured instance. I think rather you have to gather all of the information you need to unconfigure the instance in the *beforeDelete* step, and then use that in the *afterDelete* step.

**Comment by shabanovd** [comment]
or that trigger must be always last one

**Comment by shabanovd** [comment]
also, use triggers to abort operation *is* design bug, no? I use different interface to avoid problems you describe.

**Comment by adamretter** [comment]
Using a trigger to abort a delete between *before* and *after* is a valid use-case and one that we have promoted in the past.

I don't think making the Configuration trigger the last in the chain will work, as when configuring as opposed to unconfiguring it needs to be the first in the chain I think.

**Comment by shabanovd** [comment]
nope, I did not promote. And more to that exception in triggers lead to db corruption.

**Comment by adamretter** [comment]
@shabanovd I was not saying that *you* promoted it. I said *we* promoted it, as in the eXist project and/or community.

**Comment by shabanovd** [comment]
I'd say you promote it and I and @wolfgangmm point that it wrong.

**Comment by shabanovd** [comment]
here an example of DoAbort exception design https://github.com/shabanovd/exist/commit/f84649da0f7770c2ee5d764a8022ba109cbc02d5

**Comment by shabanovd** [comment]
@wolfgangmm Can this be merged? That do fix db corruption issue happening each time resource deleted. @adamretter point that it lead design bug that have low probability.

**Comment by adamretter** [comment]
I am worried we are trading one bug for another. Can we not fix the underlying issue?

**Comment by shabanovd** [comment]
@adamretter, you're saying that simple workaround that low db corruption from probability 1 to 0 is not good because it raise probability of configuration inconsistence on less then +0.001

The bug that keep db corruption probability on 1.0 is much better?

**Comment by adamretter** [comment]
@shabanovd No, of course I am not saying that. This patch should be merged if it improves things, but I don't want the real problem to be lost or ignored.

**Comment by wolfgangmm** [comment]
If this is an emergency fix for a real corruption issue, I'll apply it, even if it is just a temporary solution. However, this means we should not forget about it after the fix has been applied. Maybe an issue should be opened as a reminder?

**Comment by shabanovd** [comment]
@wolfgangmm thanks. @adamretter describe theoretical design bug, but reality a bit different, eXist will get corrupted if remove operation do not finish "normally". So, that is more eXist's general design bug and just in background configurator design bug. Solving 2nd without fix 1st is nothing.

**Pull request merged**
