### PR TITLE
[5.x.x] Backport build scripts

### PR DESCRIPTION
**Pull request by reinhapa**
Backport `develop` Github actions

### CODE REVIEW

**Comment by adamretter** [comment]
We should probably exclude exist-xqts from this, as it isn't really designed still to work with eXist-db 5.x.x

**Comment by reinhapa** [comment]
> We should probably exclude exist-xqts from this, as it isn't really designed still to work with eXist-db 5.x.x

Ok, that's fine for me. I will tidy up the commits accordingly..

**Comment by adamretter** [comment]
> Do you have any ideas about the failing dependency check though?

I am afraid not, my only observation is that it is trying to download it rather than use the built artefact from the local repo

**Comment by line-o** [comment]
Even though that there still seems to be an issue with dependency checks I would want to merge this PR as it brings back test execution to 5.x.x

**Review by line-o — APPROVED** [review]
Dependency checks should be addressed but can be done in a separate PR

**Comment by line-o** [comment]
@reinhapa you made it! All green. Good work.

**Review by adamretter — APPROVED** [review]
LGTM

**Pull request merged**
