### PR TITLE
Fix GitHub Actions for SonarCloud

### PR DESCRIPTION
**Pull request by adamretter**
Fixes the SonarCloud integration with GitHub Actions.

**NOTE**: Previously SonarCloud Automated Analysis, and Manual Analysis (i.e. via CI) were enabled. You can only use one. Automated Analysis is not supported for Java projects, and so I disabled that in the SonarCloud dashboard. I believe it was the automated analysis that was previously (incorrectly) reporting 100% green for everything.

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz Okay do the NPE that you were seeing in the GitHub action build are of two types:

1.
```java
java.lang.NullPointerException
	at org.exist.xquery.AbstractInternalModule.binarySearch(AbstractInternalModule.java:138)
	at org.exist.xquery.AbstractInternalModule.getFunctionDef(AbstractInternalModule.java:120)
	at org.exist.xquery.FunctionFactory.getInternalModuleFunction(FunctionFactory.java:311)
	at org.exist.xquery.FunctionFactory.functionCall(FunctionFactory.java:282)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:111)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:61)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:57)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:11206)
```

2.
```
java.lang.NullPointerException
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6290)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5291)
	at org.exist.xquery.parser.XQueryTreeParser.libraryModule(XQueryTreeParser.java:3979)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3810)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3591)
	at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2628)
	at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2569)
	at org.exist.xquery.XQueryContext.importModuleFromLocation(XQueryContext.java:2525)
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2432)
	at org.exist.xquery.functions.inspect.InspectModule.eval(InspectModule.java:77)
```

Having done a quick analysis, it looks to me like they are both caused by the same problem. The problem being that one-of-more entries in the `AbstractInternalModule#mFunctions` array are null.

I do not yet know why or how that could be the case; I will look deeper...

**Review by dizzzz — APPROVED** [review]

**Comment by adamretter** [comment]
Okay a little further progress, the code:

yields:
```java
        } catch (final NullPointerException e) {
            System.out.println("***ADAM*** NPE thrown in: " + getNamespaceURI());
            final int len = mFunctions == null ? 0 : mFunctions.length;
            for (int i = 0; i < len; i++) {
                final FunctionDef functionDef = mFunctions[i];
                final FunctionSignature functionSignature = functionDef == null ? null : functionDef.getSignature();
                final String ref = functionSignature == null ? "null" : functionSignature.getName().toString() + "#" + functionSignature.getArgumentCount();
                System.out.println("" + i + ": " + ref);
            }
            throw e;
        }
```

```
***ADAM*** NPE thrown in: http://exist-db.org/xquery/inspection
0: inspect:inspect-function#1
1: inspect:inspect-module#1
2: inspect:inspect-module-uri#1
3: null
4: null
5: null
```

**Comment by adamretter** [comment]
@dizzzz I think that this might be working now, but I would prefer that we merge https://github.com/eXist-db/exist/pull/3751 first.

**Comment by adamretter** [comment]
@dizzzz @duncdrum @line-o I think this one is now ready to merge.

**Comment by line-o** [comment]
@adamretter yes looks good. Only the newly added check now finds 9 code smells. What do you think, should they be addressed here as you already did in part?

**Comment by adamretter** [comment]
@line-o I think as those issues were present long before enabling SonarCloud, they can be fixed in a different future PR.

**Comment by line-o** [comment]
SonarCloud says 5 of those are from 7 days ago. I fear that
a) these will never be addressed
b) all rebase PRs will have score D

**Comment by adamretter** [comment]
> SonarCloud says 5 of those are from 7 days ago.

@line-o Presumably that is when the first complete scan was completed!

>  I fear that
> a) these will never be addressed
> b) all rebase PRs will have score D

If someone addresses them, then they will be addressed. I am not sure what the plan is, or if there is a plan for addressing these. Perhaps @dizzzz has something in mind, I am not sure.

**Pull request merged**
