### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by adamretter**
@dizzzz Here we go! :-)

**TODO(AR)** have `FastByteArrayOutputStream` return an unsycnhronized `FastByteArrayInputStream` when calling `toInputStream`...

# Rules

1. Prefer `org.apache.commons.io.output.ByteArrayOutputStream` over `java.io.ByteArrayOutputStream`.
	
2. When possible provide a size hint to `ByteArrayOutputStream(size)`
     1. Pay attention to difference in initial sizing: `commons.io.output.ByteArrayOutputStream(1024)` vs `java.io.ByteArrayOutputStream(32)`
	
3. Note that `commons.io.output.ByteArrayOutputStream` and `java.io.ByteArrayOutputStream` are thread-safe, when writing non-concurrent code, instead prefer `org.exist.util.io.FastByteArrayOutputStream` which is a non-thread safe port of `commons.io.output.ByteArrayOutputStream`.

4. Note that calling `toByteArray` on either `org.exist.util.io.FastByteArrayOutputStream`, `commons.io.output.ByteArrayOutputStream`, or `java.io.ByteArrayOutputStream` will result in a copy of the data, so the size requirement is 2x the content of the `OutputStream`.
    1. If the follow-on destination for the data is another `OutputStream`, consider calling `writeTo(OutputStream)` instead of `toByteArray()`.
    2. If the follow-on destination for the data is an `InputStream`, `FastByteArrayOutputStream` and `commons.io.output.ByteArrayOutputStream` also provide `toInputStream()` and `toBufferedInputStream()` methods.

5. When reading from an `InputStream` to a `ByteArrayOutputStream`, consider the method `write(InputStream)` on either `FastByteArrayOutputStream` or `commons.io.output.ByteArrayOutputStream`.

6. Avoid `org.apache.commons.io.IOUtils.copy(...)`.

7. When the size is known in advance, don't use a `ByteArrayOutputStream`, use a `ByteBuffer` or `sun.misc.Unsafe`.

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz This wasn't ready to be merged - hence the "In Progress" label and the TODO in the PR.

**Comment by adamretter** [comment]
It's okay though I can always send a follow-up PR

**Comment by dizzzz** [comment]
Oops @adamretter my apologies ; I missed the "in progress label" and interpreted "TODO(AR) " as a long term thinghy :-(

**Comment by dizzzz** [comment]
I guess I was a bit too focussed on getting the tests on macos running at travis

**Pull request merged**
