### PR TITLE
(4.x.x) Update Eclipse classpath to fix compilation

### PR DESCRIPTION
**Pull request by reinhapa**
### Description:
Fixes the Eclipse workspace compilation by adding missing source folders and correcting referred libraries within the `.classpath` file.

### CODE REVIEW

**Comment by adamretter** [comment]
@reinhapa Could you also prepare similar PRs for `develop-5.0.0` and `develop-4.x.x` please?

**Comment by reinhapa** [comment]
@adamretter the current one is done for `develop-4.x.x` but I sure can prepare one for the `develop-5.0.0` and `develop` itself...

**Comment by adamretter** [comment]
@reinhapa great thanks :-)

**Comment by dizzzz** [comment]
Is this PR now a mix of unplanned commits?

**Comment by reinhapa** [comment]
@dizzzz no, it should only contain the `deveop-4.x.x` changes went in between the time I started the PR. It should be the only contain the `.classpath` and the `XQDocTests.java` having a wrong package name...

**Comment by dizzzz** [comment]
it is looking ok now :-)

**Comment by adamretter** [comment]
I don't understand why there are 15 commits in this PR?

**Comment by dizzzz** [comment]
woops I missed that ; probably a fix on a fix?

**Comment by reinhapa** [comment]
@dizzzz just  fixed the branch.

**Pull request merged**
