### PR TITLE
Added util:line-number()

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by shabanovd** [comment]
@adamretter what is the purpose of such function? you always know line number where it placed, no?

**Comment by adamretter** [comment]
It's for knowing the line-number at runtime when collecting debug info within an XQuery.

**Comment by shabanovd** [comment]
@adamretter here was discussion but it disappear now ... anyway, I still can't understand how line number of `util:line-number()` will help you ... do I missing something?

**Comment by adamretter** [comment]
@shabanovd Here is how I am using it:

```xquery
declare function assert:equals($expected as item(), $actual as item(), $line-number as xs:integer) {
    if($expected ne $actual) then
        fn:error(xs:QName('assersion'), 'Expected ' || $name || ', but actually ' || $actual || ' at ' || $line-number)
    else()
};
```

Consider the use of the above function for making assertions:

```xquery
...
assert:equals("x", "y", util:line-number())
...
```

**Comment by dizzzz** [comment]
@adamretter the PR has now a merge conflict :-(

**Comment by adamretter** [comment]
@dizzzz I just rebased... should be good now :-)

**Comment by adamretter** [comment]
@dizzzz Mergy mc-merge?

**Pull request merged**
