### PR TITLE
(5.0.0) Fix javadoc

### PR DESCRIPTION
**Pull request by adamretter**
To release, Maven enforces that the Javadoc that we have must be valid.

Unfortunately much of eXist-db's Javadoc is junky. There are thousands of syntax errors in our Javadoc. I have now fixed a large ammount of issues (>2000), which took a couple days, but this is a big job, and there is still a long way to go :-(

We could of course just delete all the invalid Javadoc, but there is actually quite some value in keeping it, as the syntax problems tend to be small ommitted items. There is just a huge amount of them, as eXist-db never had any Javadoc validation process before when we used Ant.

I am opening this PR (Work in Progress), and I am hoping others will help too. That means you!

[Here is a list of the remaining ~2,199 Javadoc issues](https://gist.github.com/adamretter/08c4a8e45dfe99b6b6f8003f5ea2d0be). Please ignore any related to `<pre>` blocks as I plan to fix those at the end. If you would like to contribute, please claim a set of line numbers from the error list and work on those by contributing commits to this PR.

When claiming a set of line numbers, please add a comment with the line numbers below so we don't duplicate work!

### CODE REVIEW

**Comment by duncdrum** [comment]
see eXist-db/documentation#140

**Comment by dizzzz** [comment]
We need to exclude the generated code:

- exist-core/target/generated-sources/antlr/org/

**Comment by line-o** [comment]
I started to make changes to `exist-core/src/main/java/org/exist/xquery/value/SequenceType.java`

**Comment by wolfgangmm** [comment]
Is there a way to run the checks via maven, so I can see where we are?

**Comment by adamretter** [comment]
@Wolfgang `mvn javadoc:javadoc`

**Comment by wolfgangmm** [comment]
ok, working through `org/exist/xquery/` then...

**Comment by windauer** [comment]
I'm fixing the JavaDoc in org.exist.config ..

**Comment by windauer** [comment]
now org/exist/collections/ - this will take a moment

**Comment by windauer** [comment]
now exist-core/src/main/java/org/exist/source

**Comment by windauer** [comment]
now in exist-core/src/main/java/org/exist/dom/

**Comment by wolfgangmm** [comment]
I'll continue with org.exist.xquery.value...

**Comment by line-o** [comment]
Will start with org.exist.xmlrpc.RpcAPI

**Comment by windauer** [comment]
will work on exist-core/src/main/java/org/exist/indexing

**Comment by windauer** [comment]
next /org/exist/storage .. what a never ending story ;(

**Comment by adamretter** [comment]
Okay we are down to 655 errors now.

You can check this by running: `mvn javadoc:javadoc | grep "\[ERROR\] /Users/aretter/code/exist" | wc -l` (...obviously update the path appropriately for your machine!)

**Comment by adamretter** [comment]
I have org.exist.http

**Comment by windauer** [comment]
down to 225 errors now.. we are getting there...

**Comment by windauer** [comment]
I go on with org.exist.xmlrpc

**Comment by windauer** [comment]
not test/TransactionTestDSL.java and org.exist.debugger - the last ones if @adamretter is done with http and xupdate

**Comment by windauer** [comment]
omg.. that was all only exist-core..  now the extension modules are failing .. what a never ending story.. I there away to tell maven go on creating the javadoc for all modules, to get an impression how many stuff to come? Currently maven stops after the first module with javadoc issues.

**Comment by line-o** [comment]
Very good question from @brihaye 
Could you provide a link to the line in the code?
That looks like a bug, but maybe this works for some reason. It does compile which is already surprising.

**Comment by line-o** [comment]
building this branch results in
```
[ERROR] /Users/jll/customers/exist/add-test/exist-core/src/main/java/org/exist/http/servlets/HttpResponseWrapper.java:[126,40] cannot find symbol
[ERROR]   symbol:   variable arg0
```
maybe related to @brihaye question

**Comment by adamretter** [comment]
@eXist-db/core this is now ready to land...

**Comment by joewiz** [comment]
Travis and AppVeyor show the same error:

```
[ERROR] Failures: 
[ERROR]   TransformTest.transform:43 expected:<...doc>Start Template 1[
Start Template 2
Template 3End Template 2
]Template 3End Templa...> but was:<...doc>Start Template 1[Start Template 2Template 3End Template 2]Template 3End Templa...>
[ERROR]   AdditionalJingXsdRngTest.testValidateRNGwithJing:137 expected:<[tru]e> but was:<[fals]e>
[ERROR]   AdditionalJingXsdRngTest.testValidateXSDwithJing:69 expected:<[tru]e> but was:<[fals]e>
[ERROR] Errors: 
[ERROR]   XmlRpcTest.testQueryWithStylesheet:475 » SAXParse Content is not allowed in pr...
[ERROR]   MarshallerTest.startDB:164 » SAX The XML parser reported a problem: fatal erro...
```

**Pull request merged**
