### PR TITLE
(4.x.x) Small code improvement with Object.equals

### PR DESCRIPTION
**Pull request by sten1ee**
Thank you for your contribution to eXist-db! 

To help the community judge your pull request (PR), please include the following:

- A (short) description of the content of changes.
- A context reference to a [Github Issue](https://github.com/eXist-db/exist/issues), a message in the [eXist-open mailinglist](http://exist-open.markmail.org), or a [specification](https://www.w3.org/TR/xquery-31/).
- Tests. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) via XQuery > Run as Test.

Your PR will be tested using [Travis CI](https://travis-ci.com/eXist-db/exist) and [AppVeyor](https://ci.appveyor.com/project/AdamRetter/exist) against a number of operating systems and environments. The build status is visible in the PR. 

To detect errors in your PR before submitting it, please run eXist's full test suite on your own system via `build.sh test`.

------

### CODE REVIEW

**Comment by sten1ee** [comment]
It's a mystery to me why Appveyor failed that build: 
```
Environment: APPVEYOR_BUILD_WORKER_IMAGE=Ubuntu1804, JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
```
I don't think it has something to do with the changes I've introduced.

**Comment by adamretter** [comment]
@sten1ee Don't worry about that one

**Comment by adamretter** [comment]
@sten1ee could you also open a backport PR against the `develop` branch please?

**Comment by sten1ee** [comment]
Mmm, shame on me, but I don't know how to open a backport PR against develop branch.
This is what I thought it should be like (but it isn't):
image

**Comment by adamretter** [comment]
You need to create a new branch from the `develop` branch, cherry-pick over you commit, and then open a new PR from that branch, against `develop`.

**Comment by sten1ee** [comment]
There we go: https://github.com/eXist-db/exist/pull/2904/

**Pull request merged**
