### PR TITLE
Fix issues with IzPack and shutdown on Windows

### PR DESCRIPTION
**Pull request by adamretter**
As reported by Dominic Martin on the exist-open mailing list.

### CODE REVIEW

**Comment by dizzzz** [comment]
the other build of 4.x.x was ok, but for this build I see

image

**Comment by adamretter** [comment]
@dizzzz actually I am wondering if I introduced an issue with the lock events. I think the `LockTable` needs to become per-`BrokerPool`. It is likely that we start and destroy `BrokerPools` within the same VM, but that the LockTable processor is destroyed when the first BrokerPool is, and never recreated - which could lead to us collecting lots of lock events which are never processed.

**Comment by adamretter** [comment]
@dizzzz Assuming CI passes, I think this is now good to go.

**Comment by dizzzz** [comment]
off and on some tests fail, ut in general I think the PR is OK..

**Comment by duncdrum** [comment]
codacy discovered an unused import, that you might want to remove

**Comment by adamretter** [comment]
@dizzz indeed I think the CI failures are transient.

@duncdrum okay, I have made that that change. Thanks

**Pull request merged**
