### PR TITLE
[build test] use -Dmaven.resolver.transport=wagon

### PR DESCRIPTION
**Pull request by dizzzz**
testing `-Dmaven.resolver.transport=wagon` to avoid download issues maven 3.9 

ref: https://questdb.io/blog/maven-troubleshooting-open-source/ 

image

### CODE REVIEW

**Comment by line-o** [comment]
Nice! Now the tests on windows do fail because of an unknown goal `.resolver.transport` 
Maybe the parameter name needs to be escaped somehow.

**Comment by line-o** [comment]
@dizzzz from what I gather on StackOverflow you could try
`-D"parameter_key"="parameter_value"` or `"-Dparameter_key=parameter_value"`

**Comment by line-o** [comment]
Much better!
Now we are back to "normal" flaky tests on windows: https://github.com/eXist-db/exist/actions/runs/4323427743/jobs/7547021481#step:4:9096

**Review by line-o — APPROVED** [review]
Thanks @dizzzz!

**Comment by joewiz** [comment]
A string of checks green, never before seen!

Thanks, @dizzzz!

**Review by duncdrum — APPROVED** [review]

**Pull request merged**
