### PR TITLE
Fix compilation issue with JAXB dependencies on JDK 11+

### PR DESCRIPTION
**Pull request by adamretter**
Fixes a transient dependency issue on JAXB which appears on JDK11+ which was revealed by https://github.com/eXist-db/exist/pull/3605

JAXB is no longer part of modern JDKs. This moves us to JAXB 3.0.0 which is now an external dependency by the Jakarta project.

This should work with JDK 8+

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
image

**Review by dizzzz — CHANGES_REQUESTED** [review]
Build issues :-(

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
thnx... I was not able yet to look into the details

**Comment by adamretter** [comment]
Thanks for the merge @dizzzz

**Pull request merged**
