### PR TITLE
[bugfix] fixes #4045 by pool create non pooled instances if exhausted

### LINKED ISSUE #4045: [BUG] Restore of backup file stops : parser pool issue
Whilst restoring a full.zip backup file, the restore process halts; stack shows that it might be related to parser pooling;

# how to reproduce
- obtain backup
  - create backup
    - start database
    - fill with applications
    - create backup 
    - stop database
    - clean `data/*` folder
  - or download backup file from https://www.dropbox.com/s/2ou33s0ms8x1vw9/full20210925-1600.zip?raw=1 
- restore database
  - start `client.sh -l` and restore created backup file.
  - restore process stops :-(

# details 
```
"java-admin-client-0.restore" #49 prio=6 os_prio=31 tid=0x00007f9ef9374800 nid=0x1674b waiting on condition [0x0000700003dae000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0d9b738> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:1323)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at org.exist.util.XMLReaderPool.borrowXMLReader(XMLReaderPool.java:65)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:424)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.Restore.restore(Restore.java:97)
	at org.exist.xmldb.LocalRestoreService.lambda$0(LocalRestoreService.java:58)
	at org.exist.xmldb.LocalRestoreService$$Lambda$666/665967369.applyXmldb(Unknown Source)
	at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:48)
	at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:265)
	at org.exist.xmldb.LocalRestoreService.restore(LocalRestoreService.java:56)
	at org.exist.client.ClientFrame.lambda$39(ClientFrame.java:1130)
	at org.exist.client.ClientFrame$$Lambda$665/665306664.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

[stack.txt](https://github.com/eXist-db/exist/files/7229858/stack.txt)

### PR DESCRIPTION
**Pull request by reinhapa**
### Description:
Exhausted pool creates non pooled instances
 
- the maximum pool entries will be set to 2 times the max idle amount
- in case the pool gets over the maximum pool entries one-time-only  instances will be created not be managed by the pool intance
- improved the JMX bean name to be under org.exist.management.exist
- 
fix for https://github.com/eXist-db/exist/issues/4045

### CODE REVIEW

**Comment by adamretter** [comment]
@reinhapa Hi Patrick you don't need to create one time instances in this manner, the equivalent can be done with a simple config option. What is the issue that you are seeing where the pool is being exhausted? could this be due to a resource leak that needs to be fixed instread?

**Comment by reinhapa** [comment]
@adamretter When testing using the restore using the given backup file there was no reader leak, but checking it with JMX it 
revealed that in this case there where 9 instances in use during restore concurrently. 

Also I did not found any option to achieve the one time instance approach, so if you could can point me to the according option I happily remove that part  😊

**Comment by dizzzz** [comment]
I think the concurrency has to de with the nesting of the collections, as where the __collection __.xml documents are still read/open.

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
I could also not find the config item you mentioned @adamretter

**Comment by adamretter** [comment]
@reinhapa I have bought your fixes together with my tests, and a couple small adjustments in a new PR - https://github.com/eXist-db/exist/pull/4052 I have kept your commits and attributed them to you in the new PR, thanks :-) I think if we merge #4052 we can then close this one - but please take a look and let me know...

**Pull request closed without merging**
