### PR TITLE
Simplify the RESTXQ caching model to prevent leakage of tmp files.

### PR DESCRIPTION
**Pull request by Infiniverse**
Fix a tmp file leakage into the RESTXQ code for PUTs and POSTs.

The HttpServletRequestAdapter was presuming that consumers would know how to release the cached input stream properly - never a good idea. It ought to own it's own resources and have them released as part of it's lifecycle. That way no-one can use it incorrectly! :)

### CODE REVIEW

**Comment by dizzzz** [comment]
Did we forget this PR?

**Comment by adamretter** [comment]
Ah yeah sorry. I will get it back on to the todo list

On 21 October 2015 at 21:44, Dannes Wessels <notifications@github.com>
wrote:

> Did we forget this PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/pull/213#issuecomment-150019202>.
>



-- 
Adam Retter

skype: adam.retter
tweet: adamretter
http://www.adamretter.org.uk

**Comment by dizzzz** [comment]
@adamretter this is still open in the restxq context....

**Comment by Infiniverse** [comment]
Hey folks, untimely attention to this issue is one of the main reasons that I dropped ExistDb. Sorry.

**Comment by duncdrum** [comment]
can this be salvaged or do we need to close?

**Comment by adamretter** [comment]
This needs to be reconsidered and fixed in a different manner. Will roll this up into the future fix.

**Pull request closed without merging**
