### PR TITLE
XQSuite+XSuite was not correctly reporting all test failures

### PR DESCRIPTION
**Pull request by adamretter**
This fixes an issue raised by @dizzzz where not all test failures were reported from XQSuite correctly, which caused XSuite to show tests as passing when they were actually failing.

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz Oh man! This is bad...

Some of these failing tests go back quite some time. For example, `test/src/xquery/xmlid.xml` which @wolfgangmm added, first appeared in eXist-db 4.1.0. When I run it with XQSuite on 4.1.0 it gives the same failures I see on 4.3.1 and 5.0.0-RC3. If I try it on 4.0.0 it also give failures (some different some the same).

**Comment by adamretter** [comment]
So the 124 tests that are failing:

* xquery: 13 failures
* xquery.lucene: 1 failure
* xquery.optimizer: 37 failures
* xquery.range: 72 failures
* xquery.xquery3 1 failure

**Comment by wolfgangmm** [comment]
The majority of tests fails because %test:stats seems to have stopped working. Can't yet see why.

**Comment by adamretter** [comment]
@wolfgangmm Indeed the index and optimisation tests seem to have an issue with that.

**Comment by duncdrum** [comment]
this needs a rebase

**Comment by adamretter** [comment]
@wolfgangmm I know you were working on fixes for this. Is it okay for you if I rebase this as @duncdrum suggested, or is it easier for you if we hold off?

**Comment by wolfgangmm** [comment]
@adamretter yes, I would welcome if you rebase

**Comment by adamretter** [comment]
@wolfgangmm done!

**Comment by wolfgangmm** [comment]
Status update: lxm:import-from-classpath, query-field-context, positional-nested.xql are still in need to be fixed as far as my count goes.  I would welcome some help after spending quite some time on this PR. Most of the tests were not written by myself, so it's tedious to hunt down the failures.

**Comment by adamretter** [comment]
I read the minutes from the community call - I don't think we should merge this until we fix all the issues. In my experience when test are marked as "ignored" or "pending" the problems never get fixed. I will see if I can find some time to help fix the underlying problems.

**Comment by joewiz** [comment]
@adamretter Ah, great, you saw the call notes from yesterday’s call. The plan, as you saw, is for @wolfgangmm and @dizzzz to (1) mark remaining failing tests as pending, (2) create issues out of each individual failure, and (3) merge this (and its ports) so that the PRs that rely on it can be merged. But if you are able to fix the failing tests, that would certainly be preferable, and I’m sure that would be greatly appreciated.

**Comment by tuurma** [comment]
It would be great to have all the failing tests fixed but it is clearly not a trivial job. It's already been months that some PRs are blocked so the course of action agreed on during last call seems more sensible to me unless @adamretter or anyone can offer a realistic timeline to bring remaining tests to order.

**Comment by line-o** [comment]
I second @joewiz and @tuurma . To not merge this in will create a bunch of stale branches. That these issues are visible is thanks to the fixed xqsuite in the first place. It is unsure if 

- the tests are valid
- ever would have passed.

Having them as separate issues is way more reasonable in order to enable further development.

**Comment by adamretter** [comment]
@tuurma @line-o I disagree.

My thinking is this, I found the bug and raised in on 3 Sep 2018, so it has now been 5 months and not all the issues have been fixed. However there was a reason to fix them, i.e. there is a genuine problem which is holding up development. If we mark them as pending/ignored, they will never be fixed.

I am happy to help on this, and I have already done so by fixing many of the issues.

However I am not happy to have the pending/ignored approach as it just means hiding bugs rather than investing the time to work on them.

Perhaps one solution is for @wolfgangmm and I to collaborate in real-time via teleconf for a few days or a week to actually fix the problems?

**Comment by line-o** [comment]
According to @wolfgangmm there are 6 tests that are still failing. For each of them an issue will be created with a mention of the pending test that will check the fix. 

They will then be

- visible
- can be worked on in parallel 

Therefore, the likelyhood, they will be fixed is actually higher since more people are made aware of them. They are not longer hidden in this completely separate issue.

**Comment by adamretter** [comment]
@line-o Yes I realised issues would be created. However, I still don't agree to that plan. In my experience, many issues are created and few are ever fixed. We can create new issues, but I don't believe they will be fixed.

**Comment by line-o** [comment]
Following this belief, it could mean this PR will never be merged. 
The fixes that are included in here and in other pending PRs blocked by this one will then not make it into the code base.
I do not see a reason to take fixes hostage to get others done.

**Comment by adamretter** [comment]
@line-o I have offered to work on the related bugs alongside other people... so let's focus on making that happen, and get this stuff fixed rather than sweeping it under the rug ;-)

**Comment by duncdrum** [comment]
if it weren't for the fact that we have 284 open issues, and we frequently have PRs fixing things without closing the relevant issues. I'd rather have the remaining 6 issues closed without marking things as pending and new issues being created to be addressed `later`

**Comment by adamretter** [comment]
I rebased this today and discovered we actually have 9 tests failing now. I will see if I can't fix some of these...

**Comment by adamretter** [comment]
Okay we are now down to just 3 failing tests...

I will try and spend some more time on this soon.

**Comment by adamretter** [comment]
Okay I fixed them all :-)

**Comment by wolfgangmm** [comment]
Fantastic news really! So let's pull this in once travis is done.

**Comment by dizzzz** [comment]
@wolfgangmm travis is green !

**Pull request merged**
