### PR TITLE
Further fixes to CI

### PR DESCRIPTION
**Pull request by adamretter**
Remove non-existent profile

### CODE REVIEW

**Comment by line-o** [comment]
Build still failing: something something `rename-jetty-etc-dir-for-appassembler`

**Review by dizzzz — APPROVED** [review]

**Comment by line-o** [comment]
@dizzzz what makes you approve the  changes? The build still fails

**Comment by line-o** [comment]
I think we have to wait for a moment since the last build failed with a request returning with HTTP status 429 Too many Requests

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
nice work!

**Comment by dizzzz** [comment]
@line-o I did approve the PR originally as the code looked ok to me (review=code inspection). I agree one could/should look at the build results too, but that is another obvious visible check right? So for me my Ok is really about I understand the code change (despite there are still issues)

**Comment by line-o** [comment]
I will merge this assuming that the minor issues reported by codacy will be addressed.

**Pull request merged**
