### PR TITLE
Use modification dates to extract only the resources that are newer than their destination files.

### PR DESCRIPTION
**Pull request by ptrckb**
When destination file already exists, it compares the timestamps of resource and destination file and, by default, extracts the resource only if it is newer than the destination file.

### CODE REVIEW

**Comment by adamretter** [comment]
@ptrckb Any update on this?

**Comment by ptrckb** [comment]
I thought it was the way the ant copy task was working but it seems I was wrong. I may try again later.

**Comment by line-o** [comment]
I would close this PR for now. It has been open for over 4 years with no further activity.

**Comment by joewiz** [comment]
@ptrckb Please feel free to open a new PR if you return to this.

**Pull request closed without merging**
