### PR TITLE
Support for resources in repo.xml

### PR DESCRIPTION
**Pull request by JoernT**
support for resources directories in repo.xml, if storing html fails try as binary in deployment.

repo.xml sample:
```
<?xml version="1.0" encoding="UTF-8"?>
<meta xmlns="http://exist-db.org/xquery/repo">
    <description>eXistdb some app</description>
    <author>eXist Solutions</author>
    <website/>
    <status>alpha</status>
    <license>BSD-2-Clause</license>
    <copyright>true</copyright>
    <type>application</type>
    <target>someapp</target>
    <resources path="bower_components" type="binary"/>
    <resources path="app/elements" type="binary"/>
</meta>
```

### CODE REVIEW

**Comment by dizzzz** [comment]
anyone?

**Comment by adamretter** [comment]
@dizzzz Sorry, I don't use packages... so this would really need to be looked at by someone who does.

**Comment by wolfgangmm** [comment]
This PR depends on some other changes by @zwobit. It won't work without them, so I'm waiting for his PR.

**Comment by zwobit** [comment]
Replaced by: https://github.com/eXist-db/exist/pull/836

**Pull request closed without merging**
