### PR TITLE
[fix] disable global restXQ trigger

### PR DESCRIPTION
**Pull request by line-o**
### Description:

This PR disables the restXQ trigger in collection.xconf.init. This is a breaking change as applications relying on this trigger to
be activated globally will have to add this trigger to their application's collection.xconf.

In my testing I was able to add two separate applications with both having the restXQ-trigger activated in their own
collection.xconf (both were based on https://gist.github.com/joewiz/28dd9b8454d14b4164a0). Modifying the code
showed up immediately when the exported routes were called with `/exist/restxq/{route}`. 

### Reference:

This trigger has led to several severe problems in the past with heap-memory exceptions when installing XAR-packages and 
hanging databases. There is also an unsolved issue with modules with circular dependencies.

- related #3448

### Type of tests:

In order to replicate my test you can check out this PR, build it and then create one or more test-applications using the template below.

```xquery
xquery version "3.1";

module namespace my-app = "http://my/app";

(: 
    Save this file into eXist anywhere (e.g., /db/restxq-template.xqm or 
    /db/apps/my-app/modules/restxq-template.xqm).
    
    Note that the collection configuration file where you store the module must invoke
    the restXQ trigger.

    Add a collection.xconf next to your script (or in any parent collection).
    It has to have the following trigger configuration (along with any other configurations).

        <collection xmlns="http://exist-db.org/collection-config/1.0">
            <triggers>
                <trigger class="org.exist.extensions.exquery.restxq.impl.RestXqTrigger"/>
            </triggers>
        </collection>
    
    run the handler with GET http://localhost:8080/exist/restxq/test
:)

declare namespace rest = "http://exquery.org/ns/restxq";
declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";

declare
    %rest:GET
    %rest:path("/test")
    %output:media-type("text/html")
    %output:method("html5")
function my-app:hello() {
    let $title := 'Hello world!'
    return
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>{$title}</title>
            </head>
            <body>
                <h1>{$title}</h1>
            </body>
        </html>
};
```

### CODE REVIEW

**Comment by adamretter** [comment]
As I previously stated to you @line-o in the public eXist-db Slack, I will not accept this change

**Comment by line-o** [comment]
I know

**Comment by line-o** [comment]
Here you have the chance to argue why this is still needed or what I have not thought about. Just not accepting it is a little shallow of an argument.

**Comment by adamretter** [comment]
Would you like me to copy and paste my arguments from Slack?

**Comment by line-o** [comment]
> Would you like me to copy and paste my points from Slack?

Yes, please do so.

**Comment by reinhapa** [comment]
> As I previously stated to you @line-o in the public eXist-db Slack, I will not accept this change

Hi @adamretter,
I tried to find the discussion about this but was not able to find it anymore. Could you explain what the problem is in your opinion as I do not really seem understand the actual problem with this change.

**Comment by dizzzz** [comment]
@adamretter  in exist index configuration for a collection is taken from the collection.xconf for that collection, or when missing the one from the most close by parent collection.xconf .
How does that work for triggers?

**Comment by duncdrum** [comment]
@line-o there is a test for docker using restxq. This will need to modified to either activate it by using a custom `conf.xml` for that temporary container; or disabled.

**Comment by line-o** [comment]
@duncdrum Yes I saw that. It would make better to adapt it. But before that I would like to come to an agreement if this is the way forward, which is the more complex part.

**Comment by windauer** [comment]
@adamretter in Slack you wrote that the people who are not using restxq should simply disable it. Problem with this approach is imho that endusers will not know whats the cause of their issues and that they should search for "disabling restxq". They will notice heavy RAM usage only due to installing a XAR (and eXist-db not freeing the RAM afterwards, even when you trigger a GC via Monex). Or that the installation of [frus](https://github.com/HistoryAtState/frus) takes 40min with a default eXist-db while it would take only 20min on the same machine with restxq disabled. In worst case they even step away from eXist-db without knowing that their issue could have simply been solved by disabling the restxq trigger. 
 
I would be all in for adding a "enable restxq" trigger to the app generator @duncdrum is maintaining and to add the information how and where to enable restxq prominent in the documentation but to disable it by default.

**Comment by line-o** [comment]
@StephanMa are you using restxq - annotating functions to route http traffic - or the REST-like API of exist?
The easiest way to distinguish them is by the URLs you are calling 
- `[/exist]/restxq/...` -> restxq
- `[/exist]/rest/...` -> REST-like API
This is about restxq and does not disable the REST-like API of exist.

**Comment by duncdrum** [comment]
See https://github.com/eXist-db/exist/pull/4855#issuecomment-1500203280

**Comment by adamretter** [comment]
#4855 is unrelated to this!

**Pull request closed without merging**
