### PR TITLE
make sure to unlock resource

### PR DESCRIPTION
**Pull request by shabanovd**
resource was not unlocked at all

### CODE REVIEW

**Comment by adamretter** [comment]
@shabanovd Please can you add a test case

**Comment by shabanovd** [comment]
It's unclear for me how to write test for it. @adamretter, please do, if you know how to.

**Comment by dizzzz** [comment]
I'd have no idea....

**Comment by adamretter** [comment]
@shabanovd @dizzzz This one is nice and easy, just call either `AuditTrailSessionListener#sessionCreated` or `AuditTrailSessionListener#sessionDestroyed` and afterwards check the lock state.

**Comment by dizzzz** [comment]
ok thnx for providing the hints. that helps.

**Comment by shabanovd** [comment]
To be clear my opinion that the owner of the feature must carry out tests, not me - contributor of bugfix for that feature. It related to other (my) PRs.

**Comment by adamretter** [comment]
@shabanovd It has always been the responsibility of those submitting code to also submit tests. It is even in our docs and have been for a long time, see https://github.com/eXist-db/exist/blob/develop/CONTRIBUTING.md

> * **Test**. If you fix something prove it, write a test that illustrates the issue before you fix the issue and validate the test. If you add a new feature it needs tests, so that we can understand its intent and try to avoid regressions in future as much as possible.

**Comment by dizzzz** [comment]
@adamretter you are basically right, but such an approach might and will withhold contributors to file any fixes for obvious but hard to test bugs ; we need to try to take it a bit pragmatic side...

**Comment by adamretter** [comment]
@dizzzz Sure, but this is easy to test.

Not wanting to write tests or learn how to write tests, is not an excuse for not doing so. I am always happy to teach how to write tests if someone needs help.

I would probably be more relaxed about the odd PR without tests, but it is the case that I frequently have to ask for tests in PRs. If there are not tests for code that adds risk and unmaintability issues; As it is we have accumulated far too much of this technical debt in the past. Time to draw a line.

If we are not in agreement, we should also discuss this in the upcoming community telco?

**Comment by dizzzz** [comment]
we are in agreement for sure! But sometimes a combi of code-inspection and the current test suite might be enough.

**Comment by adamretter** [comment]
@dizzzz Agreed. In this case the current test suite doesn't test this. Hence my call for tests :-)

**Comment by shabanovd** [comment]
@adamretter if you want test - write one. my contribution ends on point to bug place. you should not expect more from me here.

**Comment by adamretter** [comment]
@shabanovd So we should merge your code without tests, because you are special?
This is not the first time you have abandoned PRs because you refuse to finish them by writing tests. Personally I don't think your behaviour is really in the spirit of community collaboration (which is a documented process). That is just my opinion though. AFAIK no one else sends PRs and then expects *you* to write the tests for them.

More than likely, I will write the tests again, because you won't *sighhh*. It's not like I don't have other PRs to work on!!!

**Comment by dizzzz** [comment]
Gents......

**Comment by adamretter** [comment]
@dizzzz @shabanovd For reference here is how you test such code - https://github.com/eXist-db/exist/blob/develop/test/src/org/exist/http/AuditTrailSessionListenerTest.java

I have now merged this along with its test. The test only took me 10 minutes to write :-)

**Comment by shabanovd** [comment]
@adamretter can you do not send commits to develop branch without reviews?

I don't think that your test cover current PR anyhow.

**Comment by adamretter** [comment]
@dizzzz Why do you think the test does not cover your changes. If you undo your change https://github.com/eXist-db/exist/pull/1267/files#diff-6fe9b581946cde755de400a26ab9400eR164 then the test will fail.

**Comment by dizzzz** [comment]
@adamretter I did not write anything ?

**Comment by adamretter** [comment]
@dizzzz Sorry. I meant Dmitriy (edited above)

**Pull request closed without merging**
