### PR TITLE
Upgrade of log4j2 framework 

### PR DESCRIPTION
**Pull request by dizzzz**
### Description:

upgrade of log4j framework

### Reference:

https://logging.apache.org/log4j/2.x/changes-report.html#a2.8

### Type of tests:

- run unit testsuite
- start database

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz Looks good. Just one thing -  I think  you also need to update the `.classpath` file

**Comment by dizzzz** [comment]
and the netbeans files........ a switch to maven would be a help here :-)
actually I think this file (c|sh)ould be generated

**Comment by shabanovd** [comment]
@dizzzz really - that files do not autogenerated and IDE will raise error.

**Comment by dizzzz** [comment]
Done

**Comment by dizzzz** [comment]
@shabanovd  I only wanted to state that this file is soo simple and could be derived from other sources. Just like the netbeans project files, the fileset is not complete. I'd rather see these removed, because clearly no-one used them as they are outdated... all the time. they just do not work :-)

**Comment by shabanovd** [comment]
@dizzzz can you add note to next call agenda?

**Comment by dizzzz** [comment]
re: removing the project files?

**Comment by shabanovd** [comment]
@dizzzz yes, `netbeans and eclipse project files`

**Comment by adamretter** [comment]
@dizzzz So NetBeans and IntelliJ can work directly with Maven projects without the need for generating extra project files. Maven also have a plugin for generating Eclipse project files

**Comment by dizzzz** [comment]
@adamretter I know, I know

**Pull request merged**
