### PR TITLE
add testsuite for literals in curly braces

### PR DESCRIPTION
**Pull request by line-o**
### Description:

This adds tests for https://github.com/eXist-db/exist/issues/291

### Type of tests:

xqsuite

### CODE REVIEW

**Comment by duncdrum** [comment]
with a 4.x.x backport this should go into the next 4.x release imv (i.e. has the wrong milestone)

**Comment by adamretter** [comment]
@line-o #2140 is now merged. Could please rebase this on the develop HEAD? We can then look to get this PR merged.

**Comment by adamretter** [comment]
@line-o So these tests are passing CI. Is that as you would expect?

**Comment by line-o** [comment]
@adamretter yep, the one that would fail would also fail to compile.

**Comment by adamretter** [comment]
Thanks for your contributions @line-o :-)

**Pull request merged**
