### PR TITLE
Add auto deploy folder to 'dist'

### PR DESCRIPTION
**Pull request by dizzzz**
fix of https://github.com/eXist-db/exist/issues/410

### CODE REVIEW

**Comment by dizzzz** [comment]
please hold... I missed this PR: https://github.com/eXist-db/exist/pull/411

**Comment by dizzzz** [comment]
To Add: call resign task

**Comment by adamretter** [comment]
@dizzzz Is this ready to land?

**Comment by dizzzz** [comment]
this part, yes
in the original contibuted PR there was a sign step, but it should not be included;
this PR should be OK

**Pull request merged**
